ultrabug/py3status

py3status/core.py

This just allows py3status to be closed/restarted faster.

make Runner threads daemon so they die when we kill py3status

---

py3status/py3.py

from #1062 and possibly related to #859 
because `py3.get_output()` gave the actual module output it can be altered by the consumer.  By giving a copy we prevent this from happening.

get_output() returns copy of output not actual output

---

py3status/composite.py
py3status/py3.py

A simple fix for #1079
`Py3.notify_user()` only shows the text if it gets a Composite as input

only show text of Composite when notifying user

---

py3status/formatter.py
tests/test_formatter.py

The formatter is nice but still has some problems, highlighted in #1003 
We want nice output like `1 result`, `2 results` currently this is not possible.
This PR fixes this.  To achieve the above we can now use `format = '{count} result[\?if=count>1 s]'`
So we can now do
```
current functionality
\?if=count    # test if count is truthy
\?if=!count   # test if count is falsy
check for a value
\?if=count=5  # test if count == 5
\?if=!count=5  # test if count != 5
compare
\?if=count<5  # test if count < 5
\?if=count>5  # test if count > 5
negated compare
\?if=!count>5  # test if count <= 5
```
values can be string, numeric or boolean.
This implementation is crude as it does very basic parsing of the condition (this could be improved but makes this PR more complex)
it would also allow formats …

formatter: allow conditions

---

py3status/modules/clock.py

We replace legacy methods... 
```
def on_click(self, i3s_output_list, i3s_config, event):
def clock(self, i3s_output_list, i3s_config):
```
... with shiny new ones.
```
def on_click(self, event):
def clock(self):
```

clock: deprecate legacy methods

---

py3status/modules/systemd.py

I tidy up the code and the docs. We replace legacy method `def check_status(self, i3s_output_list, i3s_config):` with shiny new one `def systemd(self):`. Nothing changes.
We should see if we can get more placeholders by using `GetAll` D-Bus properties as some of them can be nice and/or useful. `SubState` looks interesting as it could give us more states / information. EDIT: And if we can use `CACHE_FOREVER` + `self.py3.update()` with listener / PropertiesChanged thing. Idk.

systemd: clean up docs and code, deprecate legacy method

---

py3status/modules/exchange_rate.py

We swap out `re.findall` with a well-established method `self.py3.get_placeholders_list`.

exchange_rate: use helpers

---

py3status/modules/do_not_disturb.py

No need to run a killer thread if dunst is so nicely reacting on custom signals.
This was proposed by @tobes [a long long time ago](https://github.com/ultrabug/py3status/pull/598#issuecomment-267867768) 🙂 
Since then dunst found a new maintainer and was drastically improved, so I'm back on dunst 😄 
----
I can't make it forget history, @tobes, `-SIGSTOP` just hangs my dunst - if possible I would very much like to clear history - could you try as well and maybe give me a hint?
-----
Deliberately not doing any other improvements so that this can be merged faster.

[do_not_disturb] Add better support for dunst

---

py3status/modules/graphite.py

We can validate the config once in `post_config_hook` instead of the loop to optimally reduce cycles if applicable. There could be some other things to tweak, but likely not something for us to toy with.

graphite: use post_config_hook

---

py3status/core.py
py3status/events.py
py3status/i3status.py

Currently we check event and i3status threads are alive in the main loop.  This moves these checks into the actual modules.  Also remove some other cruft in the loop that is no longer needed.

move thread checks out of core main loop

---

py3status/modules/whoami.py

We deprecate the `deprecated` dict and other things to annihilate the lines. _Taking a break from working on future `keyboard_lock` to push this..._

whoami: annihilate the lines

---

py3status/command.py

Bugfix.
```
3d [chris:~] % py3-cmd                     
Traceback (most recent call last):         
File "/usr/bin/py3-cmd", line 11, in <module>                                       
sys.exit(send_command())               
File "/home/chris/src/py3status/py3status/command.py", line 294, in send_command 
msg = msg.encode('utf-8')
UnboundLocalError: local variable 'msg' referenced before assignment
```

py3-cmd: add exit if no command

---

py3status/modules/mpris.py

Deprecating `build_composite` in favor of `safe_format` for `mpris`.
```
.../py3status/py3.py
--------------------
def build_composite(self, format_string, param_dict=None,
composites=None, attr_getter=None):
"""
.. note::
deprecated in 3.3 use safe_format().
```

mpris: deprecate build_composite

---

py3status/parse_config.py

We remove hardcoded `not in range(1, 6)` to accept any integer number. Users with this kind of mouse will be able to use `10`, `15`, or `19` if they want to. This works fine with my `8`, `9` (back, forward).

parse_config: onclick accepts number 1-20

---

py3status/modules/player_control.py

Uses `self.py3.command_run(cmd)`
Omits `import subprocess` and `/usr/bin`.
Thoughts on this module? The `debug` config  is made for audacious as it does not display anything with `mpris` (eg vlc). We could deprecate that config and do the logging ourselves.
~~The alternative~~ Another idea is to scrap the whole thing and write it from scratch using `playerctl` https://github.com/acrisci/playerctl ... Supports spotify, vlc, audacious, bmp, xmms2, and others.
Anyhow... Hopefully, a hassle-free PR... just like the old ones. 🎃  Tested OK w/ VLC.

player_control: use helpers

---

py3status/modules/pomodoro.py

Replacing `__init__` with `post_config_hook` for `pomodoro`.
I'd like to merge my format-friendly pomodoro PR someday. Slightly more informative too.

pomodoro: use post_config_hook

---

py3status/modules/xsel.py

This is a bugfix. In `xsel`, the bouncer `\n` continues to kick out the drunk line out of the bar...
*"Enough is enough."* The fix? We absolutely remove excess whitespace chars everywhere.

xsel: remove excess whitespace chars

---

py3status/modules/github.py

Adding support for GitHub Enterprise by making the GitHub URLs configurable by the end user.

github: add support for GitHub Enterprise

---

py3status/modules/uname.py

We remove `class Meta` and use `dictionary comprehension` to annihilate the lines. 😊 
I think it is nice not to keep `{machine}` in default format because it does not change for most users... except in some rare scenarios like using `py3status` on virtual machines.
This also saves space on the bar... And now I think this is more perfect than `static_string` too.

uname: annihilate the lines

---

py3status/modules/mpris.py

Removing `__init__`. Moving things to `post_config_hook` for `mpris`.
Initializing `self._states` dict once in `post_config_hook` for `mpris`.
Raising `KeyboardInterrupt` in the beginning instead of halfway for `mpris`.

mpris: use post_config_hook, and for the states too, and raise KeyboardInterrupt earlier

---

py3status/modules/github.py

I think we don't like slashes. This should allow users to copy and paste URL into a config and not having to worry about the trailing slash. If you prefer `rstrip`, let me know. I think `strip` may be a slightly faster (not that it matter....)

github: remove the trailing slashes

---

py3status/modules/moc.py

Seperate PR for small cleanup after fixing the `moc` bug with `rapid refresh` PR.
* Rephrasing.
* Use `list` so we don't have to convert `str` to `list` every time. This helps? 
* Adding an example of configuring extra buttons not listed in module.
* Fixing `dict` so we don't have to tilt too much... Right? Ty.

moc: clean up docs and codes

---

py3status/modules/xsel.py

I don't like old string lying around in my clipboard visible all the time and if it is a password even more so. That is why you can now click the string to clear it out.
To not lose the old copied strings one can optionally turn on logging.

Clear clipboard onclick and optional log (xsel)

---

py3status/modules/process_status.py
py3status/modules/systemd.py

Seperate pull request for `process_status`. We make the docs suck less... Should I start merging formats everywhere? EDIT: This is the last `default format for this module` string. 👌

process_status: clean up the docs

---

py3status/parse_config.py

#1171 reports an issue on OpenBSD due to config file encoding guessing.
This fixes the issue by assuming utf-8 if guessing fails.  It allows users who could not run to use py3status but does not change existing behaviour for those that can run py3status already
I think it should get in 3.7 as it is trivial and allows us testing on OpenBSD

assume utf-8 if we cannot guess file encoding

---

py3status/modules/air_quality.py

Bugfix. `air_quality` throws an exception when offline. This will keep the module moving.

air_quality: fix attributeerror exception

---

py3status/modules/backlight.py

Until I learned about `py3-cmd` I was using my own script for changing brightness. I'm missing one feature in the py3status'es module that I had in my script:
I usually use a large `delta` value (`10`), but my screen is very bright and in the evening I want to fine-tune the brightness and use some value like `2` or `3`. With the constant `delta` it is impossible, it jumps between `10` and `1`.
This change introduces a `brightness_slow` parameter (please suggest a better name), which is a threshold, after which the value is being changed by a minimally possible value instead of the `delta` (I know the hardcoded value of `1` might change in #1077).
My favorite values:
```
backlight {
brightness_delta = 10
brightness_slow = 10
}
```
How this looks:

[backlight] Allow slower value change after a threshold

---

py3status/modules/xrandr_rotate.py

Excerpted from the log...
```
INFO Module `xr`: ---------- RUNNING ----------
INFO Module `xr`: xrandr --output DP-2 --rotate left
INFO Module `xr`: ---------- RUNNING -------
INFO Module `xr`: ---------- RUNNING ----------
INFO Module `xr`: xrandr --output DP-3 --rotate left
INFO Module `xr`: ---------- RUNNING ----------
```
```
INFO Module `xr`: ---------- RUNNING ----------
INFO Module `xr`: xrandr --output DP-2 --rotate normal --output DP-3 --rotate normal
INFO Module `xr`: ---------- RUNNING ----------
```
Enuff said.
Okay, maybe not. I have two monitors. This will always run the `xrandr` command once instead of once, twice, thrice, etc. Somebody out there have six monitors. Poor soul. This removes flickering too.

xrandr_rotate: run command once

---

py3status/__init__.py
py3status/core.py
setup.py

This allows to run py3status using the gevent event loop which effectively reduces the load of the system by running everything in a concurrent and non blocking way.
Note that py3status' setup now supports extra requires to allow users to choose their dependencies flavours.

add option to enable support for green threads using gevent.

---

py3status/modules/online_status.py

Reviewing a new module #1163 has been brought to my attention that we're not applying the `timeout` config to the `ping` section. This PR will include the `-W` option for `self.timeout`. Tested OK in `python2` and `python3`.
Like `ping`, I elicted no response from contributers and/or owners for days. My `timeout`, in days, have been reached so I will stop contributing until further notice. We can try again when everybody is not too occupied. Have a good day. :-)

online_status: fix timeout for ping

---

py3status/py3.py

*Sighs*. My bugfix for the `pretty_cmd` with `basestring`  AND the `shell` aspect in `py3.py`.
If there is an exception with `basestring` and `shell=True`, it'll print `Command p y 3 s t a t u s`. If there is an exception with `[cmd, cmd, cmd]` and `shell=True`, it will print correct. If there is an exception with `[cmd, cmd, cmd]` and `shell=False`, it'll print correct.
The `command_output` have an extra statement and I missed one of possibilities to test. In this, we get the `pretty_cmd` early and on its own.
Initially, it may be easier to just print everything as-is... but this should fully fix it. Also, for the future... we should merge pull requests now... so we can catch minor bugs (if any) on all working branches before the releases... instead of last days. Cheers. 👍

py3: fix pretty_cmd for shell

---

py3status/modules/timer.py

Use `self.py3.COLORS` instead to respect users's authoritah! ![2017-12-09-173229_87x24_scrot](https://user-images.githubusercontent.com/852504/33800539-4a540886-dd07-11e7-9602-7832062b3e6b.png) ![2017-12-09-173752_92x30_scrot](https://user-images.githubusercontent.com/852504/33800562-cfa2b816-dd07-11e7-8909-9de22517983e.png) ![2017-12-09-173649_115x26_scrot](https://user-images.githubusercontent.com/852504/33800552-9cb3cddc-dd07-11e7-9c5f-823decae293c.png) 
The colons can be duplicated via `format = '[\?color=#ccc {timer}]'`

timer: add colors

---

py3status/modules/deadbeef.py

I used `deadbeef` for short time yesterday to help out someone and sometimes later, I forget I still have the module running in the bar when I saw too many `deadbeef` in the log. I wish to fix this.
We can make `deadbeef` relax more... so we're changing `cache_timeout` to `5` and we're adding new config `sleep_timeout = 20` where the module can sleep longer between intervals when it's not in use.
Before
```
Not in use..... 1 second..... 60 refreshes per minute.
In use.....  1 second..... 60 refreshes per minute.
```
After
```
Not in use..... 20 seconds..... 3 refreshes per minute.
In use.....  5 seconds..... 12 refreshes per minute.
```
Ty. 🎧

deadbeef: add sleep_timeout

---

py3status/modules/volume_status.py

The module will `check_command` when `self.command` is None.
The module will not `check_command` when `self.command` is not None.
I had `command = 'pamixer'` in the config and `pamixer` was not installed. This leads to an exception. I fix the `post_config_hook` so it can check everything. This occurs now because I did a fresh installation not long ago. Ho ho hum. :-) 
EDIT: Log for historical archiving purposes.
```
2017-10-22 13:14:27 WARNING Instance `volume_status`, user method `current_volume` failed (FileNotFoundError) volume_status.py line 160.
2017-10-22 13:14:27 INFO Traceback                                                                                                     
FileNotFoundError: [Errno 2] No such file or directory: 'pamixer'
File …
```

volume_status: check the binaries

---

py3status/modules/yubikey.py

This module is designed to show a visible indication that YubiKey is waiting for a touch.
Basically it uses a bunch of hacks to solve [this issue](https://forum.yubico.com/viewtopic.php?f=35&t=2397). 
Owners of YubiKey, especially YubiKey 4 Nano would be extremely glad for this module 🙂
How it works:
- It requires [maximbaz/yubikey-touch-detector](https://github.com/maximbaz/yubikey-touch-detector) to run in the background and subscribes to updates from it via unix sockets.
**DEMO**:

Add YubiKey module (show a visible indication that YubiKey is waiting for a touch)

---

py3status/modules/keyboard_layout.py
py3status/modules/thunderbird_calendar.py

This module displays Thunderbird Calendar tasks:
>    {due} : due tasks
>    {completed} : completed tasks
>    {current} : title of current running task (sorted by priority and stamp)
Caution, in order to work user must set **profile_path** and enter the full path of his/her thunderbird profile folder in the i3satus config:
> ...
> order += "thunderbird_calendar"
> ...
> thunderbird_calendar {
>     profile_path = "/home/user/.thunderbird/1yawevtp.default"
>     format = "✔ {due} - {current}"
> }
> ...
Any input would be greatly appreciated.

thunderbird calendar tasks module

---

py3status/modules/google_calendar.py

Hey, I noticed this bug recently when resuming the module from sleep. What happens is, when the system resumes from sleep, clicking on the module will refresh it, but since there usually isn't an internet connection for a few seconds after resuming, when the module builds a response, it will display a negative value in `format_timer` since it's calculating time_delta based on an event that is already over. 
How to reproduce:
1. Make an event for some time in the future.
2. Put the computer to sleep.
3. Resume from sleep AFTER the event has passed.
4. Click on the event in py3status to refresh the module.
The module should now display a negative  value for `format_timer`, like so `(-xd xxh xxm)`.
The small change I made fixes this behavior.

google_calendar: fix resume from sleep bug

---

py3status/modules/volume_status.py

>@tobes a) Users who just want things to work. To me a good example would be the volume_status as a user I should be able to just do order += 'volume_status' and should get a sensible working volume control (I don't think we are here as the volume changing controls isn't by default)
:ok_hand: 
EDIT: Thoughts on `button_mute`? Leave it configured or leave it `None`? 
EDIT: After considering it some more, I think maybe it sucks that users have to configure buttons, but after configuring it once, they can leave it alone for long time. I said this because I made some other modules and had configured them to `None` too.

volume_status: enable mouse buttons

---

py3status/core.py

Hi. I'm not familiar with the core/py3 code. This closes #1082 for me.
```python
else:
self.log(msg, level)
```
It looks like `py3status` want to log all notifications just in case (eg, error, message, etc) which is why I added a parameter `module_msg` in `py3.py`. Both seems okay to me. Pls criticize my werk. Thx.

core: make notify_user less ambiguous in the logs

---

py3status/py3.py
py3status/request.py

Some websites needs cookies in order to work. With this modification, you can specify a `CookieJar` or subclass object to `py3.request` in order to exploit cookies.

Handle cookies within request

---

py3status/modules/xrandr_rotate.py

>screen: display output name to rotate, as detected by xrandr.
If not provided, all enabled screens will be rotated.
(default None)
Git bisect. None.
Old: If you provide a `screen` and have >1 outputs, it'll display `ALL` and rotate only that output.
New: If you provide a `screen` and have >1 outputs, it'll display `DP-2` and rotate only that output.
A minor bugfix... ~~plus a quick `psc` check to ensure we have a good `screen` too.~~

xrandr_rotate: display screen properly

---

py3status/modules/coin_market.py

* Expose a new placeholder (upstream)
* Don't sort the placeholders. Leave it as-is. Better readability. 
* Add `format_datetime` for `{last_updated}` placeholder. The code is written in loop to deal with potential future `datetime-related` placeholders. It might be a bit excessive and/or not perfect as there is no other `datetime` placeholders to test.
* Docs/code cleanup.
Note: The time is not  always same. I saw coins that were 5 minutes apart. The users can use `{last_updated}` now... cuz nobody know epoch.

coin_market: multiple changes

---

py3status/core.py
py3status/i3status.py
py3status/module.py
py3status/module_test.py

I forgot I'd done this.
It is slightly complicated as it adds a generic way to add random a user defined tasked to the queue.  If accepted I'll make the i3time update one of these too.
Maybe we should make them run in a thread like the py3status modules to simplify stuff too

task to monitor i3status thread

---

py3status/modules/google_calendar.py

Parroting.
>Simplify the code.
>I think this makes things cleaner and is worth the minor change

google_calendar: remove unused variable

---

py3status/modules/coin_market.py

Parroting.
>Simplify the code.
>I think this makes things cleaner and is worth the minor change
>This needs #1246 as otherwise it slows down startup of py3status.

coin_market: remove first_run

---

py3status/core.py
py3status/module.py

Currently modules are loaded in series and so one slow module running it's `post_config_hook()` blocks starting all modules.
This PR allows each module to be started in a thread.
We need to ensure that the module has been setup before it updates. hence `self.enabled`

start modules in threads to parallelize

---

py3status/modules/github.py

Simplify the code.
This slightly changes the behaviour as we now do not display until we get data.  Before we showed ?.
I think this makes things cleaner and is worth the minor change
This needs #1246 as otherwise it slows down startup of py3status.

github: don't treat first run as special

---

py3status/modules/backlight.py

this is an alternative to #1076
It allows the user to do `format = '{level:2.f}'` if they want to see as a float
The default output should be as before.

allow brightness as a float

---

py3status/modules/air_quality.py
tests/test_module_doc.py

Hi. Quick rundown on this pull request. The first commit. We introduce all placeholders instead of using few placeholders. It's also something that we could merge in hopefully without any issues.
The second commit. I combined `AQI`, `category`, and `color` into one `quality_thresholds` config param. This would break somebody's config (if they have one) because of all this combinations. This, of course, is not perfect when it comes to supporting other URLs... because it's made to work with only one URL right now.
This should be easier for others to support a different `AQI` setup should they want to try it. Maybe if we get some URLs first to figure out the next step from there. I simplified many things to make `air_quality` more readable. This got `thresholds` for `aqi` and we're using …

air_quality: new module from scratch

---

py3status/modules/window_title.py

I made this pull request to add `{class}` placeholder because that's what somebody in https://github.com/ultrabug/py3status/issues/1141 may be trying to accomplish using third-party scripts. Actually, I am not so sure as he may be wanting to `scrub` certain patterns inside the `{title}` for couple of reasons.
* Some applications can have class in their titles... making `{class}` useless.
* Some applications can start with class, then title.
* Some applications can start with title, then class.
* Some users may prefer to display `{class}` alone.
Having universal `scrub` option could be sufficent to scrub this kind of `window_title` irks.
----------
I also found a minor issue with `window_title`... Using title below as an example...
```
Formatter new features · Issue #752 · …
```

window_title: add new placeholders

---

py3status/core.py
py3status/events.py

To test these changes it is easy to add a `sleep(0.5)` in a module like `volume_status` and then create some scrollwheel events.
This PR allows events to be handled in threads.  This is good because
* An event no longer blocks other events being handled.  This is a problem if an event takes a long time to run
* We do not end up with a backlog of events that can confuse the user as they are handled when they are triggered rather than in a queue.
To work smoothly we also discard some events/updates.  A module should only handle events one at a time this includes it's own scheduled updates.  So we only let a module instance run one thing at a time.  There is a complication that if a module has a scheduled update during an event the update is discarded.  If the event does not trigger an …

Run event in threads to fix latency problems

---

py3status/storage.py

#1261 running modules in test mode failed if they used storage.  This is a quick fix for that issue where we cannot get the `i3status_config_path`.
Really we need a proper fix where we load test modules via the full stack.  We will have to consider if test modules can write to our datastore as that may not be something we want them to do.  But that is for another day.

allow test modules to use storage

---

py3status/modules/i3pystatus.py

So after the fun of #687 I had a go at i3pystatus modules support.
In some ways they are easier, there is a lot less code but they are also more problematic.  ~~Some modules eg weather cannot easily be added to the py3status config (or at least I haven't worked out an easy way to do it).  Realistically full support will be difficult.~~  They also clash really badly on `format`
Their current release on pypi is partially broken so some modules do not work eg gpu_mem and they have no support for python2.
It's interesting to see what the opposition are doing eg they support double clicks (which is quite easy but gets confusing with the scroll-wheel (is that multi-clicking or just lots of really fast single ones).  Also from playing on i3blocks it seems there are many more mouse buttons …

i3pystatus support

---

py3status/modules/xrandr.py

Allow user to specify the resolution they want for each screen using a parameter {output}_mode in i3status.conf

allow overiding xrandr resolution using {output}_mode

---

py3status/modules/do_not_disturb.py

I use the do-not-disturb module with `dunst`, and prefer to use `SIGUSR2` to bring it out of DND mode (`SIGTERM` actually causes the process to exit). This patch makes the set of signals configurable.

Do-not-distrub configurable signals

---

py3status/formatter.py

This removes the insignificant trailing zeroes and the decimal point too if there are no remaining digits following it, eg `50.000` and `5.500` becomes `50` and `5.5`.

formatter: add {:g} to remove trailing zeroes

---

py3status/modules/sysdata.py

I rename long variable name `self.values` to `sys`. That's it. More readable this way.

sysdata: rename self.values to sys

---

py3status/modules/sysdata.py

I create `self.keys` where keys will be kept. 99% keys and 1% caches... then I fill up the `self.keys` with names for `load` to zip up the load stuffs with.
In `sysdata: over 9000 optimizations, 3 bugfixes`, I rename the loads.
* From... `('load1', 'load5', 'load15')`
* To... `('load_1min', 'load_5min', 'load_15min')`. 
It probably would be just `('1min', '5min', '15min')` in new module `loadavg`.

sysdata: zip up the load stuffs

---

py3status/modules/sysdata.py

I think it is cleaner with `self.key['swap']` because we initialize it once and it stay out of way everywhere in the code... but we'll see how that goes. I do same thing for `swap` here and `mem` next.

sysdata: zip up the swap stuffs

---

py3status/modules/sysdata.py

The differences between load averages with `timeit`.
Using `/proc/loadavg`.
```
def _get_loadavg():
"""
Get the load average from /proc/loadavg :
"""
with open('/proc/loadavg', 'r') as fd:
line = fd.readline()
load_data = line.split()
load1 = float(load_data[0])
load5 = float(load_data[1])
load15 = float(load_data[2])
return load1, load5, load15
sys = {}
keys = ['1min', '5min', '15min']
sys.update(zip(keys['load'], _get_loadavg()))
35.29173210001318
35.370016951987054
34.465308131999336
35.80027389898896
```
Using `os.getloadavg()`...
```
sys = {}
keys = ['1min', '5min', '15min']
sys.update(zip(keys['load'], _get_loadavg()))
6.896805440017488
6.9395914629567415
7.0003847110201605
6.975486984010786
```
Using `os.getloadavg()` and some more
for new `loadavg` module hopefully one day.
``` …
```

sysdata: replace /proc/loadavg with getloadavg()

---

py3status/modules/volume_status.py

This PR partially relies on #1267 
volume_status module calls commands by using functions directly from subprocess
instead of using helper function from py3. It also fails to parse some commands
output with non-English locale set. 
This PR makes volume_status use py3.command_output function, which in
conjunction with #1267 fixes command parsing issue.

volume_status: use py3.command_output

---

py3status/modules/external_script.py
py3status/py3.py

Many modules parse command's output by searching for keywords which
are mostly English words. This fails when command is able to provide
localized output based on user's locale
This PR adds to `localized` parameter (False by default) to py3.command_output 
to control whether it should set environment variable LC_ALL to C which
forces application to use default (mostly English) locale.
Having this, command output will be independent from user locale.
To consider:
- localized = False by default means that existing modules have to be modified if they
rely on output being localized, but since most (all?) modules scrap data from command's
output instead of displaying the output directly, it might not be a problem.

py3: command_output call command with LC_ALL=C

---

py3status/events.py

With the events running in threads changes the on_click events would not run if the module was updating.  This caused some issues such as #1270. This PR runs the external on_click in a separate thread that is not 'dropped' this should resolve the issue.
@maximbaz it would be great if you can see if this fixes your issue.

Allow external on_click events to run immediately

---

py3status/py3.py

This allows us to simplify some modules code see #1212
```
if case_1:
cached_until = self.cache_timeout
if case_2:
cached_until = 0
else:
cached_until = self.py3.CACHED_FOREVER
return {
'cached_until', self.py3.time_in(cached_until)
}
```
Slight cleanups to docs etc
`CACHE_FOREVER` is now `object()` to help keep things cleaner

allow time_in(CACHE_FOREVER)

---

py3status/py3.py

Sometimes we could run into this (rare) scenarios.
```
if self.thresholds:
for k, v in data.items():
try:
self.py3.threshold_get_color(v, k)
except Exception:
pass
return data
```
```
try:
self.py3.threshold_get_color(data.get('number'), k)
except Exception:
pass
```
```
self.py3.threshold_get_color(data.get('number', -1), k)
```
This PR allows us to do stuffs without worrying about `None` or try/except.. eg
```
if self.thresholds:
for k, v in data.items():
self.py3.threshold_get_color(v, k)
return data
```
```
self.py3.threshold_get_color(data.get('number'), k)
```

py3: make thresholds take None for an answer

---

py3status/modules/transmission.py

Hi. I made a new module `transmission`. This requires `transmission-daemon`.
We can display basic `torrent` statistics. Should the users want them, we can stop/start/verify the torrents using `scrolling` and `clicking`. It's possible to perform other actions too using `button_run` and `on_click`.
If you are using `transmission-daemon`, then you might be using web-based client. Transmission offers remote `GTK`/`Qt` clients too that would connect to this daemon. This just makes things a bit nice and I added an `on_click` example that can take the users to the web-based client. :fallen_leaf: 
Idle.
Seeding -- Sowwy. Bad screenshot -- See next.
Stopped.
Verifying.
Pretty.

add new module: transmission

---

py3status/modules/deadbeef.py

Without this, it prints `[]` (aka not running). We make sure it's installed first.

deadbeef: not installed

---

py3status/modules/hddtemp.py

Hi. I made a new module `hddtemp`. This module display hard drive temperatures. I don't want this to go in `sysdata` and I think `sysdata` should be split up into `lm_sensors`, `loadavg`, etc... anyway for more clarification and more flexible / easier in customizing.
The screenshots shows `darkgray` but is white in default... as is traditional. I wonder about extending color palette... to support ~`color_default`~ `color_primary`, `color_secondary` too to help with the overall theme so users can change colors for all modules easily via few color options in `general {}`.
The thresholds contains `blue` and `orange` color too.... Too cold and almost too hot.
EDIT: The screenshots are slightly outdated. No color `blue`, `orange` and `red` in this one.

add new module: hddtemp

---

py3status/modules/taskwarrior.py

Add a new `task_args` to the `taskwarrior` module to allow customizing the arguments passed to the `task` executable.

taskwarrior: make the command customizable

---

py3status/modules/hddtemp.py

This should stop the `SAMPLE DATA ERROR` for `hddtemp` module.

readthedocs: fix hddtemp screenshots

---

py3status/modules/air_quality.py
py3status/modules/backlight.py

Hi. We talked about errors briefly in #1310. I brought up the possibilities of supporting errors in `format` like the one I did in `air_quality`... for bad modem state `MM_MODEM_STATE_FAILED`. I later realize/review that this is not the ideal way to deal with non-common errors. I go ahead and replace error format with error helper here... and added missing `request_timeout` config to test this error.
We still can take advantage of error formats in some modules such as `mpd_status` to ignore common  `is_authenticated`, `is_connected` errors because we don't always run or want to run `music player daemon` on startup. Many thanks. :baby_chick:

air_quality: replace error format with error helper

---

py3status/py3.py

With `format_notification` exposed and very customizable in my branch for `pomodoro`, this allows ~~the users~~ py3status to dismiss empty notifications due to the respected formatting tricks and/or the user preference to turn them off via `format_notification = ''`. Let me know if this is okay.

py3: dismiss empty notifications

---

py3status/py3.py

I ran into what I believe is a bug with `sysdata`. When we use `gradients = True` inside `sysdata` and the value is well over the threshold, we will get a white gradient. ~~Also, it seems to skip on every other threshold too.~~ EDIT: This fixes it for me...

py3: return gradients properly

---

py3status/modules/hddtemp.py

Because of `(0, 'deepskyblue')` instead of `(24, 'deepskyblue')`, the `thresholds` does not work correctly with `gradients`. This just fixes it.
I also added two more colors for temperatures less than `24` and more than `51`. Both are achievable. This way, we can support `gradients` without touching the `thresholds`.
I fixed the spacing for the screenshots too.

hddtemp: accuracy thresholds and gradients

---

py3status/modules/xrandr.py

Documenting `xrandr`'s potential for mischief in order to shut down a long-standing issue #580.

xrandr: document issue #580

---

py3status/modules/weather_yahoo.py

Minor bugfix for `3.8` release. Assigned to @ultrabug. 
* Bug 1: Printed wrong dates for me. `2am` instead of `2pm`. Ooh so close.
* Replaced `%H` with `%I` in `DATETIME_GENERAL`. Ok now.
* Removing `self.py3.log()` and `try/except`.
* I have been using this for weeks. No issues.
* Cleanups.
* Minor QA to follow coding standards.
* Simplfying `init` lines in `psc` via looping.
* Better example for users. Use Yahoo! color instead of `bad` color.
* Add extra screenshot.

weather_yahoo: date bugfix and a series of changes

---

README.rst

Update README with a reference to the new `py3-cmd` util so users are aware they don't have to send `USR1` for bar updates.

add py3-cmd to Control section of README

---

py3status/py3.py

This is similar to `backlight: better xbacklight detection` pull request.
I was testing sounds in `pomodoro` with `mp3` file.
* I have `paplay` installed automatically due to `pulseaudio`, `pulseaudio-utils`. This does not play the audio for me. I get this in the terminal:
~~~
~/Downloads  $ paplay test.mp3
Failed to open audio file.
~/Downloads $ echo $?
1
~~~
* I did not have `aplay` installed. I tested it anyway. This play the audio okay.
I think it would be nice if we can avoid `pulseaudio/alsa` stuffs and just use external `ffplay` from `ffmpeg` package that's regularly updated and should be available everywhere just like `paplay` and `aplay`. EDIT: This supports more audio and video formats too.
```
FFplay is a very simple and portable media player using the FFmpeg libraries
and the …
```

py3: play sounds with ffplay

---

py3status/modules/xrandr.py

Assigned to @ultrabug 
Hi. For first commit... If we defined a primary output, xrandr will put "primary" in `mode` instead of a mode (resolution). This avoids that and will give mode instead (code borrowed from `xrandr_rotate`). It seems that we're not using `mode`, `state` for anything (other than one-off logging) so it could be ~~simplified~~ removed. Also, I think we don't need try/except too.
The second commit addresses #623 for me. It turns out that if you assign multiple outputs to `--pos 0x0` (which was what happened here with no `xrandr` configs), you get weird clone behaviors. The solution is to add a `{}_pos` config in `xrandr` to assign a position. This commit will set the `0x0` for first output then `--right-of {previous_output}` repeatedly.... preventing multiple `0x0` …

xrandr: parse mode properly

---

py3status/parse_config.py

similar to `env()` (#1149), `exec()` allows you to capture the output of a shell
script. This is useful for example when you need to store a password in
a relatively safe manner.
Example:
imap 0 {
password = exec(pass show email/foobar|head -n1)
}
you can also force casting to `str` (no-op), `int`,`float` or `bool`. Bool behaves differently compared to `env()`: it returns a true value when the output is `1` or `true`, or when the script returns nothing on stdout and its exit code is zero. (meaning, when your script exits with a non-zero exit code and you've forced casting to bool, it'll be falsy)
also see https://github.com/ultrabug/py3status/pull/1210#issuecomment-376587858, where it was brought to my attention. 
**caveat**: it is parsed via a regex; parsing stops at the first `)`. (but …

allow executing shell code in the config (e.g. safely store passwords)

---

py3status/modules/keyboard_locks.py

Cosemitc bugfix for `1.8` to address locks in wrong order and minor coding standards. Additionally, I added lock toggle support too via `xdotool` in this [branch](https://github.com/lasers/py3status/tree/keyboard_locks-add_xdotool) if you want to try it out. Ty.

keyboard_locks: rearrange locks

---

py3status/modules/pomodoro.py

Reading up on the technique, I believe this module is overworking everybody with an extra pomodoro before they receive a longer break. Also, `max_breaks = 4` may be confusing ~~for some users~~ because 4 pomodoros consist of 3 normal breaks and a longer break. Does this mean 4 max breaks or 4 max breaks with a longer break? Please see if this finding is accurate ~~first~~. Thank you.

pomodoro: fix off-by-one error, rename max_breaks to pomodoros

---

tests/test_formatter.py

Separating purely unrelated commits.

test_formatter: add {:g} to remove trailing zeroes

---

py3status/modules/arch_updates.py

Seems that the command line utility 'checkupdates' was moved from the pacman package to pacman-contrib.  I've updated the documentation to reflect the new dependency.

update documentation to include the pacman-contrib requirement.

---

py3status/core.py
py3status/module.py

This PR clears out some legacy cruft.
* remove support for multiple methods for a module - this add complexity and is no longer used by any modules for some time.
* remove legacy calling for modules
This is a first push on a fresh round of code cleaning.  It removes complexity from the modules which is no longer needed.  As part of this cleanup I have added a `while True/break` to reduce the diff for this PR.  If accepted then I will make another PR just to remove that.
There is still much room for further cleanups\simplification here but this feels like a good first step

Module simplify

---

py3status/modules/diskdata.py

When a disk was specified, _get_io_stats() was summing statistics
for all drives, not just the selected device name.

Fixes #1373 - Fix disk stats computation in diskdata

---

py3status/modules/wwan.py
py3status/py3.py

Hi !
I would like to used wwan_status but it was not working for me.
I think lot of laptop installation use networkmanger and modemmanager for wwan now.
This module based on wwan_status used NetworkManager, ModemManager and dbus services for get status.
This module doesn't report the ip address because i think it is useless. I can re-add it if you think this can be usefull, say me.
Also, i use this api doc https://developer.gnome.org/NetworkManager/stable/nm-dbus-types.html#NMDeviceModemCapabilities and I'm not sure if I find by the correct way the "netgen".
This is my first pull request for this great project, I hope my module will help.
For me the module do the job for the moment,
I listen you, I will be happy if the module is adopted, I can improve it, say me.
ps: I'm python newbie.

Add wwan network manager module

---

py3status/modules/net_rate.py

If an interface is specified, but has no statistics, handle the
exception more gracefully.

Fixes #1377 - Handle non-existent interfaces better

---

py3status/modules/gitlab.py

Hi. I made a new module `gitlab`. This module can fetch us a number of stars, forks, open issues, and open pull requests as well as several placeholders not shown on the list.
>Format placeholders:
>*{open_merge_requests_count} number of open merge requests, eg 1
>
>See https://docs.gitlab.com/ee/api/projects.html#get-single-project
>for explicit list of valid Gitlab placeholders to use. Not all of
>Gitlab placeholders will be supported. Here's some examples.
>
>*{name}              project name, eg py3status
>*{star_count}        number of stars, eg 2
>*{forks_count}       number of forks, eg 3
>*{open_issues_count} number of open issues, eg 4
>
>Number of notifications are not available at this time.
I wish to add `notification_count` too, but can't find where we can do that. Also, …

add new module: gitlab

---

py3status/modules/hddtemp.py

According to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891501, it looks like the real issue could be that @cyrinux simply got bit by a hddtemp byte ultrabug. I have included a workaround to remove non-printable characters, strip, and replace `G B` with `GB`. This will make his HDD `name` look nice.
@cyrinux Can you confirm this works okay for you? :beetle: :bug:   EDIT: #1355

hddtemp: workaround for hddtemp byte bug

---

py3status/formatter.py

Splitting them up at @ultrabug's request.
I need this to support nvidia_smi's custom `memory.used_percent` placeholder. We can parse that placeholder okay, but not `{memory.used_percent:.2f}`. This makes it okay. Resolves #1302 
master: `0.7, {test.abc}`
this: `0.7, 123.5`
```diff
diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index dbcec8c6..c2755866 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -16,12 +16,29 @@ class Py3status:
"""
"""
-    format = 'Hello, world!'
+    format = '{test}, {test.abc}'
+
+    class Meta:
+        update_config = {
+            'update_placeholder_format': [
+                {
+                    'placeholder_formats': {
+                        'test': ':.1f',
+ …
```

formatter: parse placeholders with periods

---

py3status/modules/air_quality.py

There is actually a 502 bad gateway on the api.
A quick fix to display nothing instead of a big error when api error.

air_quality: display nothing instead of error on api error

---

py3status/modules/volume_status.py

Skip `pamixer` if `pulseaudio` is not installed. Addresses #1393.

volume_status: skip pactl if no pulseaudio

---

py3status/modules/xrandr.py

This PR adds support for running a configurable command to set desktop background when display configuration is updated.
Whenever display configuration changes the desktop background isn't updated, causing white boxes to show. I would have the plugin have rerun my preferred command to configure the desktop background again, so I don't have to do so manually.

Add support for setting background

---

doc/py3-cmd.rst
py3status/command.py
py3status/modules/timer.py

Making it an official PR for @ultrabug to test it.
This is an alternative to https://github.com/ultrabug/py3status/pull/1358 to resolve py3-cmd issue https://github.com/ultrabug/py3status/issues/1349. Additionally, this should close insufficient documentation issue too https://github.com/ultrabug/py3status/issues/1245.
Changelog:
* I added documentation everywhere. Closes an issue (imo).
* In timer, I rename `mins` to `minutes` for cleaner example in `py3-cmd` docs.
* Unrelated. I rename `output` to `verbose` making it less vague.
* I understand why we didn't have aliases or button number in first place. If we work with `argparse`, it tends to sort stuffs and give us args to use. Some things are done after processing arguments. To keep it clean/simple, we would want to try having …

py3-cmd: allow sending events with more options 

---

py3status/modules/volume_status.py

Skip `pamixer` if `pulseaudio` is not installed. Addresses #1393.

volume_status: skip pamixer if no pulseaudio

---

py3status/modules/file_status.py

see https://github.com/ultrabug/py3status/pull/1369#issuecomment-402644653

file_status: patch to fix plural wording

---

py3status/modules/whatismyip.py

> **@lasers** Separate issue... We fetch requests when we toggle between self.format and self.icon. It should fetch only on self.cache_timeout or when users uses button_refresh.
This PR fetch requests only on `self.cache_timeout` or when users uses `button_refresh`.
Small note: At right timing, `self.toggled` could be left with wrong value, but it won't have effects because of `refresh` boolean. Just pointing this out. I prefer this over keeping making it `False`.

whatismyip: don't fetch requests between toggle states

---

py3status/modules/deadbeef.py

I like me some dead man's switches. :skull:
EDIT: I think I tried this before with `cmus` or `moc`. Question: Is better for the users (and modules, I guess) to have all available buttons exposed versus the selective buttons?
Like others, I don't include `button_random`, `button_stop`, and more.
```
--play           Start playback
(pending) --stop           Stop playback
--pause          Pause playback
--toggle-pause   Toggle pause
(added)   --play-pause     Start playback if stopped, toggle pause otherwise
(added)   --next           Next song in playlist
(added)   --prev           Previous song in playlist
--random         Random song in playlist
```
Should I not add `button_stop` here too? `cmus` have `button_stop` w/ sensible behavior..
Options in a nutshell:
1) Expose all buttons. …

deadbeef: add button examples

---

py3status/modules/deadbeef.py

I consider this somewhat a critical bug. Let users use their music on `deadbeef` for many months ahead without a quirky issue regarding the `if` condition in the code. Almost two years ago since the 7.2 release too.

deadbeef: deprecate 7.0, 7.1 support

---

py3status/modules/deadbeef.py

This fixes https://github.com/ultrabug/py3status/issues/1293. Users should be able to use `DeaDBeeF` without issues now.

deadbeef: use py3.command_output helper 

---

py3status/py3.py

Hi, I made a new helper to assist with thresholds. This is optimized and could be partially tokenized too. 
Adding this in `post_config_hook` will simplify things by ensuring that all variables in the data can be colorized (via loops) and that no cpu cycles would be wasted on unnecessary thresholds.
I'm merging this now so I can fix the other pull requests and/or modules.
I chose `get_color_names_list` over `get_colors_list` because I made this to fetch placeholder names. We can modify this to get css color names, color rgb or special color names too, but I don't see what for... so I go with the name `get_color_names_list`. Thank you.

py3: add new helper: get_color_names_list

---

.gitignore

When we `py.test --flake8`, we get this cache directory. Make it go away.

gitignore: ignore .pytest_cache

---

py3status/modules/loadavg.py

Hi. I made a new module `loadavg`. This module display load average figures giving number of jobs in the run queue (state R) or waiting for disk I/O (state D) averaged over 1, 5, and 15 minutes.
Making this pull request allows contributers/collaborators/owners to understand better about one of the decisions I wanted to make with `sysdata`... ie splitting them up into specialized modules.
Note: You can use `stress` to see thresholds changing colors between 0, 20, 40, 60, and 80.
Really old screenshots.
New screenshots.

add new module: loadavg

---

py3status/parse_config.py

When we have a config error with multiple config files, it does not tell us which file caused it.

parse_config: print file name too in config error messages

---

.git-hooks/pre-push

Helpful `pre-push` hook for everybody... to run flake8 tests first before pushing.
Note: Please wait until we `black` py3status first before adding the hooks. Otherwise, errors.

git-hooks: run flake8 tests first before pushing

---

py3status/py3.py

py3: fix drunken typos

---

py3status/modules/sysdata.py

Not long ago, I renamed `cpu_usage` to `cpu_used_percent`.
With all used percent placeholders ending with `used_percent`, we can make `max_used_percent = 0` to simplify thresholds by looking for `used_percent` keys. This mean `swap_used_percent` will be a part of `max_cpu_mem` threshold too.
Next, we should rename `max_cpu_mem` to either `max_used_percent` or `maximum_used_percent`. I was wondering if you prefer `mem_used_percent` or `memory_used_percent`. 
`nvidia_smi` uses `memory.used_percent`.

sysdata: make max_used_percent to simplify thresholds

---

py3status/formatter.py
tests/test_formatter.py

This is for `pomodoro`. Other modules can take advantage of this.
We use `{remaining_minutes:ceil}` to print `1` instead of `0.5324243` in pomodoro.
If `{remaining_seconds}` is in the format too, then we shouldn't use `:ceil` on the minute.
This is not a big concern because most users would be using new placeholder `{remaining}` or `{progress}` as both basically print nice `[\?not_zero {hours}:]{minutes}:{seconds}`.
This is here to support pomodoro's old placeholder `{mm}`... total minutes.

formatter: add {:ceil} to return x or x+1

---

py3status/formatter.py

A prelude bugfix to https://github.com/ultrabug/py3status/pull/1395's "invalid format" error.

formatter: don't strip whitespace

---

py3status/formatter.py
tests/test_formatter.py

`'[Hi, my name is {name}]'` does not work when `name` is a string `'None'`. This PR fixes it.

formatter: hide block on 'None' string too

---

py3status/formatter.py

The difference between showing values and faking nonexistent keys....
`{real}` (before) vs `None` (after).
We enter wrong formats, we get fake nonexistent keys instead of values.
This changes so we see more values even if we made mistakes somewhere.
Different scenario: Sometimes we can't avoid mistakes, but do want values anyway.
```diff
diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index dbcec8c6..3bba265e 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -16,12 +16,17 @@ class Py3status:
"""
"""
-    format = 'Hello, world!'
+    format = '{round:.2f} // {real:.2f} // {nonexistent}'
def static_string(self):
+        data = {
+            'round': 123.456,
+            'real': None,
+        }
+
return { …
```

formatter: show values instead of faking nonexistent keys

---

py3status/modules/lm_sensors.py

>@tobes First we should get lm_sensors merged
Agreed. I expose this. You review this.
-----
Hi. I made a new module `lm_sensors`. This module display sensors information from hardware sensors. The placeholders are parsed from the hardware via `sensors -u` leaving no stone unturned.
Making this pull request now allows contributers/collaborators/owners to understand better about one of the decisions I wanted to make with `sysdata`.
To copy `sysdata`'s `cpu_temp` behavior in `lm_sensors`, simply specify only the sensor for first core to use, eg `sensors = ['core_0']` instead of all sensors.
This requires some wanted features for thresholds too #1281. Thank you.

add new module: lm_sensors

---

py3status/modules/nvidia_smi.py

We revives an accidentally closed pull request. https://github.com/ultrabug/py3status/pull/903
* Support 140~ external placeholders. Some duplicates. eg, `gpu_name` and `name`, but unofficially, I can use 10~ placeholders. It can vary from GPU to GPU. See if we should make a script that'll output a list of properties and values, weeding out the others, eg `Not Supported`.
* I like `{memory.used}` here in the default format.
* Backward compatible not included for `nvidia_temp` as of this time. New module?
* Support color thresholds for placeholders in the `format_gpu`. _**New!**_
```
thresholds = {
'memory.used': [(0, 'good'), (1, 'degraded'), (2, 'bad')],
'temperature.gpu': [(0, 'bad'), (1, 'degraded'), (2, 'good')],
}
```
* I clean up things.
* I fix mistakes too. `format_gpu` makes more …

add new module: nvidia_smi

---

py3status/modules/nvidia_smi.py

I need to try `screenshots.py` in the future to see screenshots here first instead of looking at readthedocs. This should finalize the work on `nvidai_smi` module for some time now.

nvidia_smi: remove a trailing whitespace

---

py3status/modules/spaceapi.py

Scrolling causes requests. We add this to quietly prevent button refreshes.

spaceapi: prevent button refresh

---

py3status/modules/mail.py

Hi. I made a new module `mail`. This module ought to count number of mails.
If we want to, we can expand this to support `format_xxxx` loop too... where we can show index, partial subject, partial body message, or even senders in the bar. I know this for sure with non-`imap` mailboxes since I toyed with them right before I added `imap`... eg
> `1 Spotify, Hi from Susie, 2 Dad want to kno, 3 Dentist Appoint` (subject)
> `1 Github, 2 Google, 3 Mom, 4 Steam, 5 Github, 6 Marcus` (sender)
> `1 Hi, What are, 2 Do you want to, 3 I saw you today!` (body message)
I only tested this with `mbox`, but this should work okay with other mailboxes too.
P.S. Merry Christmas. This is my gift to you. 🎁  :-)
~~Closes~~ Targeting https://github.com/ultrabug/py3status/issues/143.
~~Closes~~ Targeting …

add new module: mail

---

py3status/formatter.py
tests/test_formatter.py

Hi. I'm not familiar with the formatter code. This closes #1095 for me.
This is likely the reason why adding something at end makes it just work.
```python
elif (self.parent is None and
((not self.next_block and enough)or self.base_block)):
valid = True
```
Without an `if` in there, the formatter think it is a `[{placeholder}]`.

formatter: return falsey properly

---

py3status/module.py

Addresses https://github.com/ultrabug/py3status/issues/815.

module: align modules with py3status instead of i3bar

---

py3status/modules/wanda_the_fish.py

Hi. I made a new module `wanda_the_fish`. This module display a fortune-telling, swimming fish.
There was a nice little GNOME2 panel applet where it displays an animated character (a fish) which pops up quotes generated by `fortune`. Simply put, there are people out there who adores `wanda_the_fish` too much. People also made this possible for other DEs too, but we still don't have one for `i3wm`. :frowning_face: 
Now with this module, we can start appreciating `wanda_the_fish` and her fortunes again. :tropical_fish:  :blush: :heart_eyes: :heart_eyes:

add new module: wanda_the_fish 

---

py3status/modules/external_script.py
py3status/py3.py

Often scripts put some diagnostic information on stderr, so having some text on stderr doesn't necessarily mean the command has failed. In fact, this is true in most cases — exit code is an indicator of whether command failed or not.
This PR allows to ignore stderr and thus not failing the command. This PR also changes the default behavior of `external_script` because I believe it is more correct this way.
Not sure on the name of the property. Maybe reversing is better, like `fail_on_stderr`?

command_output: do not treat text on stderr as failure, rely on exit code

---

py3status/modules/timewarrior.py

Hi. I made a new module `timewarrior`. ⏲  Not to be confused with `taskwarrior`. See https://taskwarrior.org/docs/timewarrior/index.html for more information.
Formatter `[\?end&cache=60 |\?cache=1]` certainly would be nice to have here... mainly because I am providing `on_click` examples instead of adding `button_continue`, `button_start`, and/or `button_stop`... and users familiar with `timew` could keep using the terminal (static interval).
The defaults are a little wonky as it is simple and have no separators... and no colors too. I don't know what I should use... `degraded`? `good`? Or just `None` everything and let the users decide it themselves? Anyhow, some things are borrowed from `taskwarrior` as they both are similar and nice.
**EDIT**: Wonky default formats fixed. Use `None` + …

add new module: timewarrior

---

doc/configuration.rst
py3status/py3.py

Added a formater section in the Configuration manual as users should not have to search the py3-modul documentation to format their status bar. Also updated the save_format doc string to include the conditional syntax of the formater.

docs: update formater and configuration documentation

---

py3status/modules/sql.py
py3status/modules/timewarrior.py

`getattr(self, name) or ''` --> `getattr(self, name, '')`

sql, timewarrior: fix getattr(self, name) or ''

---

py3status/modules/clock.py

clock did it's own parsing which is bad so use formatter so we do it correctly

clock: use format parsing to find placeholder

---

py3status/modules/weather_owm.py

#1433 reported an issue when https://timezoneapi.io/ is blocked/unavailable.
Whilst looking at this I found that there is a lack of flexibility.  I often am interested in weather in several locations and it is nice to be able to choose one, We need this to solve the #1433 issue
we can now set either `location` or `city`
Added examples as well as some general re-factoring needed for this functionality.

weather_owm: work without timezoneapi but also if you set city or location

---

py3status/modules/gitlab.py

The first `post-merge qa fixes` PR had to be merged asap.
I found more minor issues in different places. I'll leave this PR open and keep adding new ones here until we're ready for a release. If you find some, comment here and I can add them too.
* `gitlab` -- Hide `{name}` placeholder too when we don't have Internet connection.
* `nvidia_smi` -- Degree `C` went missing in the `format`. I'm adding `C` again. 
~~* `sql`, `timew` -- Use `getattr(self, name, '')`... not  `getattr(self, name) or ''`.~~

gitlab: hide {name} placeholder when offline

---

py3status/modules/external_script.py

We cast the output automatically to work with `int`, `float`, `NoneType`, etc better.
EDIT: Addresses https://github.com/ultrabug/py3status/issues/1391.

external_script: cast numeric output automatically

---

py3status/modules/sql.py

I found another future bug of mine after discussing about color names in https://github.com/ultrabug/py3status/pull/1472. Sorry, not sorry.
Initial PR does not have lowercase. I suggested lowercase to enforce our QA.
>@lasers To make this more readable, we should use Python's naming style (for functions) which is lowercase with words separated by underscores.
Later I made commits to address `format_row` and to ensure everything works well. He tested it too to be working well too. Then things went stale in that PR as well as `py3status`. No more communications.
I got role. I looked at this again and saw that we shouldn't lowercase the keys because we don't know what the keys will look like... and the fact that this can use more than one SQL database now too. I supported case-sensitive …

sql: don't make placeholders case-sensitive

---

py3status/parse_config.py

So this fixes two issues but they are very related and the PR is only two lines
1) The comment is somehow corrupt.  With the old version if you paste it into your config you get some weird unicode char `'͉'` [Combining Left Angle Below](https://unicode-table.com/en/0349/) in python3 (not python2).  anyhow it is clearly not `Δ` [capital delta](https://unicode-table.com/en/0394/).  Anyway we fix this
2) update the regex
* use `r` style string to remove the duplication of backslashes.  
* change `\\N\{.+\}` to `\\N\{([^}\\]|\\.)+\}` although the pattern is more complicated it is more predictable. essentially we change from. `\N{ .. anything .. }` to `\N{ .. anything that is not a } unless it is escaped .. }`.  Even though I am unaware of any unicode name chars that use an escaped `}` it …

config parser: improve unicode support

---

py3status/autodoc.py

So I was looking at the docs and things are getting a mess with the config syntax highlighting.
Things have got more complicated and the highlighting was always fairly basic.
I think the `shell(..)` and `env(..)` where the final straw.
https://py3status.readthedocs.io/en/latest/configuration.html#environment-variables
Anyhow this gives us a ~~spring~~autumn clean and makes everything super shiny once again.  Anyhow it's all fairly ugly regex stuff and seeing as I'm the only one who works on this bit I'm not going to go into much detail.  But there are some new comments (mainly for me when I revisit this in a couple of years or so)
if you are testing make sure to `make clean html` or else you won't get a clean build
No screenshots to preserve the mystery

py3status lexer updates for docs

---

py3status/parse_config.py

So we do quote removal in two places in the config parser.  This changes things to just do it in one place
1) rename `make_name()` to the more readable `remove_quotes()`
2) `make_value()` now uses this code rather than having it's own version
3) improve the robustness of the code we check that the first and last character are both the same quote type.

config parser: unify quote removal

---

py3status/parse_config.py

This add exceptions to the config parser and removes `# noqa`
`# noqa` flake8 error suppression should be used extremely sparingly and never to just hide errors.  The whole point of flake8 is to help improve code quality so ignoring it's suggestions undermines the point of using it.
I am confident that `ValueError` is the only exception thrown in the casting as I do not believe we can ever have a situation where `TypeError` is raised.
For module import a variety of exceptions can occur and so catching any feels appropriate in this case.

config parser: add explicit exceptions

---

doc/configuration.rst
py3status/parse_config.py

So we have `env(...)` and `shell(...)` as config options and I want to add `base64(...)`
Currently this is a little messy so this cleans it up
* We now have a common regex for 'functions'.  Having one reduces errors and can be better tested etc.  The existing ones had subtle bugs.
* `py3_wrapper` is made available in the parser.  Now we can just notify the user and keep going when these functions hit a problem.  Before they would stop the parsing.
* `shell(...)` now can use `)` if it is escaped, now that we have a better regex :)
* type conversion is now through common code (so is consistent)
* oh and `shell(..)` is python2 compatible now.
* It is now easier to expand if we want like `base64(..)`
* the match is now part of the token (because we needed it here)

config parser: cleaner functions

---

py3status/parse_config.py

This decodes bytes. Allow `base64()` and friends to work on Python3 too.
Bug acknowledged in https://github.com/ultrabug/py3status/issues/1211. ~~EDIT: Testing other values too...~~

parse_config: decode bytes

---

README.rst

Hi there,
As of today, the AUR package have been adopted in `[community]` by [the Arch Linux Trusted User _Morten Linderud_](https://www.archlinux.org/people/trusted-users/#Foxboron) and is now an **officially maintained package** :tada: 
Consequently, [the AUR package has been removed](https://lists.archlinux.org/pipermail/aur-requests/2018-September/026688.html) and I'll only keep maintaining the [`py3status-git`](https://aur.archlinux.org/packages/py3status-git/) package which almost never needs anything done.
It was a pleasure maintaining the `py3status` package for so long!
This PR updates the installation instructions according to [this new package home](https://www.archlinux.org/packages/community/any/py3status/) :slightly_smiling_face:

Update Arch Linux installation instructions for official package

---

py3status/modules/timewarrior.py

Cosemitc bug. `1w12d 5:13:29` (before) vs `1w 12d 5:13:29` (after). Idk I had active time interval.
EDIT: It's 1 week 5 day something.... or 12 days, 5 hours something.
I don't believe we're meant to use `{days}`, `{weeks}`, `{months}`, `{years}` at same time in `format_duration`, but real users of `timew` probably wouldn't leave this running for more than few hours if they wanted to track their time so I'm suggesting to leave this format as-is.
Second thoughts... It's probably better if I take out `{weeks}`, `{months}`, `{years}`.  EDIT: Done.
EDIT: I defaults minutes and seconds with `:02d` too. Don't cause users pain. Thx.
EDIT: Maybe I should remove impractical placeholders `years`, `months`, `weeks`, `microseconds`?

timewarrior: fix cosemitc issues with format_duration

---

py3status/module.py

Splitting up one huge monster into little cute monsters.... :japanese_ogre: :ghost: :wolf:
I'm defaulting `left` instead of `center` to be more consistent with the i3bar protocol... in case some users switched over from `i3status` and it generally looks more nice in the long run too.
>**align** 
>_Align text on the center, right or left (default) of the block, when the minimum width of the latter, specified by the min_width key, is not reached._

module: default left align instead of center

---

py3status/formatter.py
tests/test_formatter.py

@ultrabug 
This reverts 2 commits. related to the formatter.
These change the behaviour of the formatter.  I feel we need to better understand what we want from the formatter rather than @lasers changing it because he has an issue with some module he is writing.
* maybe we should change some of the behaviours but it should be a concious choice.
* @lasers could easily make his modules work correctly I think if he thought about things a little more and used some tricks like the attr_getter functionality of the formatter.
The first commit I objected to and don't feel that accepting the PR was the correct decision because I don't think it was thought through, I agree that I have been somewhat absent in the recent past.
The last commit was just merged by the author which I think is not good. …

Revert formatter changes

---

py3status/modules/timewarrior.py

This changes `index` from `'2'` to `'time/2'` to address a limitation. https://github.com/ultrabug/py3status/issues/1516

timewarrior: pass action/id index

---

py3status/py3.py

Add `LANGUAGE="C"` to "English" environment so that commands like `hamster` will print output in English (esp. on systems where `LANGUAGE` is set to something different).
Useful link about locale-related environment variables:
[https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html#Locale-Environment-Variables](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html#Locale-Environment-Variables)

Some commands in some environments does require LANGUAGE=C to print output in english.

---

py3status/modules/timewarrior.py

This reverts commit fc7407f357872cb552a994fda2621cac3d2a5dc9.
timewarrior is a new module so the changes do not matter so much
this removes some button actions considered harmful
@lasers has repented (I like to think so) for merging his own PR especially during the freeze
this is a low risk PR even very late in the window.
I'm still happy for the module to be dropped but it is better if we have it that we have this version

Revert "Revert "timewarrior: pass action/id index""

---

py3status/modules/nvidia_smi.py

An alternative for #1477. Should I combine ~6~ 7 commits into 3 commits for better readability?
@tobes With this merged, you can have your period.
I initially do this because if I run into an issue, I can come up with an edge-case solution for this module only or I can try and make formatter work better overall. For instance, `{None:.2f}` can still happen in other modules with `data_dict.get('placeholder')`.

nvidia_smi: remove string 'None', use memory.used_percent

---

py3status/modules/lm_sensors.py

The command `sensors` got  `-j` for JSON output not long ago. However, they hadn't made a release for 3-4 years so we think not many users will be able to use `-j` or install `lm_sensors-git` easily so we're going to support native/raw `-u` output instead.
This means... More users can use `lm_sensors` and not having to fuck around with anything. Yay.

lm_sensors: revert, cache, optimize, cleanup

---

doc/writing_modules.rst
py3status/module_test.py

This allows us to produce an output similar to the i3bar output in terminal with `--term`.

module_test: print modules in terminal

---

py3status/module.py

Not sure if that's the right way to do this, but here's what I use for my setup.
In lots of my module config `format` string I use pango markup.
But it isn't interpreted (and instead display the ugly xml in my i3bar) unless I use the following patch.
Here's an example extracted from my setup that needs this to work and properly display the font awesome icons:
```
general {
color_good = "#3EC2FF"
color_bad = "#FF0000"
colors = true
output_format = "i3bar"
markup = "pango"
}
order += "volume_status"
volume_status {
format = "<span font='Font Awesome 5 Free Solid'></span> {percentage}%"
format_muted = "<span font='Font Awesome 5 Free Solid'></span>"
color_muted = "#FFFF00"
}
```

Allow module to use the general "markup" config

---

py3status/cli.py

I consider it a bug on our part

adds ~/.config/i3 as a default config directory, closes #1548

---

doc/configuration.rst
py3status/constants.py
py3status/core.py
py3status/module.py
py3status/modules/xrandr.py
py3status/py3.py
py3status/udev_monitor.py

Allows modules to use a generic interface to subscribe to udev events and be refreshed **ONLY** when they happen.
This allows some modules, such as featured xrandr, to not poll for change all the time :+1: 
Comments / review welcome. I've been using it for a while now.

implement udev event monitoring

---

py3status/parse_config.py

We check for invalid ~~(empty)~~ modules so py3status does not die with a vague message.
```python
order += ""  # IndexError: list index out of range
order += None  # AttributeError: 'NoneType' object has no attribute 'split'
```
Vague message is:
```
Error: status_command process exited unexpectedly (exit 2)
```
Addresses https://github.com/ultrabug/py3status/issues/1523.

parse_config: raise error on invalid modules

---

fastentrypoints.py
py3status/docstrings.py
py3status/formatter.py
py3status/parse_config.py
py3status/py3.py
tests/test_formatter.py
tests/test_module_doc.py
tox.ini

We have a new round of flake8 errors.
Mostly this is due to W605 bad escape chars which are fixed in core
Modules need updating but are ignored for W605.  W504 (operator should be at end of line not beginning) and E999 for 3.6
We also hide some warnings
Flake8 code warning in python2
Module import issue for 3.7
The modules we can look at fixing up in the next cycle or two and then remove the ignore.

fix flake8 W605 errors in core and disable test for modules

---

py3status/py3.py

This clears up minor confusion about the origin of the notifications.
* Notifications coming from py3status will have `py3status` title.
* Notifications coming from modules will have `py3status: module_name` title.
* Before `py3status` vs After `py3status: pomodoro`.
I thought about removing `py3status` prefix, but that seems like a bad idea because of module names such as `google_calendar`, `i3pystatus`, `i3block`, `github`, `gitlab`, etc.
Soon or later, modules like `usbguard`, `pomodoro`, etc can be updated with different titles such as capitalizing `Pomodoro` rather than (current) `py3status` or (this pr) `py3status: pomodoro`.

py3: notify_user module name in the title

---

doc/configuration.rst
py3status/constants.py
py3status/module.py

This addresses https://github.com/ultrabug/py3status/issues/1540. From what I understand...
* Renaming `min_width` to our custom `min_length`.
* Permit users to still use `min_width` (pixel)
* We can't use our custom `align` with i3bar's `min_width` so we made our own with chars.
* We'll rename our custom `align` to `position` too to keep everything away.
* Renaming `align` to our custom `position`.
* i3bar can't align multi-color modules.
* All i3status modules are always fully colorized.
* Permit users to still use `align`... This would only work with single color.
* We could make universal `allow_colors = False` in the future.
* We could allow users to override all `color` with a static color (then simplify) in the future.
* Multi-color mean breaking out into more composites.
* …

module: rename min_width,align to min_length,position

---

py3status/module_test.py

Before.
```
$ python3 xrandr.py
Module `test_module` could not be loaded
'MockPy3statusWrapper' object has no attribute 'udev_monitor'
```
After.
```
$ python3 xrandr.py
{'full_text': 'DP-2+DP-3', 'color': '#00FF00', 'cached_until': 1540554427.0}
{'full_text': 'DP-2+DP-3', 'color': '#00FF00', 'cached_until': 1540554428.0}
^C
```
```
$ python3 xrandr.py --term
DP-2+DP-3
DP-2+DP-3
^C
```

allow test_modules to use udev_monitor

---

py3status/modules/battery_level.py

cc @ultrabug for another great example of using new udev feature.
With this change, `battery_level` module will refresh instantly as soon as you plug or unplug charging cable. Because of this, there's no need to refresh the module as often as every 30 seconds, I set it to 60 seconds for now.
Guess what, until today I had `cache_timeout` set to `1` because I wanted to instantly know when I plug in my charger. NO MORE.

battery_level: refresh with udev, increase default cache_timeout

---

doc/README.md
doc/writing_modules.rst
py3status/modules/wifi.py
py3status/py3.py

Fixing a typo. This addresses #1576.
EDIT: You can blame this person. a06882dac8602ea17fa2ea0e5f0518491ddc99ba

fix typo cache_until with cached_until

---

py3status/screenshots.py

1) Based on number of modules, we are literally missing 101 screenshots.
2) We're missing several single screenshots in `static_string`, `sql`, `diskdata`, etc.
3) We're missing several last screenshots in `coin_market`, `check_tcp`, `dpms`, etc.
0654970bbaf18b10810cbb35724c8992093e655d, #1535 is the first bad commit
```bash
0654970bbaf18b10810cbb35724c8992093e655d is the first bad commit
commit 0654970bbaf18b10810cbb35724c8992093e655d
Author: tobes
Date:   Wed Oct 10 21:09:08 2018 +0100
clean and improve screenshots generation (#1535), by @tobes
```
* I fix, clean and improve screenshot generation too.
* I file diff. I change `name.png` to `name-0.png`.

screenshots: fix parsing missing last screenshots

---

py3status/modules/i3pystatus.py

Because I looked at `screenshots.py`, I saw that `i3pystatus` does not have a screenshot.
I'm adding one. I'm also fixing docstrings. We also could remove a checking  in `screenshots.py` to ensure that all modules **must** have a `SAMPLE_OUTPUT` string in the docstring to enforce better QA instead of silently skipping (one module).

i3pystatus: add sample output, fix docstrings

---

py3status/modules/external_script.py

In light of new Zen #1582, I'm submitting a simple implementation for the pattern I use with `external_script`. In my mind is good enough until we come up with some sophisticated support for notifications in core. This replaces #1439.
-----
Before:
* external_script shows only first line of output, no way to see entire output
* refreshes on any button click
After:
* external_script still shows first line of output, but on click you get a notification with full output
* refreshes only on `button_refresh`, i.e. left click shows notification and doesn't trigger refresh
* also added `line` format placeholder to show the total number of lines in the output (could rename if you want, `line` was proposed in #1439).
Why:
I use `external_script` with the same pattern for different purposes. Don't …

external_script: notifications

---

py3status/modules/dropboxd_status.py

Recent versions of `dropbox-cli` may include a Unicode circle in the output, e.g.
```
Syncing "foo" • 28 mins
Downloading "foo" (5,382 KB/sec, 28 mins)
```
which breaks the `dropboxd_status` module since the wrong encoding is passed to `Popen`.
Defaulting to the system encoding should resolve this.

Add support unicode character output from dropbox-cli

---

py3status/modules/keyboard_layout.py

Quick untested code to address #1360.
Undocumented because it's not ideal to use both `{layout}` and `{variant}` at same time.
I didn't split them up because users can add variants in `layouts` list too. This explicitly should do what @cyrinux wanted... to print `{variant}` name alone https://github.com/ultrabug/py3status/pull/1335#issuecomment-393609437.
If you want to go ahead and document `{variant}` too, I will.

keyboard_layout: add variant

---

py3status/modules/gitlab.py

This switches from partial future helper code to `py3.get_color_names_list` helper.

gitlab: use py3.get_color_names_list helper

---

py3status/screenshots.py

Attempting to fix the `readthedocs`. :hurtrealbad:

screenshots: don't use f-strings

---

py3status/screenshots.py

Removing `f-strings` generates the docs, but no screenshots. I looked at `autodoc.py` and it seems to be parsing everything okay. `make html` also generates everything okay here. I'm not sure what else it could be... Two possibilities.
1) Removing `-0` is absolutely important. 
2) Somebody does not like `os.path.realpath()`.
I'm trying `#2`. :pray:

screenshots: use abspath instead of realpath

---

py3status/modules/vpn_status.py

Hi, 
The `vpn_status` module currently only displays one VPN name, even if multiple connections are active.
This PR makes it display the full list of connected VPNs:

vpn_status: handle multiple simultaneous vpn connections

---

py3status/formatter.py

*This might be moot if we are switching to f-string formatter in the near future.*
Occasionally, we can run into unwanted side effect of having several `[\?soft  ]` in the `format`.
```python
format = "a[\?soft  ][{b}][\?soft  ][{c}][\?soft  ][{d}] World"
```
If `c` does not exist or the block is invalid, we print all `[\?soft ]`. With this PR, we skip one or more:
```python
```
If `[\?soft -]` is not same as the next `[\?soft :]`, then both soft blocks would be printed.

formatter: avoid duplicate soft blocks

---

py3status/command.py

The first commit is for `--modifier Control --modifier Shift --modifier Mod1`
The second commits is for `--modifiers Control+Shift+Mod1`. 
If you like the first commit, I can remove the second commit.
If you like the second commit, I can squash commits or you squash and delete the body.
I like the second commit better. Short and simple.

py3-cmd: allow sending click events with modifiers

---

py3status/modules/emerge_status.py

Added a module that displays current emerge information.
Multiple format options are available (documented in the module file).
User needs to have read access to the log file in /var/log/emerge.log. This can be acomplished by the Gentoo 'portage' group.

Added emerge status module

---

py3status/modules/speedtest.py
py3status/modules/speedtest_cli.py

Hi family,
Here a new module for do speedtest.
It needs speedtest-cli to be working.
Some point:
* This module if not refreshed at py3status, but only next on click / py3-cmd refresh.
I think I will personally refresh it with a networkmanager dispatcher hook.
* I have first done a "hack" which is the `{quality}` placeholder. Done this because there is yet a bug for int/float comparaison with the formatter. Even when this will be fix i think we can keep it, but, what is a "good" or "bad" connection? Must I add params for report quality based or user preference?
* To be quick, i do upload or download only if placeholders are present. Need at least `{download}` or `{upload}`
Waiting for review :)
(I will have lot of travis fix to do first I think)

New module: speedtest

---

py3status/command.py

py3-cmd throws NamespaceErrors when trying to refresh a module this should fix it.

[py3-cmd] only check for modifiers at click events

---

py3status/modules/google_calendar.py

Don't do anything with empty event urls. Addresses https://github.com/ultrabug/py3status/issues/1599.

google_calendar: fix url indexerror exception

---

py3status/modules/transmission.py

transmission-remote prints help when not using arguments so we need to use --list as default

transmission: use --list when no aditional arguments are given

---

py3status/modules/backlight.py

Use case: user share the same configuration between laptops/desktops and don't want to have a "backlight: no unavailable devices" error when using backlight mode in desktop.

backlight: Added "hide_when_unavailable" option

---

py3status/module.py

This only works on `i3-gaps`. I add `background` and `border` colors as well as `border_{top, bottom, left, right}` widths. The border widths only work if you specified `border`.

module: add background and border colors

---

py3status/module.py

This should fix https://github.com/ultrabug/py3status/pull/1486#issuecomment-449669433.  
If you want to use `self.module_class` for `py3.get_color()`, you require a module to loaded successfully first. Doing `set_module_options(module)` at end of `init`... assuming a module wouldn't fail when it failed... would result in a failed `py3`... Let alone a failed `get_color()` too. 
There are ways we can fail modules. One can fail modules by switching branches between different modules... resulting in failed modules on the bar... or for our users, they can fail by entering wrong names... or are missing modules/paths.
Now, if you have `get_color()` options in the failed module configs too, you would find yourself breaking the bar entirely... This possibly could be the reason for …

modules: don't set module options on failed modules

---

py3status/modules/diskdata.py

This PR added `used_percent` threshold to `diskdata` module.
It allows to set threshold based on percent of used disk.
It also fixes the description of `used` threshold, that is calculated based on `used` and not `used_percent`, like it was before.

diskdata: Added used_percent threshold

---

py3status/modules/i3block.py

Cleaning up docstrings so it would look similar to any other modules. I did this before... in #1587.

i3block: fix docstrings

---

doc/conf.py
doc/configuration.rst
doc/intro.rst
doc/writing_modules.rst
py3status/modules/mail.py

It's not useful to paste output... especially without colors. I'm listing warnings only.
```
...
py3status/doc/configuration.rst:139: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 12 supplied.
py3status/doc/intro.rst:93: WARNING: Unexpected indentation.
py3status/doc/intro.rst:97: WARNING: Unexpected indentation.
modules-info.inc:3136: WARNING: Unexpected indentation.
py3status/doc/writing_modules.rst:810: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 20 supplied.
py3status/doc/writing_modules.rst:820: WARNING: Error in "code-block" directive:
maximum 1 argument(s) allowed, 18 supplied.
copying static files... WARNING: html_static_path entry 'py3status/doc/_static'
does not exist
build succeeded, 7 warnings.
```

autodoc: fix warnings

---

py3status/modules/velib_metropole.py

Give it a value instead of the dict. Fix `format` thresholds for those who want to colorize `station`.

velib_metropole: fix format thresholds

---

py3status/modules/file_status.py

This reduces getting thresholds from `2` times to `0 or more` times on every interval.

file_status: optimize thresholds

---

py3status/py3.py

When it comes to empty strings, we tends to use `(default None)` instead of `(default '')` everywhere. This would prevent an exception with some `format* = None` configs. The main `format` config is usually excluded because it is already defined 99% of the time.

py3: get_color_names_list to return an empty list on false value

---

py3status/py3.py

I saw this in `velib_metropole` when I was addressing `format` thresholds. 
A color got assigned on `L1993`... and it failed (TypeError), it would use that color instead of `None`. 
https://github.com/ultrabug/py3status/blob/69dedeb8400ade2e8bb1742c284cb067bf2f8211/py3status/py3.py#L1193-L1200

py3: threshold_get_color to set color=None on exception

---

py3status/module.py

Addressing yet another error / edge case with `get_color`. #1619. Cheers.

modules: don't set module options on disabled modules

---

py3status/modules/net_rate.py

This reduces getting thresholds from `3` times to `0 or more` times on every interval.

net_rate: optimize thresholds

---

doc/intro.rst

This commit updates the docs of how to install `py3status` in NixOS.
It is not that the old instructions are wrong, however what they did was installing `py3status` and its dependencies in the Python interpreter that is globally available to its users. This is how it works in most distros, however the idea of NixOS is to isolate each program and its dependencies.
These new instructions injects Python dependencies only in the `py3status` binary.
Also change the language of the snippets to `nix` (don't know if this works in https://readthedocs.io, needs to test).

doc: Update NixOS docs

---

py3status/modules/diskdata.py

Call `time()` and `_get_io_stats()` once instead of twice on every interval.
The data does not have time to change. The `time` did change slightly.
```
2019-01-13 18:15:11 INFO Module `diskdata2`: TIME: False
2019-01-13 18:15:11 INFO Module `diskdata2`: TIME: -0.0012888908386230469
2019-01-13 18:15:22 INFO Module `diskdata2`: TIME: False
2019-01-13 18:15:22 INFO Module `diskdata2`: TIME: -0.003037691116333008
2019-01-13 18:15:33 INFO Module `diskdata2`: TIME: False
2019-01-13 18:15:33 INFO Module `diskdata2`: TIME: -0.003916025161743164
2019-01-13 18:15:44 INFO Module `diskdata2`: TIME: False
2019-01-13 18:15:44 INFO Module `diskdata2`: TIME: -0.004103660583496094
```
This should be more accurate and should sometimes give us slightly more.
Unrelated. I rename from `ios` to to `diskstat` …

diskdata: call functions once instead of twice

---

py3status/modules/do_not_disturb.py

This fixes `state = None` for dunst because we can query state from others, but not dunst.
* xfce - via querying -- return 0/1
* lxqt - via pgrepping -- is it running or not 
* dunst - no way to query its state

do_not_disturb: fix dunst's state=None

---

.git-hooks/pre-push

This is required because of `fix black formatting CI tests (#1643)`.

git-hooks: add black tests to run first before pushing

---

py3status/cli.py
py3status/core.py
py3status/i3status.py

This adds `-u, --i3status` for @Dettorer and other users to specify custom `i3status` path. If we can't `which i3status`, then it usually mean `i3status is not installed` so we'll try `Popen([None, "-c", ...)` too which will give us same error as old `i3status`. Anything more is not necessary.
Addresses #1600.

i3status: add -u, --i3status to specify i3status path

---

py3status/modules/mpris.py

After looking what `subscription` looks like on other music players, I tried this for clementine... and it seems to be working quite well. I'm able to stop, pause, play, quit client, start client, etc.
Addresses https://github.com/ultrabug/py3status/issues/911.

mpris: fix clementine attributeerror exception

---

py3status/modules/do_not_disturb.py

This commit removes usage of `killall` in do_not_disturb module to fix this module under NixOS. In NixOS `killall dunst` returns a `dunst: process not found` (this happens with other packages too, thanks to the usage of binary wrappers in NixOS).
Instead, use `pkill` instead of `killall`, much more reliable and works everywhere (`killall` is part of `psmisc`, not installed by default in some systems, while `pkill` is part of `procps`, almost essential in every Unix system).

do_not_disturb: Avoid usage of killall

---

doc/configuration.rst
py3status/modules/air_quality.py
py3status/modules/bitcoin_price.py
py3status/modules/coin_market.py
py3status/modules/getjson.py
py3status/modules/github.py
py3status/modules/gitlab.py
py3status/modules/pingdom.py
py3status/modules/velib_metropole.py
py3status/modules/weather_owm.py
py3status/modules/whatismyip.py
py3status/py3.py

I believe we shouldn't bother users with this particular config. By defaulting `timeout=10` in `py3.py`, we can simplify several things. The modules with exposed config are left alone but will be hidden this time to allow some transition time.
I made one adjustment to `exchange_rate`, from 20 to 10, since this module is broken for long time so I think maybe it is okay to do that (i.e. to use the default value instead)... I also wonder if we want to default `pingdom` with the default value too, but `pingdom`'s request need to be fixed too. Not me.
Addresses #1519 (request_timeout,  self.py3.request)
P.S. In case you didn't notice, I'm really trying to kill many issues as I can here. 
EDIT: I changed ~~`pingdom` and `getjson`'s~~ ~~nearly~~ all `request_timeout` to 10.

simplify module options by hiding request_timeout configs

---

py3status/py3.py
py3status/util.py

Simple correction of a typo occurring a few times in the code ("gradiant" -> "gradient").

Fixed typo in naming ('gradiant' -> 'gradient')

---

py3status/modules/net_rate.py

When i'm offline, after resuming my laptop, I can get lot of garbage from net_rate.
A quick working fix is done by handle KeyError too. 
ps: Error was on line 163.

net_rate: prevent log flooding on weird network interface state

---

py3status/cli.py

Regardless of its state, don't use `do_not_disturb` module when you're testing things. It was hiding this an error message from me... I ran into this error message for first time after removing `do_not_disturb` from my config. This is why I like `state = None`. ;-)

i3status: use None or i3status

---

doc/configuration.rst
py3status/module.py

RFC. This adds custom urgent backgrounds. Requires `i3-gaps`.
* `timer` looks nice with `urgent_background = 'crimson'`. 
```python
order += "timer"
timer {
time = 5
urgent_background = 'crimson'
}
```
* `github` looks nice with `urgent_background = 'black'`.
* `mail` looks nice with `urgent_background = 'deepskyblue'`. 
You get the idea.

module: add urgent background and borders

---

py3status/modules/tor_rate.py

Hi guys,
I hide "Error: Failed to establish control connection!" with hide_if_not_running param for user which assume tor is not running sometimes. 
ping @maximbaz

tor_rate: hide socket error if we assume tor is not always running

---

py3status/modules/imap.py

Flake8 tests failed. Resolves `use ==/!= to compare str, bytes, and int literals [F999]`

imap: fix flake8 F999 errors

---

py3status/modules/arch_updates.py

.. since cower was deprecated by author and replaced with auracle.
This commit also prioritizes auracle over cower if both are installed.

arch_updates: add auracle support

---

py3status/modules/netdata.py

This reduces getting thresholds from `2` times to `0 or more` times on every interval.
This exposes `4` more color thresholds for users to use. (Niche).
Side note: I could put nearly everything inside the dict to remove few more lines. Should I?

netdata: optimize thresholds

---

py3status/modules/hddtemp.py

This reduces getting thresholds from `1` time to `N+0` times on every interval. `N` might as well be `1`.
* More threshold options (from 1 to 4) to use such as `name`, `path`, and others. (Niche)

hddtemp: optimize thresholds

---

py3status/modules/air_quality.py

This reduces getting thresholds from `1` time to `N+0` times on every interval. `N` might as well be `1`.
* Config `thresholds` exposed to allow user-defined `thresholds` for other placeholders.
* More threshold options (from 1 to 20+) to use such as `iaqi` placeholders, `idx`, and others. (Niche)
* New placeholders added in future should have working thresholds out of the box too. (Yay)
* By default, we uses `{'aqi': True}`. If this is `True`, we uses information from `quality_thresholds` consisting of tuples `(aqi_index, aqi_color, aqi_category)`.
* Users should be able to use thresholds same as others if they want it. List, dict, etc.

air_quality: expose and optimize thresholds

---

py3status/modules/usbguard.py

Addressing `usbguard` module as per discussions in #1566 and #1656, this reduces the functionality to what @cyrinux and I actually use in this module. Let's extend this module on specific user requests.
This also fixes #1656, module is finally refreshing instantly and yet we are able to return to `"cached_until": self.py3.CACHE_FOREVER`.
The diff is a bit simpler if you disable whitespace changes (`?w=1`).

usbguard: simpler implementation

---

py3status/cli.py
py3status/core.py
py3status/docstrings.py

Simplify `include_paths` early to valid paths so we don't have to fix or check anything later.

simplify include_paths early to valid paths

---

py3status/modules/sysdata.py

1) This ~~reduces~~ halves parsing lines in `/proc/cpuinfo` on every interval by stopping on 24th line.
* `cat /proc/meminfo | wc -l` --> `49`
* `cat /proc/meminfo | head -n24` --> `24`
2) Move methods so we don't have to check `if mem` and `if swap` twice on every interval.
3) Kill lines. The code is organized too... in line with other methods.

sysdata: optimize meminfo

---

py3status/__init__.py
py3status/argparsers.py

Personal opinion to use `argparsers`. It's not always clear which file to open... `cli` or `command`.

rename cli.py to argparsers.py

---

py3status/modules/twitch.py

This cleans up some Twitch code.
* Remove dead config `format_invalid`. Not triggerable. 
* Use exception in `post_config_hook` instead.
* `An unknown error has occurred.` can never happen because of `None` / `not None`.
* Larry the cow need to stop mooing madly in my terminal.
* EDIT: Change `cache_timeout` from `10` to `60`.

twitch: clean up some code

---

py3status/modules/twitch.py

This adds `py3.request` helper. We can use `request_timeout` too if we want to. :crossed_fingers: :pray: :prayer_beads: 
* Rename `stream_name` placeholder to upstream `display_name`.
* Both URL uses `py3.request` now. 
* Errors such as `Bad Request 404` will be used instead of broken `format_invalid` config.
* Things looks okay on my side.
* Colors and formats are left alone. Guess we will wait for the new formatter or something.
Plz merge #1698 first.

twitch: use self.py3.request helper 

---

py3status/argparsers.py

This adds a slash to all existing paths. Fixes the regression I saw from merging https://github.com/ultrabug/py3status/pull/1695. It does not feel ideal to enforce trailing slash, but it'll have to do.

argparsers: add slash

---

py3status/modules/screenshot.py

Dunno if we have users using this module. Anyway...
* Deprecate `push` in favor of other existing configs.
* Use `py3.command_run` helpers.
* Deprecate `cache_timeout` in favor of `CACHE_FOREVER`.
* Add `format`. Expose `{basename}` placeholder.
* Minor code cleanup. Everything should still be same. Thx.

screenshot: catch up with the standards

---

doc/configuration.rst
py3status/formatter.py
py3status/modules/sysdata.py
py3status/py3.py

>But if you want @ultrabug's opinion, can you please submit a PR and blackstar it?
If the color is `invisible`, it is used to invalidate the block. This addresses #934.
And a slew of imaginable conflicts.
* I imagine there are conflicts between old formatter and new formatter 4.0 rfc.
* I imagine there are conflicts between old formatter blocks versus new formatter thresholds colors.
* I imagine there are conflicts between collaborators.

formatter, py3: use color invisible to hide blocks

---

py3status/module.py

I find more issues with my pango PR to convert composites to `pango` markup.
* Support Python2 too by adding `u''` for unicode. 
* ~~Apply `i3bar_module_options` (again).~~ Doing it early instead.  
EDIT: ~~I'm not even sure if this is correct. Trying something different.~~ Fixed. Doing it early works better

module: add pango markup conversion (py2+module_options)

---

py3status/modules/arch_updates.py

First commit moves main method down.
Second commit renames things (i.e. fluffy changes).
Third commit moves lot of things around to detect `pacman`, `aur`, `format`, better.
As a result of this...
* Users can use `aur` alone without `pacman`. 
* If users specified `pacman`, `aur`, `total` placeholders in `format` and the binaries are not installed, it'll throw error. I imagine users are happy with auto format anyway.
* Same as before... If the `format` is not specified, it'll determine the `format` based on installed binaries... just more balanced/accurate.
* It's more balanced/accurate in a sense that we can add more than one `pacman` command other than `checkupdates` (if we can find out what it is)... essentially treating this same as `aur` code.
I thought about adding `thresholds` …

arch_updates: remove include_aur in favor of auto, refactoring

---

README.rst
doc/intro.rst
py3status/argparsers.py
py3status/core.py
py3status/events.py
py3status/module_test.py
py3status/modules/google_calendar.py
py3status/modules/scratchpad_counter.py
py3status/modules/window_title.py
py3status/modules/xrandr.py
py3status/py3.py

This should solve compatibility problems with sway #1717. Tested on i3. Untested on sway.
I hide the `--wm` argument too. `py3status --wm [i3|sway]`. This dictates no more than `msg` and `nag` and if necessary, this can be extended more to support other things like `lock`.
* Allowing users to specify `--msg`, `--nag`, `--lock` could be more flexible over `--wm` especially when it comes to `timeout`, `font`, or `lock`-related arguments.
* Speaking of `lock`-related arguments, hardcoding `i3lock` wouldn't bode well.
* Allowing users to specify settings inside py3status/module configuration section for `msg`, `nag`, `lock`, `debug`, `log`, etc could certainty be more flexible and/or overkill, e.g. selective logging, different log path for modules, enable debug only on one or more modules, …

add i3/sway directive

---

py3status/modules/arch_updates.py

I turned on `hide_if_zero = True` to hide `UPD: 0/0` and ran into `SPEC VIOLATION: full_text is NULL!` because I supplied `None` for everything in my `arch_updates` refactoring.
There is a discrepancy between real modules and test modules when supplying `None` or `[]`.

arch_updates: fix SPEC VIOLATION: full_text is NULL!

---

py3status/modules/mpris.py

This removes hardcoded button pixels  in favor of configurable space padding in `format`. Buttons will be either smaller or larger... If users want, they can remove spaces in their `format` to make it more smaller or larger.
EDIT: Worth mentioning that the click hitbox can be smaller or larger. Maybe not an issue.
Addresses #1737.

mpris: remove min_width pixels in favor of spaces

---

tox.ini

`flake8 3.7` failed all Python tests so we pinned `flake8 3.6.0`. It got fixed not long after. Can unpin.

tox.ini: unpin flake8 3.6.0

---

py3status/events.py

Not exactly a bugfix. `if module_info` is always True, otherwise, we would see this exception already because `full_text` and `partial_text` is not defined anywhere other than inside `if module_info`. 
```bash
UnboundLocalError: local variable 'full_text' referenced before assignment
File "py3status/py3status/core.py", line 58, in run
self.module.run()
File "py3status/py3status/events.py", line 83, in run
self.module_name, self.event, self.command
File "py3status/py3status/events.py", line 149, in on_click_dispatcher
full_text, partial_text = self.get_module_text(module_name, event)
File "py3status/py3status/events.py", line 131, in get_module_text
return full_text, partial_text
```

events: remove unused if statement for \$OUTPUT{,_PART}

---

py3status/module.py

Consistent behavior for `[]` and `None` in testing modules. Most modules uses composites anyway.
Addresses https://github.com/ultrabug/py3status/pull/1735#issue-258578484.
> ... ran into `SPEC VIOLATION: full_text is NULL!` because I supplied `None` for everything...
> 
> ... discrepancy between real modules and test modules...

module: fix indexerror exception

---

doc/py3status.html

update i3wm.github.io py3status page with newer links and doc fix #1010

---

doc/configuration.rst
doc/contributing.rst
doc/intro.rst
doc/py3-cmd.rst

https://py3status.readthedocs.io/en/latest/configuration.html?highlight=on_click#configuring-a-py3status-module need unordered list badly. I fix other things too.

docs: make unordered list, update docs, fix typos

---

py3status/events.py
py3status/parse_config.py

I can't reproduce the exception. I believe this would avoid the same exception in the future.
Addresses #1705.

parse_config: raise errors on sections in containers in the order directive

---

py3status/modules/frame.py

This avoids hardcoding `frame` in `module.py` which is 9a339ff. 
If you want `markup = 'pango'` in `general {}`, then all modules including `frame` will get a pango markup. Sure, `frame` acts funny, but I believe it to be correct (a single pango markup composite).
With new option `None`, you can cancel this out by adding `markup = None` to `frame` module... which will behave same as hardcoded `frame` in `module.py`. Option `'none'` is raw from i3bar.
`format_separator` is fixed too in this PR.. to support `format_separator = '\?color=violet \|'` instead of spaces or non-colorized symbols/characters. Using (fixed) `format_separator` will work fine for pango markup too. Users could use this to mimic real separators or make different ones.
I do not see a way to keep both real separators and …

frame: add safeformat for the separator

---

py3status/modules/group.py

A recent PR stops cycling on `urgent`, but omitted `cycle` so group will always cycle modules.
```diff
-            if self.cycle and time() >= self._cycle_time:
+        # keep cycling if no urgent
+        if not urgent:
+            self.cycle = self.cycle_timeout
+            if time() >= self.cycle_time:
self._change_active(1)
-                self._cycle_time = time() + self.cycle
```
This adds a missing check for `cycle = 0` to ensure we don't cycle against users' wishes. Sorry I always mess up something. You should come out of your rock and yell at me some more. :-)
Addresses #1756.

group: don't cycle on zero

---

py3status/modules/mpris.py

This handles disconnected players gracefully on clicks.
```
2019-03-29 14:32:10 WARNING on_click event in `mpris` failed (Error) mpris.py line 579.
2019-03-29 14:32:10 INFO Traceback
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.NoReply:
Message recipient disconnected from message bus without replying (4)
File "py3status/py3status/module.py", line 884, in click_event
click_method(event)
File "py3status/py3status/modules/mpris.py", line 579, in on_click
getattr(self._player, self._control_states[index]["action"])()
File "/usr/lib/python3.7/site-packages/pydbus/proxy_method.py", line 75, in __call__
0, timeout_to_glib(timeout), None).unpack()
2019-03-29 14:32:10 ERROR py3status: on_click event in `mpris` failed (Error)
mpris.py line 579. Please try to fix this and reload …
```

mpris: handle disconnected players gracefully on clicks

---

py3status/modules/i3pystatus.py

1) ENHANCEMENT. This should support (all?) universal/py3status module options:
1a) BUGFIX: Universal/py3status module options does not work on i3pystatus. 
```python
SKIP_OPTS = [
"align",
"allow_urgent",
"background",
"border",
"border_bottom",
"border_left",
"border_right",
"border_top",
"markup",
"min_length",
"min_width",
"position",
"separator",
"separator_block_width",
"urgent_border",
"urgent_border_bottom",
"urgent_border_left",
"urgent_border_right",
"urgent_border_top",
]
```
2) BUGFIX. Fixes an `interval` bug where author last-minute removed `safeformat()` in the code before it gets merged... resulting in occuring unequal contents... triggering modules to nearly always check the content every second instead of `interval`/15/30. 
~~3) BUGFIX. Check Python version first before we …

I3pystatus: support universal/py3status module options

---

py3status/modules/diskdata.py

Plain `df` returning values in `kb` is just the default/convention.  In some environments the default units returned by `df` may be something else, eg. where one of `DF_BLOCK_SIZE`, `BLOCK_SIZE`, `BLOCKSIZE`, or `POSIXLY_CORRECT` environment variables have been set, or where `df` is a wrapper script that adjusts the default behaviour of `df` to the user's liking.
Thus the `diskdata` module's assumption (that the values it reads are always in `kb`) is not always true.  This patch adjusts the module so that it passes `-k` to `df`, to ensure that the values are always in `kb`.

diskdata: explicitly request kb from df

---

py3status/modules/pomodoro.py
py3status/py3.py

This simplifies the code by using py3.play_sound helper + `ffplay` to play various audio formats.
Addresses #1769.

pomodoro: use py3.play_sound helper

---

py3status/core.py

Whilst troubleshooting an issue, I noticed we log starting and exiting i3status, but not i3status modules. 
Before.
```
2019-04-08 00:12:37 INFO i3status spawned using config file /tmp/py3status_vglx24_e
```
After.
```
2019-04-08 00:12:37 INFO adding module cpu_usage
2019-04-08 00:12:37 INFO adding module disk /
2019-04-08 00:12:37 INFO adding module ethernet _first_
2019-04-08 00:12:37 INFO adding module tztime local
2019-04-08 00:12:37 INFO i3status spawned using config file /tmp/py3status_vglx24_e
```

core: document adding i3status modules in the log

---

py3status/constants.py
py3status/formatter.py
py3status/py3.py
tests/test_formatter.py

This moves `py3.get_color_names` helper from self-contained parsing to formatter parsing.
>@tobes This function should be fixed so it give accurate results. Currently it uses a poor method
to find the colors.
It did give us what we need with 100% accuracy targeting a specific type of colors, which is placeholder color names to be used with thresholds. This excludes other colors (i.e. css color names, hex color codes, and special color names).
>>@lasers self.py3.get_color_placeholders_list might be more accurate... similar to
>
>@tobes colours are not placeholders
Yes sir. That's why I went with `get_color_names`. Alternative names could be... 
* `get_threshold_color_names`
* `get_threshold_names`
* `get_color_placeholders`
* `get_threshold_placeholders`
I dunno. They're all wonderful. …

py3: move py3.get_color_names helper to formatter

---

py3status/modules/keyboard_layout.py

Fixes #1779
- Warn user of #1779 when using `setxkbmap`
- Prefer `xkblayout-state` when switching layout because it can switch layout properly (Using group lock)
Edit: Fix some formatting

keyboard_layout: Use xkblayout-state to switch layout

---

py3status/py3.py

We can match more than once to better specify different list of placeholders for different functions.
```diff
diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index 1cfbfed..1c0059f 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -17,9 +17,13 @@ class Py3status:
"""
-    format = "Hello, world!"
+    format = "{hello_world} {hell} {word2} {help} {zebra} {test}"
+    # format = "{hello_name} {help_girl} {word} {test_me}"
def static_string(self):
+        matches = ["hell*", "test", "word"]
+        placeholders = self.py3.get_placeholders_list(self.format, matches)
+        self.py3.log(placeholders)
return {
"cached_until": self.py3.CACHE_FOREVER,
"full_text": self.py3.safe_format(self.format),
```

py3: add multiple get_placeholders_list

---

py3status/modules/mpris.py

1) Minimal fix is commit `mpris: disable next/previous buttons`.
>There are two ways to control the media player. Either by clicking with a mouse
button in the text information or by using buttons. For former you have
to define the button parameters in your config.
Because we have two ways to control, we shouldn't have both enabled at same time. I also do not think it is ideal to default next/previous with scrolling buttons. If anything, users should set this themselves. The stop button is already disabled by default... leaving us with only (enabled) toggling button. It also helps that default `format` already next/previous placeholders for users to use instead.. or make changes. Overall, it is a better default behavior (imo).
i) Alternative: Tell users to disable `button` 4 or 5 when …

mpris: make new default changes

---

py3status/module.py

This ought to allow `markup` on both composite and non-composite.
Unrelated: My markup code for composite got gimped so I'm removing everything except markup. 
Addresses #1783.

module: fix pango markup for non-composite modules

---

py3status/modules/group.py

Different PR.
* `group: calculate remaining times to cycle more accurately` (Bugfix)
* `group: skip cycle on first run, use MAX_NO_CONTENT_WAIT` (Bugfix)
* Always get the first module on startup instead of 2nd, 3rd, etc. If first module is slow, then wait 5 seconds, then try again or move on to next module. (Enhancement) 
Addresses #1777.

group: calculate remaining times to cycle more accurately

---

py3status/modules/net_rate.py

Whilst looking into an issue, I saw something trivial and wanted to get it out of way.
This calls `time()` and `_get_stat()` once instead of twice on every interval.
The data ~~does not~~ might have time to change. The `time` likely change slightly.
This should be more accurate and should sometimes give us slightly more.

net_rate: call functions once instead of twice

---

py3status/py3.py

I tested this with:
```diff
diff --git a/py3status/modules/static_string.py b/py3status/modules/static_string.py
index 1cfbfed..aeca0fe 100644
--- a/py3status/modules/static_string.py
+++ b/py3status/modules/static_string.py
@@ -20,6 +20,7 @@ class Py3status:
format = "Hello, world!"
def static_string(self):
+        self.py3.log(self.py3.format_units(100, "Mb"))
return {
"cached_until": self.py3.CACHE_FOREVER,
"full_text": self.py3.safe_format(self.format),
```
Before.
```
➜ python3 static_string.py 
Module `test_module`: (0.0001, 'Mb')
Module `test_module`: (0.0001, 'Mb')
```
After.
```                                                                                  
➜ python3 static_string.py
Module `test_module`: (0.0008, 'Mb')
Module `test_module`: (0.0008, 'Mb')
```
Conversion.
``` …
```

py3: support converting bytes to bits on format_units()

---

py3status/modules/keyboard_layout.py

Fixes #1794 
**Changes:**
- changes "xkblayout-state print %S" to "xkblayout-state print %E". This way the keyboard variant is returned if there is one set.

keyboard_layout: xkblayout-state should prefer variant if available

---

py3status/modules/sysdata.py
py3status/py3.py

(Alt. PR) This implements the `cpu_hist` module in `sysdata` instead. This also adds a new `sysdata` feature -- displaying per cpu name + percent... This feature is required to make `cpu_hist` possible. 
This feature was requested in the past too. https://github.com/ultrabug/py3status/issues/1336. The coding is 90% done. The last 10% is asking @farnoy to try this first and see if he's happy with it... And/or that maybe `py3.get_color_names_list()` should have matches added too. 
Addresss https://github.com/ultrabug/py3status/pull/1693.
EDIT: The coding is 100% done. I added matches for `py3.get_color_names_list()` too.

sysdata: add cpus, format_cpu, format_cpu_separator, etc

---

py3status/modules/clementine.py

MPRIS1 support was removed, making the clementine module useless. This updates it to support MPRIS2, the new standard adopted.
Commit that removes MPRIS1: https://github.com/clementine-player/Clementine/commit/ed13d02

Update Clementine module to use MPRIS2

---

py3status/modules/arch_updates.py

The bug manifests in the arch_updates module when no AUR updates found. The `auracle sync` command in such case returns exit status 1:
```
Command `auracle sync` returned non-zero exit status 1
```
Instead of returning 0 as the result of `len(updates.splitlines())`, the exception code is being executed, that results in strange display like "UPD: 0/None" for default format.
As a simple workaround, I propose returning 0 instead of None.

arch_updates module: auracle throws exit code on zero updates

---

py3status/modules/xrandr.py

This allow users to change OUTPUT text.
```python
order += "xrandr"
xrandr {
DP-2 = "🖵 2"
DP-3 = "🖵 3"
}
```
Addresses #1800.

xrandr: allow users to change OUTPUT text

---

py3status/modules/volume_status.py

- permit specifying device by name
- handle changes to default device at any time, not just when previous default device has died
- report failures accurately:
- permit custom format_missing if the device is not found
- otherwise use format, but with perc of "?", rather than misleadingly reporting unmuted 0%

volume_status: pactl improvements

---

py3status/modules/bluetooth.py

I got an impression that we are slowly switching to `pydbus`, this is just one tiny step towards getting rid of `dbus` dependency.

bluetooth: switch to pydbus

---

doc/configuration.rst
py3status/core.py
py3status/module.py

ability to import resources
----
You can specify `resources` in module or py3status configuration section.
```python
py3status {
resources = [
('color_bad', '*color9', 'lightcoral'),
('color_good', '*color10', 'lightgreen'),
('color_degraded', '*color11', 'khaki'),
('nagbar_font', 'py3status.font', 'pango:Ubuntu Mono 12'),
]
}
```
```python
order += "coin_market"
coin_market {
resources = [
('color_color9', '*color9', 'black'),
('color_color10', '*color10', 'black'),
]
thresholds = [(-100, "color9"), (0, "color10")]
}
```
I'm using `fnmatch`. Is this wanted? It's possible to use `str.startswith()` instead.
This can import more than just colors... such as font and any other settings. If users want to, they should be able to specify `py3status.font`, `py3status.color`, etc.. similar to …

core, module: add an ability to import resources

---

README.rst

Changed the logo URL in the README to point to the main repo and not Tobaloidee's fork, in case the fork gets deleted in the future.

Fix logo url in README

---

py3status/core.py
py3status/formatter.py
py3status/py3.py
tests/test_formatter.py

This aims to replace unrelated `fix_color` code in #1472. I found more things to use `expand_color` on too. This passed all the tests, but I see two instances where the tests can be wrong.
If you want to close this and #1472 instead, then that's fine too. Black star just in case.
Addresses #1472 unrelatedly.
EDIT: Do you like `expand_color` or something else? `get_color`?

formatter: add expand_color()

---

py3status/formatter.py
tests/test_formatter.py

This adds `self.color` to `expand_color` used in the `formatter`. Originally not included because I thought it was redundant. You can see conky example below already working okay on `master`, but not in @ultrabug's `color_time` for `google_calendar`. Huh...
```python
order += "conky info"
conky info {
format = '[\?color=title&show OS] [\?color=output {distribution}] '
format += '[\?color=title&show CPU] [\?color=output {cpu cpu0}%] '
format += '[\?color=title&show MEM] '
format += '[\?color=output {mem}/{memmax} ({memperc}%)] '
format += '[\?color=title&show HDD] [\?color=output {fs_used_perc}%] '
format += '[\?color=title&show Kernel] [\?color=output {kernel}] '
format += '[\?color=title&show Loadavg] [\?color=output {loadavg 1}] '
format += '[\?color=title&show Uptime] [\?color=output …
```

formatter: revision 1

---

doc/contributing.rst

see e.g. [tox docs / logo](https://tox.readthedocs.io/)

tox is always lowercase

---

py3status/modules/spotify.py

I've been bothered for a pretty long time now that module for music player doesn't have an option to show whether the music is actually playing. I hope someone will find this little change as useful as I do.

Add `paused` control placeholder to spotify module

---

py3status/modules/mpris.py

Use try/except to return `False` on failed player objects instead of maintaining a list (i.e. `chrome`, `chromium`, etc).  /cc @valdur55
Addresses https://github.com/ultrabug/py3status/issues/1827

mpris module: fix KeyError exception

---

py3status/module_test.py

Mpris module uses is_gevent but module_test doesn''t have such attribute.
Addresses #1827

Mpris module: Fix AttributeError: 'MockPy3statusWrapper' object has no attribute 'is_gevent'

---

py3status/constants.py
py3status/i3status.py

This support i3status `memory` module. It seems like `valid_config_param()` along with `i3status_module_names` are not used so I'm removing/simplifying.

i3status: support memory module, remove valid_config_param

---

py3status/modules/wifi.py

This is a pretty minor change that allows for selecting a WiFi device by its MAC address as an alternative to its name in the `wifi` module. Reason for wanting this is because there is currently an issue/dispute/race condition between `iwd` and `systemd-udevd` over who should control WiFi interface names.
Given that it's causing network interface names to be unpredictable, it seems like people are generally resorting to selecting a network interface by its MAC address instead now (e.g. with `systemd-networkd` config files). This simply adds the same to `py3status`.

[wifi] device by MAC address as alternative to name

---

py3status/modules/networkmanager.py

Fixes `py3status - build passing | docs failing`

networkmanager: fix documentation

---

py3status/modules/sysdata.py

In some case the swap memory on a machine is available at a time and not available at another (for example if you plug your swap on a removable device...).
So I've notice that in that case, the sysdata module fail with a "divide by zero" exception.
This PR propose a fix to this.
Feel free to make any feedbacks

sysdata : Prevent a divide by zero on empty swap

---

py3status/modules/weather_owm.py

This adds minimal thresholds code for `humidity`, but not others.
Resolves #1843

weather_own module: add thresholds for humidity

---

py3status/modules/weather_owm.py

This fixes ``format_forecast_separator = '\?color=red , '`` to print red commas instead of literal `\?color=red , ` strings.

weather_owm module: add safeformat for separator, rename separator

---

py3status/modules/arch_updates.py

After the most recent update to the checkupdates script, the _get_checkupdates_updates method requires a change, similar to the _get_auracle_updates.
Without this, is simply return 'None' instead of 0 when there are no updates.

Fix compatibility to checkupates update

---

py3status/modules/coin_market.py

This addresses https://github.com/ultrabug/py3status/pull/1847#issuecomment-539927382 by skipping empty datas when we're comparing markets. We validate markets at first run too.
* Full url gives us 1000+ markets. We don't need that.
* Minimal url gives us 5 or more markets depending on user-specified + padding.
With global request changes, we wait for data to come first before comparing.

coin_market module: skip empty datas

---

doc/configuration.rst
py3status/py3.py

Requests failing due to network unavailability or remote server timeouts are
retried automatically ``request_retry_times`` times (default ``3``) at a
``request_retry_wait`` (default ``2``) seconds interval.
This allows to be more graceful to i3 startup when network is not up yet or to
short network disruptions and not display an error on the bar in that case.
This is related to the MR #1842 inspired by the work of @jose1711

implement global request_retry_times and request_retry_wait options

---

py3status/modules/usbguard.py

usbguard v0.7.5 made a breaking change and switched to [versioned dbus](https://github.com/USBGuard/usbguard/pull/302), this PR adapts our module for these changes.

usbguard: update for versioned dbus in 0.7.5

---

py3status/modules/mpris.py

VLC use a vlc:nowplaying field, at least when playing field
This is useful when the title field is static and only this field change
when playing a stream.

mpris: add nowplaying field

---

py3status/modules/window.py

This fixes second output issue in https://github.com/ultrabug/py3status/pull/1854#issuecomment-549896144
When making `window`, I tested with `swaymsg -t get_tree` on i3. I take it `swaymsg -t get_tree` does not output 100% same on sway due to missing `nodes` key and maybe others.
This PR is tested okay on default sway. `hide_title` works okay too.
The first output issue (missing/no title) looks unrelated imho.

window: get nodes or empty lists

---

py3status/module_test.py
py3status/modules/scratchpad.py
py3status/modules/window.py

This permits us to use cli arguments to test different configs for easier testing in terminal.
```bash
$ python scratchpad.py --term --ipc [i3ipc|i3msg|swaymsg] 
$ python window.py --term --ipc [i3ipc|i3msg|swaymsg]
$ python loadavg.py --term --format "Testing format... [\?color=1avg {1min}], {5min}, {15min}"
$ python xrandr.py --term --icon_extend "|"
$ python weather_owm.py --term --api_key LONG_API_KEY
```
This replaces a small testing code in ~~`scratchpad`~~ `window` too.

module_test: support config cli arguments

---

doc/configuration.rst

This fixes unexpected unindents mentioned in https://github.com/ultrabug/py3status/issues/1865#issuecomment-553745682. 
```
py3status/doc/configuration.rst:166: WARNING: Bullet list ends without a blank line; unexpected unindent.
py3status/doc/configuration.rst:185: WARNING: Bullet list ends without a blank line; unexpected unindent.
py3status/doc/configuration.rst:924: WARNING: Bullet list ends without a blank line; unexpected unindent.
```

doc/configuration.rst: fix unexpected unindents

---

py3status/modules/spaceapi.py

If you are offline, clicking `spaceapi: N/A` produces this because of missing `_url`.
```python
2019-12-12 INFO trying to dispatch event to module "spaceapi"
2019-12-12 WARNING on_click event in `spaceapi` failed (AttributeError) spaceapi.py line 125.
2019-12-12 INFO Traceback
AttributeError: 'Py3status' object has no attribute '_url'
File "py3status/module.py", line 901, in click_event
click_method(event)
File "py3status/modules/spaceapi.py", line 125, in on_click
if self._url and self.button_url == button:
```
EDIT: And.... if you got an `_url` and go offline later, it should not open url again.
EDIT 2: It'd be nice to kill try/exception, `STRING_UNAVAILABLE`, etc in favor of exposing real error.

spaceapi: fix offline attributeerror exception

---

py3status/modules/getjson.py

This allows getjson users to specify a basic auth user/pass
Thanks to @CorruptCommit for reporting

getjson module: support basic auth via username/password fix #1875

---

.travis.yml
setup.py
tests/test_module_doc.py

Finally had time to figure out why unit tests have been failing for me on Arch since the last release, but Travis was green.
https://docs.python.org/3/library/ast.html
> Deprecated since version 3.8: Class ast.Constant is now used for all constants.
Old classes ast.Num, ast.Str, ast.Bytes, ast.NameConstant and ast.Ellipsis are still available, but they will be removed in future Python releases.
Adding python 3.8 to testing matrix

Fix tests for python 3.8

---

py3status/modules/imap.py

This implements some changes I've had running for over a year now, but never had the time to clean up and submit here (partly, because I've finally completed the move to a better mail host).
In essence, some mail providers (cough, cough, yahoo, cough) are just plain awful at keeping connections (automatic logout after a few minutes of not issuing a command,  randomly just refusing to log in, ...). This implements a fail-safe retry logic (retry two times, then error out).
I've opted to not expose the retry count and delay to the user, since configuring this doesn't make much of a difference, but I'm open to changes.
while I was at it, I also opted to refactor the long log messages to use String.format() instead of string concatenation. It makes sense to look at each commit on its own, …

imap module: implement retry logic (works around badly configured mail servers)

---

py3status/modules/mpd_status.py

Issuing commands every two seconds, even if nothing changes causes high
CPU load with Mopidy-MPD, and possibly other MPD servers. With polling
every 2 seconds (the default), mopidy (while paused) was consuming
between 10% and 15%, with occational spikes even up to 20% cpu; using
idling, this number dropped to 0.0%.
This patch is similar to IDLE in imap.py, where we listen for changes on
subsystems we're interested in (99% that's just 'player', but we'll
default to 'mixer' (changes in volume) and 'options' (e.g. repeat mode)
too, just in case a user has those states displayed in her status bar).

mpd_status using idle (major cpu savings)

---

py3status/modules/mpd_status.py

sorry @ultrabug for the amount of work i'm generating for you currently. i promise, this will be the last update to mpd_status for a while ;-)
essentially, I've found out how to properly use the mpd2 library and this will remove my awful, hack-y workaround, as well as bring the idle_subsystems argument in line with other list-like ones.

mpd_status: clean up idle

---

.travis.yml
py3status/py3.py
py3status/storage.py

Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1791939
On Python 3.9:
```
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/sphinx/config.py", line 361, in eval_config_file
execfile_(filename, namespace)
File "/usr/lib/python3.9/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
exec(code, _globals)
File "/builddir/build/BUILD/py3status-3.24/doc/conf.py", line 5, in <module>
from py3status.autodoc import (
File "/builddir/build/BUILD/py3status-3.24/py3status/autodoc.py", line 15, in <module>
from py3status.py3 import Py3
File "/builddir/build/BUILD/py3status-3.24/py3status/py3.py", line 19, in <module>
from py3status.storage import Storage
File "/builddir/build/BUILD/py3status-3.24/py3status/storage.py", line 5, in <module>
from …
```

Fix collections.abc imports for Python 3.9

---

py3status/modules/imap.py

When OAuth is being used in the imap module and the network tries to redirect requests to a captive portal, google.auth.exceptions.TransportError is raised.
Unlike other errors that might be caused by authentication issues (which will throw a fatal error in the module) this specific case should probably be handled just like another recoverable network error - that is, keep trying until the network fixes itself.
To avoid all users having to install the OAuth library in order to catch this exception, a list of recoverable errors is stored as an attribute in the module, so that this exception can be dynamically added when OAuth is used.
Split out of discussion in #1883 
note: these commits need to be updated for the latest master, and probably for #1885

imap module: Handle OAuth TransportError

---

py3status/modules/imap.py

As stated in RFC 2177 (https://tools.ietf.org/html/rfc2177)  
> The server requests a response to the IDLE command using the continuation ("+") [...]
For example curier responds with "+ entering idle mode" instead of "+ idling".

Fix imap idle for courier

---

py3status/constants.py

This support i3status `read_file` module. Untested.
Closes https://github.com/ultrabug/py3status/issues/1908.

i3status: support read_file module

---

py3status/modules/clock.py

Time format use locale for displaying some options (like %a, %A ...), this
parameter is used to override the system locale.
Example:
clock master {
cycle = 30
locale = "fr_FR"
format = ["{Europe/Paris}"]
format_time = "%a %d/%m/%Y {icon} %H:%M"
}
Override the system locale to "fr_FR" locale.

Adding "locale" config parameter on clock module.

---

py3status/modules/mpd_status.py

when playling a live stream with embedded title information (e.g.
through mopidy), the currentsong command can provide the embedded track
metadata like the currenlty playing title, instead of just the filename.
**Edit**: looks like travis isn't talking to github right now. [tests passed](https://travis-ci.org/github/ultrabug/py3status/builds/668850084).

[MPD module] use currentsong command if possible

---

py3status/modules/networkmanager.py

Currently, you can only configure your format with access points numbers, e.g.  `ap1_ssid`, `ap2_bars`, ...
This works fine most of the time because `nmcli` only returns one AP, the currently active one. So most of the time the `ap1_xxx` placeholders make sense. However, occasionally, `nmcli` may return additional APs (for instance when a scan has been performed). In that case, AP1 may not always be the currently active AP, and if your format contains `ap1_ssid` py3status will show you as being connected to an incorrect SSID. 
This change allows to use `ap_ssid`, `ap_rate` instead of `ap1_ssid` etc. so that py3status always shows the information related to the currently used AP, and not just a specific AP number.

NetworkManager: allow using the currently active AP in formats

---

py3status/modules/volume_status.py

This document commands to print possible devices. /cc @jose1711 and others. Will this do? 
Closes https://github.com/ultrabug/py3status/issues/1915.

volume_status: document commands to print possible devices

---

py3status/module.py
py3status/modules/do_not_disturb.py
py3status/modules/frame.py
py3status/modules/networkmanager.py
py3status/modules/pingdom.py
py3status/modules/sysdata.py
py3status/parse_config.py
tox.ini

This fixes things and whatnot to pass tests. I failed to get rid of this one though. Seems ok to me.
>========== warnings summary ==========
tests/test_module_doc.py: 66 tests with warnings
<string>:1: DeprecationWarning: invalid escape sequence \?
...

fix flake8 code linting and black code formatting to pass tests

---

py3status/modules/sysdata.py

also changed regex to support modern desktop intel/amd cpus
This should also make `zone` somewhat obsolete.

sysdata module: try to use default intel/amd sensors first

---

py3status/module.py

- `inspect.getargspec` was deprected in favor of
`inspect.getfullargspec`, which also supports return type annotations.
Fixes #1941

Remove deprectated function in modules.py

---

py3status/modules/mpris.py

This pull request is basically a workaround that bypasses chromium broken mpris interface thus allowing py3status to show which media is currently being played in the browser.
**Bugs**:
- Control buttons don't work as chromium doesn't expose any interface in dbus, maybe can be fixed with some IPC
- If a player with higher priority was running the title of the old media will remain until you switch to a tab with a new media
- If playback is started before py3status the status bar won't be synchronized until a new media is played
At the moment i'm not planning on fixing those bugs because the most sensible way to do it would be to fix chromium's MPRIS.

Broken chromium mpris interface workaround

---

py3status/modules/battery_level.py

Previous code only matches with "BAT*" names in the /sys/class/power_supply.
There does not seem to be any naming convention in the documentation:
https://www.kernel.org/doc/html/latest/power/power_supply_class.html
For example, the battery on the GPD Pocket is exposed as "max170xx_battery".
This patch allows for easier addition of glob patterns to use to match for
battery nodes and adds "*bat*" in the list.

Support more battery in battery_level module

---

py3status/modules/battery_level.py

Skip batteries with missing info that leads to exceptions.
In my system, I have a Logitech Keyboard and a Logitech Mouse that appears in `/sys/class/power_supply` but they raise exceptions when parsed because of missing info:
File: `/sys/class/power_supply/hidpp_battery_0/uevent`
```
POWER_SUPPLY_NAME=hidpp_battery_0
POWER_SUPPLY_ONLINE=1
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_SCOPE=Device
POWER_SUPPLY_MODEL_NAME=Wireless Keyboard K270
POWER_SUPPLY_MANUFACTURER=Logitech
POWER_SUPPLY_SERIAL_NUMBER=OMISSIS
POWER_SUPPLY_CAPACITY_LEVEL=Full
```

Skip batteries with missing info

---

py3status/modules/sysdata.py

Fix #1958 by bumping head value to 28.
Raspberry Pi4 has SReclaimable value at line 28.

Sysdata: increasing meminfo readable lines count to support Raspberry Pi4

---

py3status/modules/hueshift.py

Fix hueshift being initialized with the cached value+delta.

hueshift module: fix initialization incrementing cached value by delta

---

doc/configuration.rst
py3status/constants.py
py3status/module.py

Thanks to the initial work of @lasers #1968
When a module error has occurred, it will be reported on the bar.
The ``on_error`` configuration parameter allows users to choose
what to do instead.
Supported values:
- ``show`` (default): report the error on the bar (click to view)
- ``hide``: hide the module on the bar

core: new "on_error" parameter to control module error behavior

---

py3status/modules/diskdata.py

This ignores errors from `df` because of permission denied and/or other reasons. Cope.
Closes https://github.com/ultrabug/py3status/issues/1957.

diskdata: ignore df errors

---

py3status/modules/spotify.py

Without this patch, spotify module only supports spotify client,
but doesn't support spotifyd. Spotifyd users need to use mpris
or other, while the spotify module is just fine.
This is problematic as it means users will write new plugins or
new code for almost no reason.
This fixes it by making the dbus commands more flexible, to be
able to use org.mpris.MediaPlayer2.spotifyd for spotifyd users
or org.mpris.MediaPlayer2.spotify for regular users. If a new
player out there supports a similar mpris interface with a new
client name, the users can now simply override the dbus_client
variable.

Add spotifyd support

---

py3status/i3status.py

'%+' is a variant of the locale specific time format based on the `date` command, and is available on some systems.

Add support for '%+' time format.

---

py3status/i3status.py

This allows users to use markup on tztime,time modules too.  Untested (as usual).
Closes #1976.

i3status: add markup support for time,tztime modules

---

setup.py

Fixes bug introduced in 37603bf3d08d08ebf8fe38ef5d419e51f03821ec and reported by @X-dark within #1978
`sys.path` contains `str` only and so should be all `Path`s converted to `str`.

Fix sys.path manipulation in setup.py

---

py3status/composite.py
py3status/core.py
py3status/events.py
py3status/module.py
py3status/modules/battery_level.py
py3status/modules/conky.py
py3status/modules/deadbeef.py
py3status/modules/google_calendar.py
py3status/modules/group.py
py3status/modules/hddtemp.py
py3status/modules/khal_calendar.py
py3status/modules/net_rate.py
py3status/modules/scratchpad.py
py3status/modules/screenshot.py
py3status/modules/sysdata.py
py3status/modules/taskwarrior.py
py3status/modules/weather_owm.py
py3status/modules/xkb_input.py
py3status/modules/xrandr.py
py3status/modules/xrandr_rotate.py
tests/test_module_doc.py

Remove some redundant code, such as square brackets, as well as `map/lambda` calls and use list/generator/dict comprehensions where appropriate.

Use list/generator/dict comprehensions where appropriate

---

py3status/modules/mpris.py

Chrome is exactly as broken as Chromium, but has the player_id "chrome",
instead of "chromium".
This adds a rather unelegant but simple workaround, to "fix" it in the same way.

Fixes mpris for Chrome, too.

---

py3status/i3status.py

There's a stdlib's `datetime.timezone` class for a custom time zone (just with a different signature), so no need to define one's own.

i3status: use datetime.timezone for a custom tz

---

py3status/modules/timewarrior.py

When only `utc` is needed, stdlib's `datetime.timezone.utc` is a good replacement for `pytz`.
I'd also like to see `pytz` disappearing from `clock.py` and replacing it with `zoneinfo` (stdlib in Python3.9, `backports.zoneinfo` in 3.6–3.8), but the `tzlocal` cannot be replaces easily and `pytz.country_timezones` are probably still needed).

Replace pytz with datetime.timezone for taskwarrior

---

py3status/formatter.py
py3status/module.py
py3status/modules/battery_level.py
py3status/modules/clock.py
py3status/modules/graphite.py
py3status/modules/lm_sensors.py
py3status/modules/nvidia_smi.py
py3status/modules/pomodoro.py
py3status/modules/rate_counter.py
py3status/modules/sysdata.py
py3status/modules/volume_status.py
py3status/modules/weather_owm.py
py3status/modules/wifi.py
py3status/modules/xsel.py

Remove unnecessary int/float conversions in Python3 code that were needed in Python2.
Another idea would be to use `ratio` (0.0–1.0) instead of `percents` (0–100) and only convert them to string at the end (`f'{0.1234:.1%}'` converts nicely to `12.3%`), which would save a lot of multiplication/division by 100 in the code. What do you think?

Remove obsolete numeric relics from Python 2

---

py3status/core.py
py3status/i3status.py
py3status/module.py
py3status/module_test.py
py3status/modules/clock.py
py3status/modules/diskdata.py
py3status/modules/google_calendar.py
py3status/modules/group.py
py3status/modules/mpris.py
py3status/modules/net_rate.py
py3status/modules/netdata.py
py3status/modules/pomodoro.py
py3status/modules/rainbow.py
py3status/modules/rate_counter.py
py3status/modules/speedtest.py
py3status/modules/timer.py
py3status/modules/uptime.py
py3status/modules/velib_metropole.py
py3status/modules/whatismyip.py
py3status/py3.py
py3status/storage.py

When using `time.time()` twice to get a short timedelta, such as refresh rate, timeout, or elapsed time, where the zero (unix epoch) is not important, this may return false (even negative) results if the system clock gets updated during that time.
To measure such short timedeltas, `time.perf_counter()` is better, because at each call it returns a positive float that is higher than the previous value.
The negative point is that this float is process-dependent and cannot be shared between processes. Therefore I have avoided modification of the code that stores this value on disk for the next instance to load it.
There are several name misuses of `time` in the code. They should be renamed to something more meaningful.

Use time.perf_counter to measure short time periods

---

py3status/argparsers.py
py3status/py3.py

As promised, here is the PR to replace the external `which` binary with pure Python code: [`shutil.which`](https://docs.python.org/3/library/shutil.html#shutil.which) has been introduced in Python 3.3 and follows the same conventions as the current code, returning either a string with the full path to the executable or None if the executable wasn't found on `$PATH`. This helps reducing the amount of external utilities that py3status has to rely on.
Closes: #1994

argparsers: use shutil.which instead of external which binary

---

py3status/storage.py

Work with `storage_dir` and `storage_file` as `str` in `storage.py/__init__.py` and convert to `pathlib.Path` only when writing to `self.storage_path`. 
Fixes #2004

Fix Path generation in storage

---

py3status/modules/net_iplist.py

net_iplist shows all ipv6 addresses on a interface which can be alot. This patch removes all old deprecated from the list.

net_iplist show only non deprecated ipv6 addresses

---

py3status/modules/volume_status.py

pipewire is now able to completely replace pulseaudio, so there may be
no "pulseaudio" command.

volume_status: run with either pulseaudio or pipewire installed

---

py3status/modules/battery_level.py

This PR fixes computing of the battery remaining time. The `h` value was not ensured to be an integer which caused issues in function `_hms_to_seconds` trying to call someting like `int("0.0")` and resulting with an error.

battery_level module: fix converting seconds to H:M:S format

---

py3status/modules/kdeconnector.py

If the battery is unavailable, the following error occurs:
```
TypeError: 'NoneType' object is not subscriptable
File "/usr/lib/python3.9/site-packages/py3status/module.py", line 948, in run
File "/usr/lib/python3.9/site-packages/py3status/modules/kdeconnector.py", line 268, in kdeconnector
(text, color) = self._get_text()
File "/usr/lib/python3.9/site-packages/py3status/modules/kdeconnector.py", line 244, in _get_text
(charge, bat_status, color) = self._get_battery_status(battery)
File "/usr/lib/python3.9/site-packages/py3status/modules/kdeconnector.py", line 197, in _get_battery_status
if battery["charge"] == -1:
```
This is a similar issue to #461.

kdeconnector module: fix for battery unavailable

---

py3status/modules/google_calendar.py

This pull requests adds two options to the Google Calendar plugin :
1. The call to the browser can be customized if required (you might not
want use the browser default while opening an event).
2. It is now possible to open the Meet Hangout VC link (associated from the caledar details)
instead of the google calendar event.
We'll always fallback to the htmlLink (event itself) in the case the
hangout VC does not exists.
Those two parameters are optional.
Example of usage :
```
google_calendar {
browser_invocation = "i3-msg '[title=\".*?Meet.*?\" workspace=\"0\"] kill; workspace 0; exec /usr/bin/google-chrome --app={}'"
preferred_event_link = "hangoutLink"
}
```
This way, I ask my window manager i3 to close any previous opened
google meet before reopening one in a dedicated workspace.
These …

[Module : Google Calendar] Additional options

---

py3status/core.py

before this fix, users could add their modules from local paths
or entry points but not have multiple instances of them
thanks to @mcgillij @lasers and @eumiro

core: fix detection of instances of user provided modules fix #2020

---

py3status/modules/weather_owm.py

I've added an option for wind direction.
Degrees doesn't say much for me, but i care about where the wind is coming from. I've put the names on it based on range direction
Used this table for the mapping : https://www.researchgate.net/figure/The-main-compass-directions-of-the-wind-used-for-clustering-the-wind-direction_tbl1_252953902

Wind direction added for weather_osm module

---

py3status/modules/sysdata.py

This is my cleanup attempt to really solve #1614, #1928, #1933, and #1995. 
* Rename `temp_unit` to `cpu_temp_unit`. More specific. (Unrelated)
* Replace messy `zone` config/code with auto cpu sensors.
* This removes sysfs path. Author wanted this so he can point it to `Tdie`.
* This also removes where you can get temperature data for things that aren't CPUs... to `{cpu_temp}`.
To explain a bit more about this... My understanding is that...
* If you're on `Intel coretemp-isa-000`, you want to parse `Core ?*`.
* If you're on `Ryzen k10temp-pci-00c3`, you want to parse `Tdie`.
* If you're on `...`, you want to parse `...`. We can add more like this now using `chips_and_sensors`.
Feature:
* If you're on `RPi cpu_thermal-virtual-0`, you want to parse `temp?`.
Feature:
* On `Intel`'s `Core …

sysdata: optimize cpu_temp

---

py3status/modules/timewarrior.py

Hello,
This little PR intends to fix a bug in the timewarrior module.
Timewarrior module was crashlooping on my pc and py3status was consuming ~90% cpu times.
I investigated and found that an internal error occured inside the timewarrior module by looking at the logs:
```
Apr 14 21:21:39 z-dev py3status: Instance `timewarrior`, user method `timewarrior` failed.
```
I found that each module has a main function with tests so i tried running it:
```sh
$ python3 ~/.local/lib/python3.9/site-packages/py3status/modules/timewarrior.py
can't compare offset-naive and offset-aware datetimes.
Traceback
TypeError: can't compare offset-naive and offset-aware datetimes
File "/home/gfeun/.local/lib/python3.9/site-packages/py3status/module.py", line 948, in run
File …
```

timewarrior: remove timezone info from end date

---

py3status/modules/weather_owm.py

This allows users to specify rounding numbers instead of hardcoded rounded numbers.
The _2nd_ commit is optional. It's something I think would help with frequently exposing rain / snow formats.
/cc potential tester @mlmatlock
Closes https://github.com/ultrabug/py3status/issues/2032.

weather_owm: remove hardcoded rounded numbers

---

py3status/modules/weather_owm.py

The knot is the unit of windspeed used in avionics and nautical settings. This PR adds support for knot as a windspeed unit.

Added support for displaying wind speeds in knots

---

py3status/modules/spotify.py

There's [a bug in spotifyd](https://github.com/Spotifyd/spotifyd/issues/890) that causes the `PlayPause` toggle command not to work. To work around this, I've added a check for the current state of the player before sending either a `Play` or a `Pause` command, which effectively toggles the player.

Work around bug in spotifyd

---

py3status/modules/weather_owm.py

Because naive datetime objects are treated by many datetime methods as local times, it would be better to make those objects aware to show correct time.
Also if we would like to force UTC it is recommended way to create an object representing a specific timestamp in UTC is by calling datetime.fromtimestamp(timestamp, tz=timezone.utc)

_format_sunrise and _format_sunset as aware dt

---

py3status/modules/whoami.py

As per the title. Allows format strings like "{username}@{hostname}" which I find useful with multiple machines.

whoami module: Add {hostname} placeholder to output

---

py3status/modules/sysdata.py

This PR turns our supported CPU sensors into a list each so `k10temp` chip can display Tdie or Tctl, but not both because  `{cpu_temp}` is strictly one placeholder / one sensor / one cpu_temperature. If you happen to have both sensors, `Tdie` will be used. Testers needed. 
Closes https://github.com/ultrabug/py3status/issues/2079.

sysdata: add tctl sensor

---

py3status/modules/scratchpad.py

At first round I applied same approach as Msg module is using.
For short conclusion it was like calling: `Msg.find_scratchpad(i3.get_tree().ipc_data).get("floating_nodes", [])` and output was list of scratchpad windows.
During commenting line about workaround I remembered one changelog line from I3ipc-python v2.2.1 (Version released on Apr 5, 2020) : 
`Fix scratchpad for sway (f11e729).`
And then I ended up calling:
`getattr(i3.get_tree().scratchpad(), "floating_nodes", [])`
Storing scratchpad as separate variable for better debuggability.
Tested it out with sway (v1.4) and i3 (v4.20). Both desktop env works and Msg is already using same approach to get list of scratchpad windows.  (Fixes #2038)

[scratchpad] Workaround for I3ipc 2.2.1 not finding leaves() in sway

---

py3status/modules/window.py

In process of testing #2086 found deeper issue.
There is no point for looking focused window/container inside of window tree when needed data is already provided by event argument.
Additional changes:
* Window cleaning uses last workspace as placeholder.

[window] I3ipc backend uses incoming event data and relies less on get_tree.focused() data.

---

py3status/modules/pomodoro.py

pyglet and pygame are no longer needed for playing sound files since the merge of #1770

Update documentation for the pomodoro module

---

py3status/modules/arch_updates.py

Fixes update checks with paru.
Unlike yay, paru exits with return value `1` after `paru -Qua`, if there are no AUR updates available (conforming to the behavior of `pacman` itself)
Thus we should return `0` if `-Qua` exits with `1`.

arch_updates module: paru exits with a non-zero status if there are no updates

---

py3status/events.py

With pydevd.debugger first click caused "JSONDecodeError: Expecting value: line 1 column 2 (char 1)". (Fixes #2090)

[events] With pydevd.debugger first click caused error

---

py3status/modules/khal_calendar.py

I noticed that the khal_calendar module quickly overwhelms my status bar when there are multiple events scheduled for today. Introducing a 'limit' config option keeps the space manageable.

added option for the khal_calendar module to limit the number of returned calendar entries

---

py3status/core.py
py3status/module.py

Auto update makes assumption that there isn't interruption between updates.
Now when module sends CACHE_FOREVER then system checks if pending update_due is from module (from previous auto update cycle) and then sets next update_due.... 
Address #2085

Try to fix root cause of negative update_due

---

py3status/formatter.py

This fixes a pango markup regression starting with `&`, then eventually everything else too.
Closes https://github.com/ultrabug/py3status/issues/2118.

formatter: stop escaping html characters on pango markup

---

py3status/modules/twitch.py

This PR fixes the twitch module, that relied on an API that is no longer available. (closes #2123)
While I was at it, I documented the fields that were there all along (though they now have a prefix, depending on which endpoint provides them), documented the new fields provided by the new API and added the option to fetch stream tags. Some of the fields probably don't seem very useful at first glance, but might be interesting for some, if combined with `?if=` expressions, so I left them in.

Migrate to new Twitch API, fix #2123

---

py3status/modules/mail.py

os.path.expandvars() returns a string, not a Path. So, for
commit 37603bf3 to have worked, we needed to expand vars
first into a string, then convert to a path, then call
Path.expanduser().
Observed traceback prior  to the fix for added context, from current master branch:
```
2022-05-29 14:48:49 WARNING Exception in `mail` post_config_hook().
2022-05-29 14:48:49 INFO Traceback
AttributeError: 'str' object has no attribute 'exists'
File "...py3status.venv/lib/python3.9/site-packages/py3status/module.py", line 143, in prepare_module
self.module_class.post_config_hook()
File "...py3status.venv/lib/python3.9/site-packages/py3status/modules/mail.py", line 221, in post_config_hook
if not path.exists():
```

mail: fix pathlib adoption

---

py3status/modules/audiosink.py

This PR introduces a new module to display the current default audiosink (from pulseaudio) and let the user toggle it via left click.
The user can ignore sinks they never use via config.
Additionally short names for the devices can be configured such that no long device names get printed.

adds module audiosink

---

py3status/modules/mpris.py

(Franz, Chrome, Chromium) so skip identity cache and ask identity directly.

[mpris] Different players can use chromium busname

---

py3status/modules/volume_status.py

Grab the first control (`Master`, `PCM`, etc)... Otherwise, grab the last control... hopefully `Capture`.
Closes #2126.

volume_status: autoselect channel on amixer backend

---

py3status/modules/taskwarrior.py

Starting from TW 2.6.0 it's possible to specify a report to export in addition to just a filter. Most importantly, the exported data will respect the order of the specified report, rather than being ordered by ID number.
For example, by setting
```
filter = 'limit:3'
report = 'next'
```
we get the three most urgent tasks from the `next` report, in decreasing order of urgency (assuming the next report is sorted by urgency as is the default). As far as I know this is not possible using just a filter alone; using `task status:pending limit:3 export` returns the pending tasks with the three lowest ID numbers.
This is backwards-compatible since the default value of report is the empty string.

Specify report in task export for taskwarrior module

---

py3status/modules/window.py

(For example Pluma closing confirmation window)

[window] Window without title will not produce error on i3msg mode.

---

py3status/modules/volume_status.py

Using device and card parameter to be in same scope as other commands.
Closes #2151

volume_satus module: amixer scontrols uses device and card parameter.

---

py3status/events.py

I'm not exactly sure for the reason for the 500ms timeout in the events thread, but it seems like an unnecessary source of wakeups.
I've been running this patch on my system for a while now and nothing seems different, except the events thread doesn't wake up twice a second.

Change the reading timeout to infinity

---

py3status/modules/clock.py

clock module: migrate to standard zoneinfo with 3.7, 3.8 support.

---

py3status/modules/timewarrior.py

Adding a whole new dependency for a pretty simple operation is somewhat overkill in my opinion.
This closes #2160.

timewarrior: Remove dependency on dateutil

---

py3status/modules/battery_level.py

I want to `{icon}` to only display the info from `blocks`, even when the battery is charging, but currently there is no way to do this (AFAICT).  This change allows the user to obtain that behaviour, if they explicitly configure `charging_character = None`.

battery_level: Allow icon to not use charging_character

---

py3status/modules/do_not_disturb.py

Requested change by irc user Steinex.

do_not_disturb module: Use 'makoctl mode' to check current mode.

---

py3status/modules/google_calendar.py

This PR adds the `calendar_id` configuration option to the `google_calendar` module.
This will allow to use another calendar to display the upcoming events, instead of the hard-coded `primary`.

Add support to configure which google calendar will be used

---

py3status/modules/battery_level.py

This fixes invalid battery indexing and an enhancement to skip batteries with unavailable rate info.
~~The 2nd commit is optional and can be separated.~~ I skip `flake8` tests (broken).
/cc potential tester + pr requester
@Juliaria08 I'm not sure if we even need `last_known_capacity` anymore. Please test this again.
Closes #2178

battery_level: fix invalid indexing, skip batteries with unavailable info

---

py3status/modules/vpn_status.py

Add wireguard support. These connections are identified by `Type: wireguard` instead of the `Vpn` attribute.

vpn_status module: add wireguard support

---

py3status/modules/clock.py

This PR is a small patch to resolve the issue detailed in:
https://github.com/ultrabug/py3status/issues/2188
The `ZoneInfo` class doesn't seem to cater for local timezones (most likely no file detailing local information can be loaded), and the [datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) module indicates the default call returns the local timezone, eg `datetime.now(None)`.
Looking into `ZoneInfo` and I couldn't see much in the way for specifics regarding local timezones. So the safest thing seemed to return None, and explicitly handle it later.

Minor patch to get the local timezone.

---

py3status/screenshots.py

Fix two DeprecationWarning.
```
INFO     -  DeprecationWarning: getsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use getbbox or getlength instead.
File "python3.10-pillow-9.4.0/lib/python3.10/site-packages/PIL/_deprecate.py", line 65, in deprecate
warnings.warn(
File "py3status/py3status/screenshots.py", line 151, in
size = font.getsize(text)
INFO     -  DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
File "python3.10-pillow-9.4.0/lib/python3.10/site-packages/PIL/_deprecate.py", line 65, in deprecate
warnings.warn(
File "py3status/py3status/screenshots.py", line 170, in
txt = txt.resize((size[0] // SCALE, size[1] // SCALE), Image.ANTIALIAS)
```

fix two DeprecationWarning

---

py3status/modules/audiosink.py

This make it `audiosink-1-int.png` instead.
```
Creating screenshots in ~/src/py3status/docs/user-guide/screenshots...
...
async_script-0.png
async_script-1-example.png
audiosink-0.png
audiosink-1-@author Jens Brandt <py3status@brandt-george.de>.png    <---- 
aws_bill-0.png
backlight-0.png
...
```

audiosink: fix screenshots

---

py3status/constants.py
py3status/core.py

Feature parity? py3status top, i3status bottom.

core: autodetect output_format

---

py3status/modules/ns_checker.py

This fixes a dnspython deprecation warning:
"please use dns.resolver.Resolver.resolve() instead"

ns_checker module: replace query() with resolve()

---

py3status/modules/playerctl.py

Fixes #2205.
This PR adds support for the playerctl module. It uses [Playerctl's Python binding library](https://lazka.github.io/pgi-docs/Playerctl-2.0/) to monitor and extract information from players. Most of the configuration options are the same as the `cmus` module. There are three more added: `button_shift`, `button_unshift`, and `ignored_players`.
An important thing to note: If any text sent to i3bar contains an `&`, the text will not render. The `&` is common in videos and therefore creates a problem. I also see this issue in the `cmus` module, so it isn't directly an issue with this module, but should be solved to provide users with a better experience.
There are two ways I see solving this: 
1. Fix it in the playerctl module by doing some sort of `str.replace("&", "and")`
2. Fix …

Add playerctl module

---

py3status/modules/bluetooth.py

I wonder if it is a race condition. Untested. Trying to catch this exception.
Closes https://github.com/ultrabug/py3status/issues/2218.

bluetooth: reinitialize dbus

---

py3status/modules/lm_sensors.py

Config `chips` worked perfectly before we switched from `-u    Raw output` to `-j    Json output`.
The issue is that `sensor -j` does not always output valid json with multiple chips.
If you specify multiple chips using wildcard, you get valid json.
```json
❯ sensors -j '*-pci-*'
{
"nvme-pci-0b00":{
"Adapter": "PCI adapter",
"Composite":{
"temp1_input": 27.850,
"temp1_max": 79.850,
"temp1_min": -5.150,
"temp1_crit": 84.850,
"temp1_alarm": 0.000
}
},
"amdgpu-pci-0c00":{
"Adapter": "PCI adapter",
"vddgfx":{
"in0_input": 1.112
},
"vddnb":{
"in1_input": 0.837
},
"edge":{
"temp1_input": 32.000
},
"PPT":{
"power1_input": 18.000
}
},
"k10temp-pci-00c3":{
"Adapter": "PCI adapter",
"Tctl":{
"temp1_input": 38.875
}
}
}
```
If you specify multiple chips individually, you don't get valid json. …

lm_sensors: fix invalid json if specified more than one chip

---

py3status/modules/vpn_status.py

This commit adds the option to display IPv4 and IPv6 addresses of the VPNs in use (if using NetworkManager). I also added support for detecting OpenVPN VPNs because the connection type is `tun` (NetworkManager does not set the Vpn property to true for OpenVPN connections). I have found this change helpful to easily get my VPN IP when pen-testing.
There could be potential KeyError issues when attempting to retrieve the IP addresses, but I have not run into any problems with this.
In this change, I decided not to filter out when placeholders are None (likely for IPv6) and instead let the user decide to exclude them in the config (e.g. `format = "{name} [\?if=ipv6 {ipv6}]"`).

vpn_status: Add formatters for displaying IP addresses of VPNs

---

py3status/modules/conky.py

Hi,
The conky module seems to be broken for some time now.
I took a look at it and it seems some time in 2022 conky devs introduced a change in the text output when `out_to_x=false` that is used by the conky module, as mentioned in https://github.com/brndnmtthws/conky/issues/1479.
This means that there's an unexpected line in the process output that's breaking the formatting.

Workaround conky/issues/1479

---

py3status/modules/volume_status.py

Hi,
#2228 and #2230 introduced a regression in `volume_status` when using it with the default source.
Example configuration chunk :
```
order += "volume_status mic"
volume_status "mic" {
is_input = True
cache_timeout = 1
}
```
With this configuration, instead of selecting the default source, `volume_status` selects the default sink by calling `pamixer --allow-boost --get-mute --get-volume`
This PR adds `--default-source` to the command in case no device is specified and the option `is_input` is True.

fix volume_status for default source with pamixer

---

py3status/events.py

Users can use `OUTPUT`, `OUTPUT_PART` to do something useful with them. Sometimes, `OUTPART_PART` will include either leading or trailing whitespace because it's not the only composite. This just strips both of them off anyway. 
Solves https://github.com/ultrabug/py3status/issues/2243#issuecomment-2032012748.

events: strip whitespaces from OUTPUT, OUTPUT_PART

---

py3status/modules/playerctl.py

This is a dependency of the module and doesn't come with py3status by default. I used the same description as the usbguard module.

playerctl: Add python-gobject dependency

---

py3status/modules/mpris.py

To improve first user UX i decided to put chrome/chromium as default players to hide on idle status. (#2255)
Removed (experimental) feature flags because they are not so experimental anymore.
Corrected requirments list.

mpris module: improve documentation and set chrome and chromium as default player_hide_non_canplay value.

---

py3status/modules/external_script.py

Allow users to view plain output
Allow users to view formatted output.
Solves https://github.com/ultrabug/py3status/issues/2243#issuecomment-2346141610

external_script: add composite placeholder

---

py3status/modules/playerctl.py

Proposes improvement for issue #2255.

playerctl module: hide non-can-play players and use chrome and chromium as default value.

---

py3status/modules/playerctl.py

playerctl throwing error to console.
`PyGIWarning: Playerctl was imported without specifying a version first. Use gi.require_version('Playerctl', '2.0') before import to ensure that the right version gets loaded.
from gi.repository import GLib, Playerctl
`
Code is there but in wrong order because linter suggested other version.
This PR proposes fix for using lines in correct order by adding lint ignore statement.
Commit which made it broked: https://github.com/ultrabug/py3status/commit/3bc4946f6c60f066389ab72a62cc56e2d079f3ed and it was OK in original version.

playerctl: gi.require_version notification fix

---

py3status/argparsers.py

Adjust pgrep to look for i3-with-shmlog too.
Closes https://github.com/ultrabug/py3status/issues/2271.

argparsers: pgrep i3 with shmlog

---

py3status/modules/conky.py

This patch includes:
**Fixes for 2 problems:**
- Conky has a new output that should be ignored
In my case, with conky `1.21.7-pre-` (default version with latest Fedora) outputs `conky: 'i3' x11 session running 'i3' desktop`
- For some reason `NamedTemporaryFile` needs `delete_on_close=False` (which I thought was implied by `delete=False`, but apparantly that is not sufficient)
**A small refactor:**
- renamed `invalid_conky_errors` to  `ignored_conky_outputs` as they're actually just expected outputs that we don't care about (and not really a runtime problems requiring a warning/exit/exception)

fix tempfile and new output in conky module

---

py3status/modules/cmus.py
py3status/modules/deadbeef.py
py3status/modules/moc.py
py3status/modules/playerctl.py
py3status/modules/spotify.py
py3status/py3.py

An alternative to PRs listed below.
I copied `thresholds` code. Minimal test. Allow users to be more specific.
Get placeholders_list first so we can target existing placeholders rather than all placeholders.
I don't know if this PR is the optimal solution, just an alternative.
Code untested on this player.. I tested on `nvidia_smi`.  Sorry if you ran into issues.
This is just an idea / experiment.
Please test this.
```python
replacements = {
"artist": [
"([\(\[][^)\]]*?(bonus|demo|edit|explicit|extended|feat|mono|remaster|stereo|version)[^)\]]*?[\)\]])",
"([\-,;/])([^\-,;/])*(bonus|demo|edit|explicit|extended|feat|mono|remaster|stereo|version).*"
],
}
replacements = [
"([\(\[][^)\]]*?(bonus|demo|edit|explicit|extended|feat|mono|remaster|stereo|version)[^)\]]*?[\)\]])", …
```

py3: add new helper: get_replacements_list

---

tests/test_module_load.py

Stop the warning by removing `__init__` in favor of something like this or pytest fixture.
```python
PytestCollectionWarning: cannot collect test class 'TestModule'
because it has a __init__ constructor (from: tests/test_module_load.py)
class TestModule
```
EDIT: I can't verify using `self` or `cls`, but it doesn't look that important because of `assert` checking (approved) instance method, not variables.

stop warning py3status/tests/test_module_load.py:5

---

py3status/modules/whatismyip.py

Adding an example with url_geo choices... This ought to satisfy all parties.
Closes https://github.com/ultrabug/py3status/issues/2259
Closes https://github.com/ultrabug/py3status/issues/2260

whatismyip: add an example with more url_geo choices

---

py3status/modules/getjson.py

No need to add ip choices here. Updating out-of-date examples and defaulting example ip choice with `https`.

getjson: fix examples

---

py3status/modules/xsel.py

If `log_file` is `None`, then actual source will raise a `TypeError`:
``` 
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Fix TypeError on xsel module

---

py3status/modules/external_script.py

I had a need for an external script to specify not just the output color, but also whether or not the output should be "urgent".

external_script module: allow scripts to specify urgent
