py3status/__init__.py

The time/tztime handler currently only supports definitions with section names that match the exact string. I have two time definitions, ”tztime local” and ”tztime utc”; this fixes the section name detection to only use the first space-separated part to detect if the section defines a time segment.

Support time/tztime definitions with extra parts in the section name

---

py3status/modules/dpms.py

The DPMS module allows activation/deactivation of DPMS and does it well.
However, the purpose of deactivating DPMS is, in most cases, to avoid
the screen going blank. If the screensaver is not deactivated then the
screen will go blank anyway. This commits allow simultaneous
activation/deactivation of both.

[DPMS] Activate/deactivate the screensaver as well.

---

py3status/modules/keyboard_layout.py

The setxkbmap method assumes that the layout appears at the end of the "setxkbmap -query" command, which is not always true (e.g. options defined with "setxkbmap -option" may appear after the layout).
The module has been modified so it uses a regular expression for parsing.

[bugfix] incorrect parsing of "setxkbmap -query"

---

py3status/modules/bluetooth.py

* `separator`: the string separator that will be used between devices
* `format_prefix`: the prefix string that will be shown when there are active connections.
* `format`: the string that will be shown when there are active connections. Accepts the placeholders `{name}` and `{mac}`.
* `format_no_conn_prefix`: the prefix string that will be shown when there are no connections.
* `format_no_conn`: the string that will be shown if there are no connections.

[Bluetooth] configurable formatting

---

py3status/modules/spaceapi.py

Space APIs are not required to provide a 'lastchange' field. Spaces
without 'lastchange' timestamp will now always only show 'open' or
'closed' without a date.
Instead of PR #74

fix for Space APIs without 'lastchange' field

---

py3status/modules/imap.py

Returns sum of unseen mails in given folders. Former behaviour with only
one given directory is unchanged.
(I wanted the mail number to reflect a mailing list directory of mine, hence the change)

IMAP module may now check several IMAP folders

---

py3status/modules/imap.py
py3status/modules/spaceapi.py

Gives the user the choice of formatting the mail notification (including where to put the number of unread mails). Additionally provides the option to just not show the mail notification if there are no unread mails.
Default behaviour doesn't change.

Free output format for unread mails

---

py3status/modules/pomodoro.py

Display remaining time as a unicode progress bar.
2 alternative styles are supported and the number of bars can be configured by editing the script.
The braces around the timer change to show if the timer is running.

Pomodoro module: display time as a progress bar

---

py3status/modules/xrandr.py

using the --current option return the current screen configuration, without polling for hardware changes.

[FIX] retrieves the layout with polling for hardware changes

---

py3status/modules/empty_class.py

Maybe the example module should be moved to doc/examples/ to move it out the real modules directory and also make it easier to find for people looking at the docs.

Improve documentation in the example module

---

py3status/modules/player_control.py

A very simple module to control audio/video players. The user very rarely runs more than one player at the same time so guessing which player should be remotely-controlled on the fly sounds useful.
The first version supports audacious only.
I'd be happier if I could submit it under GPLv3.

Add player_control.py

---

py3status/modules/player_control.py

uses only dbus and communicates via the MPRIS MusicPlayer2 interface

VLC support for player_control

---

py3status/__init__.py

setproctitle is an optional dependency to set the process name.
The profiler can generate metrics for different threads and can be enabled using the enable_profiling  variable.

Add profiling support and setproctitle

---

py3status/modules/imap.py

When the **imap module** isn't able to connect to the mailbox through imap,
or when there is no unread email, the color is set like that :
response['color'] = ''
That makes the color black on i3bar, and thus invisible on most
backgrounds.
Removing these 2 lines makes it use the default color, which is white
and visible in most of the case. That also allow the "hide_if_zero"
module option to be useful !

imap module: fix empty color that made text invisible on i3bar when no unread email

---

py3status/modules/sysdata.py

In response to issue #98 - add format string support for the `sysdata` module.
I've also done a bunch of other (what I think to be) general cleanup, particularly no longer relying on the hard-coded `CPUTEMP` option (it now relies on the presence of the `{cpu_temp}` format string variable), the consolidation of the output into a single method (formatting now makes output easier to manage), and I've added or tweaked several docstrings.
My only point of concern, not being a particularly proficient Python programmer (my first Python code in many many years), which could be reviewed by someone with a bit more relevant experience, is the extraction of the CPU temperature within the `cpuTemp` method. It may be a bit amateurish, but it seems to work as expected :).
I actually feel like including …

add format string support for sysdata module, refactor and cleanup

---

py3status/modules/pomodoro.py

In python3 calling `encode` on a string will yield a `bytes` obj which
then leads to a status bar with escaped hex chars instead of the bars, i.e.
`Pomodoro [b'\xe2\x96\x89\xe2\x96\x89\xe2\x96\x8d ']` vs `Pomodoro [b'▉▉▍ ']`.
The fix in python2 is to call format on a `unicode` object vs a `str` (ansii)
object. This will work fine in python3 > 3.3 where the `u` prefix was brought
into python3.

pomodoro: fix display_bar in python3

---

py3status/modules/dpms.py

In response to issue #98 - add format string support for the `dpms` module.
Since it's going to be a bit more configurable with a `format` string, I added the placeholder, `{status}`, which allows customising the textual output based on DPMS state. I have not added this new parameter to the default string, to not confuse or surprise existing users.
Also added a little test which this module was lacking.

add format string support for dpms module, and add some options

---

py3status/__init__.py

Get rid of the old way of loading user modules and favour the new i3status `order +=` way instead.

Drop legacy modules loading

---

py3status/modules/pomodoro.py

Implemented the display_format option discussed in https://github.com/ultrabug/py3status/pull/120 
Allows any combination of bar, seconds, minutes or (hh:)mm:ss as display for the remaining time.

Module update: Additional display options for pomodoro.py timer

---

py3status/modules/spotify.py

This works for me for Spotify 1.0.16. But I'm a newbie when it comes to getting data from DBus so I'm not sure this is the right way. The DBus path shouldn't have changed this much, should it?

Update of spotify module for Spotify 1.0.16

---

py3status/modules/battery_level.py

Hello, I'd like to propose extending the `battery_level` module to allow using user-defined characters as blocks. This is especially beneficial when using icon font:
As you can see, I also made it possible to show percentage next to the icon.
Both settings are optional, and their default values are set to preserve the existing behavior -- so current users shouldn't notice any difference. 
This is the configuration that produces the screenshots above (it assumes the icon font to be installed and configured in `.i3/config`):
```
battery_level {
blocks = ""
charging_character = ""
show_percent_with_blocks = true
}
```

[battery_level] Allow user-defined blocks with percentage

---

py3status/__init__.py

Hi! 
At this moment such config parameters as ```separator = false``` converts to ```"separator": "false"``` when parsed, that is not a proper representation for a boolean variable in Python or in JSON.
This PR must fix it.

Proper parsing for boolean values in config

---

py3status/modules/battery_level.py

@ultrabug, as promised, here's an implementation for the uniform 'format' option in battery_level module. I've also refactored quite a bit and provided previously missing documentation for several options.
It should be fully backwards compatible, and all those compatibility rules are collected in one place for easier future reference.
Feedback is welcome :smiley: 
/link: #98
**UPDATE:** Forgot to mention, there's also one bug fixed while refactoring, so the behavior is *not exactly the same* as before. Previously `battery_full` variable was set to `False` and never updated, which means that `color_good` and `hide_when_full` parameters did nothing. Now this is fixed.

[battery_level] Uniformize and standardize 'format' option

---

py3status/modules/taskwarrior.py

I don't know for older versions, but the latest stable release (2.5.1) already
have '[' and ']' when doing an export. This lead to raising an exception
because it makes a nested list and you try to access it using a string
rather than an integer

Fix parsing of taskWarrior's output

---

py3status/modules/pomodoro.py

Hi,
Py3status imports all methods of a module except those starting with an
underscore and special methods. It then call these methods with self,
i3s_output_list and i3s_config.
Because of these rules, py3status call setup_mmss_time and setup_bar
with too many arguments, causing intrusive messages in logs. This PR 
fix this behaviour by adding an underscore before these methods' name.

Eliminate intrusive log messages from pomodoro's module

---

py3status/modules/xrandr.py

The xrandr module only has left-of and right-of positioning options right now as short inputs. I added 'below' and 'above' options with examples.

Added missing "above" and "below" positioning options.

---

py3status/modules/README.md
py3status/modules/wwan_status.py

Hello,
here's my first pull request. I hope you consider it useful because as of now only Huawei modems which understand the AT command I am using are supported. I tried to extend it to the Ericsson F3507g modem, but I could not verify that the AT commands I found actually return what I expect.
When reviewing, please keep an eye on the following things:
* I am new to Python. If I violated any conventions, just point it out and I'll fix it.
* I moved the main part of the documentation to the README.md file. Is this what it should be like?

wwan_status: A network connectivity status indicator for newer Huawei modems

---

py3status/modules/README.md
py3status/modules/battery_level.py

I've added dual battery support to the battery_level module.
The batteries can now either be displayed individually and selected through the battery_id parameter or combined into a single display (so % charge represents all batteries).
The on_click function didn't seem to work because self.time_remaining wasn't provided anywhere, so I wrote some code to extract time remaining from the acpi output.
This is my first code pull request and any suggestions on how to improve or simplify the code are super welcome.
Cheers.

Add dual battery support to battery_level

---

py3status/modules/battery_level.py

Hi,
I've implemented a custom format for the on_click notification of battery_level. You can also have different notifications when the computer is plugged or not.
I introduced a new placeholder, time_remaining, who was necessary to keep the same default notification as before.
I hope you like it !

battery_level: custom format for on_click notification

---

py3status/modules/scratchpad_async.py

Display the amount of windows and indicate urgency hints on scratchpad.
Makes use of i3 events to update asynchronously.

add scratchpad_async module

---

py3status/modules/spotify.py

Added option format_down which will be shown when spotify is not running.
This enables the user to define an empty string thus the element won't be shown in i3bar.
Currently there are not format strings supported as there are no useful data.

added format_down option

---

py3status/modules/README.md
py3status/modules/wifi.py

The reason for this module is that it works for some cards (at least `iwlwifi`) that do not work with the default wireless status in i3status. In addition, this module is more configurable.
i3status issue: https://github.com/i3/i3status/issues/106

Added module to display WiFi status using iw.

---

py3status/modules/battery_level.py

For me and maybe some other users the seconds a battery has left do not matter thus they can be removed.
Thus I added the option hide_seconds to control the visibility of seconds.
It defaults to False. If set to True seconds won't be shown.

added option hide_seconds

---

py3status/modules/spotify.py

A bug in the spotify linux client makes dbus run into a timout while
retrieving the PlaybackStatus. Song information are updated immediately.

Workaround, removed PlaybackStatus query

---

py3status/modules/arch_updates.py

Adds a module which displays the number of pending updates waiting to be applied/installed on an Arch Linux installation.  As Arch is a rolling-update distribution there are frequently many updates released over any 24-hour period so it's convenient for Arch i3-users (and there are many of them!) to have an easy way to see if they should be downloading and installing updates.

Arch status module

---

py3status/modules/spotify.py

- disabled PlaybackStatus code as it cannot be read using dbus (see
https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/DBus-MPRIS-interface-bug/td-p/1262889
)
- implemented (ugly) workaround code for stopped state
- code for paused state is still missing as there is no property
to track the current play status of a song
according to my tests only Metadata can be requested using dbus all 
other properties result in time-out
- fixed return of normal state
variable color does not exist
replaced it with self.color_playing and using color_good as fallback

fixed color & playbackstatus check

---

README.rst

- README.rst: mention py3status and py3status-git packages
Only one package on the 2 was mentionned, and there wasn't any mention of initial packagers for Arch Linux AUR. rst format is a pain btw :(

Doc: update Arch Linux AUR packaging infos

---

py3status/modules/battery_level.py

```
acpi -b -i
Battery 0: Unknown, 99%
```
if `format = "bat: {time_remaining}"` 
with master we see `bat: None`
this changes it to show `bat: ` which feels better to me.

Battery time remaining '' when unknown

---

py3status/core.py
py3status/events.py
py3status/module.py

**Issues addressed:**
1) I have a world clock user module.  With the current setup the time displayed is out of sync as it can take 1 second for the updated info to be used due to `sleep(self.config['interval'])`.
2) When clicking on a module it can take up to `config['interval']` for the result of the of the click to update eg `dpms`
3) Modules that have no update for long time periods eg `weather_yahoo` spend lots of time checking if they need to update when they don't need to (minor issue)
**This pull request allows these updates to be shown immediately**
I could change `config['interval']` but then my modules are working mainly doing nothing.
**changes:**
Instead of sleeping we use a timer to wake up and do the update when needed. Modules set their own timers. Triggering an update via …

Only update modules when they need to be

---

py3status/module.py

It seems some modules set a `cache_until` of `0` eg `window_title_async` 
This causes a delay of `config['cache_timeout']`
This patch makes the module update as soon as possible which is what the module is intending.

Bugfix: modules that set a cache_until of 0

---

py3status/module.py

This commit causes a nagbar when a module has an exception in a method.  It only does this once so as not to be too annoying.
It made the group issue easy to find and I think is probably good to have so that we are more aware of errors like that.

warn on first module Exception

---

py3status/core.py
py3status/i3status.py
py3status/module.py
py3status/modules/group.py

Hi,
This pull request does the following:
* move non `i3status` stuff out of `i3status.py` still more to be done.
* hopefully makes the code a little easier to  follow.
* adds a `check_update` helper to see when modules/i3status need updating.
* reduce the general cpu workload.
```
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
$ time timeout -sHUP 10m  py3status -c ~/.i3/i3status.conf > /dev/null
real	10m0.007s
user	0m7.822s
sys 	0m2.089s
$ git checkout speedy
Switched to branch 'speedy'
Your branch is up-to-date with 'origin/speedy'.
$ time timeout -sHUP 10m  py3status -c ~/.i3/i3status.conf > /dev/null
real	10m0.006s
user	0m4.967s
sys 	0m2.070s
```
Let me know any thoughts on this

'Speedy' branch

---

py3status/i3status.py

use `datetime.utcnow()` not `datetime.now()`

use utc not local time to get time offset fix #229

---

py3status/modules/group.py

If a group is empty we get a modulo zero error when it cycles.  This prevents this from happening.
example config to cause issue
```
group bad {
cycle = 1
}
```

prevent error when group is empty

---

py3status/modules/xrandr_rotate.py

Hey guys, I've got an idea of a module to rotate screen horizontally/vertically on a single click that I want to share with you. 
My main desire is: I want it to be **simple and intuitive**, which includes:
- As a user I see it behaving just like the `xrandr` module, in terms of selecting the rotation using mouse left click or wheel and applying the selected rotation using mouse right click.
- Even though there are four different rotations possible (normal, left, right, inverted), on a daily basis I want to think of my screen as either in "horizontal" or in "vertical" mode. Therefore the configuration parameters `horizontal_rotation` and `vertical_rotation` to choose the preferred rotation modes (clockwise or counter-clockwise).
-------
*The module looks like this with the default setup …

New module: xrandr_rotate

---

py3status/module.py
py3status/modules/bluetooth.py
py3status/modules/nvidia_temp.py
py3status/modules/static_string.py
py3status/modules/window_title_async.py

Introduce universal module options like [i3status](https://i3wm.org/i3status/manpage.html#_universal_module_options), which can be used in each module block. Some user modules already implemented this functionality themselves, but i think it is preferable to handle this once for all modules.
The first commits adds the two options ```min_width``` and ```align```, like with i3status. The second commit additionally adds ```separator``` and ```separator_block_width```, which are defined in the [i3bar protocol](https://i3wm.org/docs/i3bar-protocol.html#_blocks_in_detail).
I have updated the user modules accordingly, but two modules (bluetooth and nvidia-temp) already made use of the ```separator``` property for another purpose. So I renamed these two properties, which might break backwards …

Universal module options

---

py3status/modules/xrandr_rotate.py

Discovered a couple of small glitches, this is a fix for them.
Repro steps:
- set `screen` property to an output name that is not currently connected.
- set `hide_if_disconnected` to true.
- restart i3
Expected: icon will not show up
Actual: the module crashes, since `self.displayed` is not initialized but later is being accessed.
-----
And another super-tiny one:
- set `screen` property to an output name that is not currently connected.
- set `hide_if_disconnected` to true.
- while in H mode, left click to select V mode, but do not apply it
- disconnect the screen (icon hides)
- connect the screen (icon appears)
Expected: icon shows the current rotation of the screen (H)
Actual: icon remembers your choice and still shows V even though the screen is in H mode.

Fix not initialized 'displayed' field in xrandr_rotate

---

doc/example_module.py

PR #243 is a new module and appears to have been based off the example module in docs.  This is expected behaviour, but the example uses old style of docstring.
I have updated the docstring to the 'new' style.
I also added a format param and a placeholder as this feels like a good place to include them.  They feel like a py3status standard.

updates to example module

---

py3status/__init__.py
py3status/core.py
py3status/events.py
py3status/i3status.py
py3status/module.py
py3status/modules/group.py

In some ways this should be separate pull requests but there is some overlap.  I've tried to keep the commits independent, but they aren't quite.
What this does
**events**
* As shown by the group click events fun, the events logic in py3status is quite complex.  This patch moves the event processing out of the main loop into it's own function.  This allows events to be triggered on modules using the same code path.  The groups module may be the only user, other than the event loop, but it means that they will stay consistent if the logic is changed.  eg group clicks now use `i3bar_click_events.py` fallback .
**notify-send**
* `i3_nagbar()` is renamed to `notify_user()` all parameters stay as before.
* New `--dbus-notifications` option for `py3status` command if set this switches from …

Module helpers, notify-send and cleaner clicks

---

py3status/modules/xrandr_rotate.py

@maximbaz 
I have done some playing around and have managed to fix the issue that I was having with `xrandr_rotate`.  The fix is to run the command via `i3-msg` I'm not quite sure why this works but it does.
Could you see if it works for you too.
This fixes  #227 as far as I'm concerned, unless there have been other problems reported.  And we should remove the warning in the docstring too.

fix for xrandr_rotate issue

---

py3status/i3status.py
py3status/module.py

Make `Module` and `I3StatusModule` `__repr__` easier to read.  I've found this helpful for debugging and developing.
before
```
<py3status.i3status.I3statusModule instance at 0x7f785be571b8>
<Module(Thread-5, stopped 140154880657152)>
```
after
```
<I3statusModule ipv6>
<Module battery_level>
```

Add __repr__ to Module and I3StatusModule

---

py3status/core.py
py3status/module.py

Currently when a module raises an error we are just informed of the method and a vague error.
This PR improves on this situation.  We have more information on the error:
* filename
* instance
* line number
* exception type
This makes finding/fixing errors in modules much simpler.
The code is a little nasty with the `finally` but this is to prevent circular references https://docs.python.org/2/library/sys.html#sys.exc_info

Nice module errors

---

py3status/core.py
py3status/events.py
py3status/module.py

Renames `Module.clear_cache()` to `Module.force_update()`
This method now as well as clearing the cache sets a Timer to update the module.
Change py3status to only use this to force modules to update eg on click events.
As well as being cleaner it should fix #241 @neutronst4r could you see if this fixes your issue.  In my testing it works as expected.

nicer module updates fixes #241

---

py3status/__init__.py
py3status/core.py
py3status/module.py

Following on from the improved module errors.  This PR adds better information to exceptions that occur inside py3status.
Again we show `filename` and `line number` which really help with debugging issues.
```
self.config = {}
```
has been added just in case the exception happens before it has been set in `setup()`

show more info on errors

---

py3status/modules/sysdata.py

Fix cpuTemp breaking on python3 due to changes in subprocess.check_output().

Update sysdata for python3 compatibility

---

py3status/modules/fedora_updates.py

I was getting the odd error notification generally when restarting py3status.
This fixes the issue.
I also changed the cache timeout of the initial call as the update may as well happen immediately.

fedora_updates fix occassional error

---

py3status/core.py

I've had an issue where the reported exception was deep inside a python lib (subprocess).  Whilst this was a useful start, ultimately it was not what I wanted.  Ideally we only care about where the problem hits our code (inside py3status or in one of our modules 'py3status land').
This PR does some simple filtering of the stack to find where in py3status land the exception first hit.

report_exception() find first issue in py3status land

---

py3status/modules/xrandr.py

Implementing a way to make a user-defined list of output combinations to use, as discussed in #242.
Personally... it is *so much better* now! :smile: 
@mrt-prodz, @tobes, @ultrabug please have a look.

Add `output_combinations` parameter to xrandr module

---

py3status/modules/README.md
py3status/modules/volume_status.py

This PR adds volume control buttons to `volume_status`.
These buttons are disabled by default and must be enabled in the `i3status.conf` as many users already will have their own `on_click` defined.
I also cleaned up the docstring and removed the odd `transformed` thing.

Volume buttons for volume_status

---

py3status/__init__.py
py3status/core.py
py3status/module.py

There were some inconsistencies between messages to the user.  Having two routes `i3-nagbar` and `notify-send` made some of this more noticeable.
This cleans up the messages.
I'm not sure if it is still too complicated.  eg `notify_user()` wants a sentence `This is my error.` whereas `report_exception()` wants a fragment `Error happened`.  Maybe we should just add/remove any full stops so that the user does not need to care so much.
I'd be happy to add that, but it might limit us in some circumstances.

Notification message fixes

---

py3status/core.py

```
general {
output_format = "i3bar"
colors = true
interval = 5
}
order += "static_string"
static_string {
format = "hello world"
}
```
This simple config breaks py3status as no i3status modules are defined.
This PR fixes issue #261

Allow py3status to run with no defined i3status modules

---

py3status/module.py
py3status/modules/group.py

**This is outdated see comment below**
This PR follows on from discussions in issue #250  I'd like to thank @cornerman for the `self.py3` contribution.
What this PR does:
Any module that implements `class Meta` is treated specially.
* Calls to its `on_click` and update methods are called simply as `update()` and `on_click(event)` rather than the old style `update(i3s_output_list, i3s_config, event)` and `on_click(i3s_output_list, i3s_config, event)`.
* A special helper object is injected into the module as `self.py3`.  This helper module includes: 
-  helper functions:
- `notify_user()` send message to user.
- `get_module_info()` get info about other modules (`group` module  needs to do this).
- `trigger_event()` trigger an event for a module.
- `update()` force update of self or another …

Change to new calling and py3 object for modules

---

py3status/core.py
py3status/i3status.py

By default i3bar sends a -SIGSTOP to a process sending it data.  This causes
some modules interacting with i3 ipc to be suspended, which lead to locking
issues inside i3.  This patch switches to using SIGUSR2 as the suspend
signal.
The async modules eg window_title_async were affected.
see https://github.com/ultrabug/py3status/issues/253

Keep alive when i3bar hidden

---

py3status/modules/group.py

The groups module had a unicode issue and would fail under python2.
This resolves it.

allow groups to function with python2

---

py3status/core.py
py3status/i3status.py
py3status/module.py

This extends SIGUSR2 to sleep py3status modules.  We should really sleep when we have been told to.
When sleeping we stop the update timer.  On waking we reset the timer for the requested cache_until if in the future, else do an update immediately.
```
killall -USR2 py3status
killall -CONT py3status
```

Py3status sleep

---

py3status/module.py
py3status/py3.py

This PR moves the `Py3ModuleHelper` class into it's own file.  It also renames the class to `Py3`.
Reasoning:
* Seeing as it will be mainly known through the use of `self.py3` the class name is more intuitive.
* It is likely that the functionality of the class will expand.  This will help keep that cleaner and not confuse `module.py`.
* Other parts of py3status can import the class (or more importantly the defined constants).
Internally `class Py3` is unchanged.  A small spelling correction was made to `Module` docstring

Move Py3 to own file

---

py3status/modules/scratchpad_async.py
py3status/modules/window_title_async.py

Use the new py3 style for async modules to cache their responses forever and force an update as soon as an event was received.

cache async modules until event was received

---

py3status/module.py

on_click errors were not being shown to the user.  This corrects the issue.
Also better error info is provided

report on_click errors to user for py3status modules

---

py3status/core.py

When using dbus for non `info` non-string messages would fail eg `notify_user([1, 2, 3])`
This fixes the issue.

Allows non-strings to be notified on dbus

---

py3status/modules/spotify.py

This reverts commit 0f41e58099c7fc0da47f290c19e684ef923a9904.
Spotify fixed dbus playback status.

Revert "Workaround, removed PlaybackStatus query"

---

py3status/events.py
py3status/i3status.py

Whilst working on something different I was hit by a variation of issue #174 (i3status returning different name/instance than it was given).
This PR solves the issue in a simple way.  We ignore what i3status claims and just add the correct name/instance that are defined in `i3status.conf`.  The upshot of this is that the events are handled correctly too.
PS. Sorry I keep adding so many PRs

Correct i3status module names

---

py3status/i3status.py

We should not pass format_time to i3status time modules as we handle this in py3status
fixes #177

Do not send format_time to i3status time modules - fix #177

---

py3status/core.py
py3status/events.py
py3status/helpers.py
py3status/i3status.py

Currently `i3status.py` reads the input from `i3status` and then either outputs it to `i3bar` or passes it to `core.py`.
This commit allows `core.py` to do all the out bound communication.
The basic output to i3bar is a json stream starting with version info dict and then an array of arrays.  Before we needed to worry about if we needed a comma between the items etc and would look at the i3status output to determine this.
Now we just send our 'version dict' followed by opening the array and sending an empty initial array.  After that i3bar just expects `,[......]` for each line which is simple to provide.
In turn this simplifies `i3status.py` and we can also remove the `jsonify` helper
One additional advantage (and actually the reason I started this) is that we no longer output the first …

Core to do all i3bar output communication

---

py3status/events.py
py3status/module.py
py3status/modules/README.md
py3status/modules/group.py
py3status/modules/timer.py

This PR introduces composites, this was inspired by  #176 by @cornerman 
For full functionality i3bar 4.12 is needed but it will work (though degraded) for previous versions.
__What does this offer?__
* py3status treats a composite as it would any other normal module output (so can be added to groups etc).
* a modules response can be split into parts that together make a composite.
* each part of a composite can define it's own color.
* each part of a composite can catch it's own click events.
* the whole module can still catch events for any component part.
* `group` module now no longer conflicts with the click events of its contents
* `group` module can now be opened/closed to hide show its content.
__Demo__
The power of composites can be seen by adding the following to your …

Composites fun

---

py3status/i3status.py

This PR makes some changes to the generation of the `i3status.conf` created to send to `i3status`.
Changes:
* Instead of using the user provided `general` section we just create our own from a template `I3STATUS_CONF_GENERAL`.  (less likely to break i3status)
* The interval is from the users config if set, else `DEFAULT_I3STATUS_INTERVAL` is used.
* The config file is then created using `I3Status.config['i3s_modules']`.  Before `config['order']` and `config['.group_extras']` where used.  
`I3Status.set_responses()` uses `config['i3s_modules']` to work out the order of the i3status modules.  In the current setup this is fine because 
```config['order'] + config['.group_extras'] == config['i3s_modules']``` 
However this is almost by chance.  This corrects this issue.
The main reason for …

write_tmp_i3status_config() rewrite

---

py3status/core.py

This is just a nice bug fix when i3status chokes on say a bad config eg
```
general {
color = "#FF00FF"
}
```
This can wait for 3.1

[3.1] Do not die even if i3status has.

---

README.rst
py3status/core.py

This should be in the main readme
* add -b, --dbus-notify option to README.rst
* move option so they are alphabetical for `py3status -h`

move -b runtime option alphabetically and add to README.rst

---

py3status/module.py

You can't see it in the diff but this line is repeated just before the diff starts
```
self.module_full_name = module      <---- HERE
self.module_inst = ''.join(module.split(' ')[1:])
self.module_name = module.split(' ')[0]
self.new_update = False
self.module_full_name = module      <---- HERE
```

TRIVIAL: remove repeated line in module.py

---

py3status/docstrings.py
py3status/i3status.py
py3status/module.py
py3status/modules/arch_updates.py
py3status/modules/battery_level.py
py3status/modules/clementine.py
py3status/modules/dpms.py
py3status/modules/icinga2.py
py3status/modules/net_rate.py
py3status/modules/ns_checker.py
py3status/modules/nvidia_temp.py
py3status/modules/player_control.py
py3status/modules/spaceapi.py
py3status/modules/spotify.py
py3status/modules/sysdata.py
py3status/modules/vnstat.py
py3status/modules/window_title_async.py
py3status/modules/xrandr.py
py3status/modules/xrandr_rotate.py
setup.py
tox.ini

This PR fixes line lengths to the PEP8 recommended max length of 79.
I have tried to do it in a way that minimizes the changes and maintains readability (something that yapf often fails at imho)
There are a few places where some refactoring was needed ( `xrandr_rotate.py`) but again I've tried to avoid this where possible.

flake8 line length max 79

---

py3status/core.py

This fixes the XDG_CONFIG_HOME issue.
I'm not sure what other paths if any we want to add from that issue #204 
It looks like we cover all the i3status default locations https://i3wm.org/i3status/manpage.html#_options

fix XDG_CONFIG_HOME #204

---

py3status/modules/vpn_status.py

The main reason I started using py3status was that I use multiple VPNs while at home (one for school, one for work) and it would help to know which is enabled, rather than i3status's unhelpful yes or no output. So, I wrote a small module that replaces the default vpn pidfile watch that i3status uses.
The only improvement is to display the active vpn name, which is retrieved with python-NetworkManager (which is just a wrapper for dbus-python). Otherwise, it's a drop-in replacement; there's even an option to act just like i3status and check if the given pidfile exists.
I tried my best to meet the docstring format. Let me know if I missed something. My only real concern is that I don't know how it acts without NetworkManager or python-NetworkManager installed. It's not a large or complicated …

Proposed vpn_status module

---

py3status/modules/screenshot.py

Short version:
Adds the ability to configure what application is used to take the screenshot 
Longer version:
I do not use Gnome, and gnome-screenshot was not working for me when using the plugin. I like the idea behind the plugin, so I thought I would extend it to allow the screenshot command to be configurable.

add screenshot_command configuration option

---

py3status/module.py

With #302 the problem appears to be when we wake a module that does not have its cache_time set 
This PR checks for a cache_time value.

Do not set timer if no cache_time

---

py3status/core.py
py3status/i3status.py

Back to issue #302
It looks as though i3status dying kills py3status due to the main thread being killed when the i3status_thread stops.
This patch just restarts i3status if it is killed for whatever reason.  We only do this is i3status has actual worked correctly initially so faulty configs etc would still cause it to stop.

Restart i3status should it die

---

py3status/modules/README.md
py3status/modules/insync.py

@ultrabug I made a few updates to the insync module (I cannot test it though)  Sorry I should have done this on the pull request before but was waiting for a reply on the outstanding comments I'd made first. 
Anyhow I did the following
* some docstring tweaks
* use `insync` not `/usr/bin/insync` to allow more flexible binary location.
* use `decode()` not `str()` for python2 support (and related fixes)
* cache_timeout now `10` rather that `1`
* added to `modules\README.md`
@Cypher1 could you see if this functions as expected and let us know, Thanks

insync cleanups

---

py3status/modules/README.md
py3status/modules/github.py

Display Github notifications and issue/pull requests for a repo.
To check notifications a Github `username` and `personal access token` are
required.  You can create a personal access token at
https://github.com/settings/tokens The only `scope` needed is `notifications`,
which provides readonly access to notifications.
The Github API is rate limited so setting `cache_timeout` too small may cause
issues see https://developer.github.com/v3/#rate-limiting for details
Configuration parameters:
- `auth_token` Github personal access token, needed to check notifications
see above.
*(default None)*
- `button_notifications` Button that when clicked opens the notification page
on github.com. Setting to `0` disables.
*(default 1)*
- `cache_timeout` How often we refresh this module in seconds …

Github module

---

py3status/events.py
py3status/module.py
py3status/modules/github.py
py3status/py3.py

This PR does 3 things:
* Fixes issue with i3status modules not being updated on middle click.
* Simplifies `events.py`
* Adds `Py3.prevent_refresh()` that allows modules to prevent their `on_click` events causing a refresh.
The prevent_refresh functionality is for modules that do not need to update after the click event and have slow or resource intensive updates.  I can remove this functionality if not wanted but I think it is useful.

events: cleanup and bug fix

---

README.rst
py3status/core.py
py3status/events.py
py3status/i3status.py
py3status/module.py
py3status/modules/player_control.py
py3status/modules/pomodoro.py
py3status/modules/xrandr.py
py3status/py3.py

This is a first draft for some logging changes.  Hopefully this will make it easier to find and fix issue.
* `py3status --log-file /path/to/logfile` option to use that instead of syslog
* `Py3.log(message, level)` helper function, message can be str, list etc for debugging
* `Py3statusWrapper.report_exception()` adds extra traceback info if using custom logfile.
In the future I'd like to add some `LOG_WARNING` constants for py3status internal use but I'd like to do that after the config_parser branch is merged/scrapped. `Py3` supplies and uses constants.
It might also be nice if debug extra logging used `DEBUG` rather than `INFO` in logging

logging: log to file, Py3.log() etc

---

py3status/modules/sysdata.py

[PR 307](https://github.com/ultrabug/py3status/pull/307) should also remove the method `execCMD` as it's useless now.

Remove unused method

---

doc/README.md

Noticed that the examples got broken in a doc cleanup

docs: fix examples class name

---

py3status/modules/pomodoro.py

Added config parameter format_separator. By default it is '-' like 00-00.
Now you can set it to something like 00:00, 00x00.

pomodoro module: make clock more configurable

---

py3status/modules/battery_level.py
py3status/modules/pomodoro.py

Improve documentation for obsolete `mode` and `show_percent_with_blocks` parameters. Add new parameters for controlling how the battery level is decided to be bad, degraded, or good.

Tweak battery_level

---

py3status/modules/pomodoro.py

as defined by ISO8601
following issue #332

pomodoro module: Set default time separator to ":"

---

py3status/modules/github.py

When the number of notification was zero our notification count was not reset.  This fixes the issue so we now go to the correct url.

github module: fix button press issue due to notification count not being reset

---

doc/README.md
py3status/core.py
py3status/py3.py

Now that `core.notify_user()` does rate limiting (suppresses duplicates) `py3.notify_user()` does not show output when called if a message is a duplicate.
This is unhelpful for debugging and also it is reasonable for a module to display the same information to the user multiple times.  eg. Pomodoro time is up
This commit adds a rate_limit variable to allow notifications to now be rate limited.  It is set automatically in `py3.notify_user()` at 5 seconds.
It does not strictly limit the rate of duplicate messages but does prevent more than one being shown for every time period, this greatly simplifies things.
I use the hash function to just reduce the weight of our duplicate set.
`rate_limit` could be made available to users via `py3.notify_user()` in the future, or I can add now if wanted.

Stop notify_user rate limiting notifications from modules

---

py3status/module.py
py3status/module_test.py
py3status/modules/fedora_updates.py
py3status/modules/github.py
py3status/modules/group.py
py3status/modules/pomodoro.py
py3status/modules/scratchpad_async.py
py3status/modules/static_string.py
py3status/modules/timer.py
py3status/modules/twitch_streaming.py
py3status/modules/vpn_status.py
py3status/modules/window_title_async.py
py3status/py3.py

Here is the new module_test to allow for Py3.
I have put it in it's own file for clarity.  I also dropped the MockPy3 from my first attempt as it seems better if the actual Py3 is used.
I've updated all the modules using `py3`.  I also updated `fedora_updates.py` as a demo that it will work for any module.
`Py3` now also has a `i3s_config()` to get the i3s_config.
The module tester can be given a simple config which I've used in a few places eg `static_string`
I also corrected a python2 unicode issue in `scratchpad_async.py`
`vpn_status.py` is a slight pain as the keyboard interrupt doesn't work as it gets caught in the gtk loop rather than the module_test (still for now it is good enough and I've tried too hard to sort it for one day)
A few random other changes as I was in the modules eg …

Py3 testing framework

---

py3status/modules/volume_status.py

Muted channel now will display with "bad color" (with default thresholds)
Reason: muted state must be equal to zero-volume.

volume_status: color_bad for muted channel

---

py3status/i3status.py

This makes issues like #362 much easier to debug as we now report the line number and provide traceback in the logs.

Better logging/reporting of i3status errors

---

py3status/i3status.py

`i3status_pipe` was being initialised in the wrong class.

Fix issue #370 suspending i3status

---

py3status/__init__.py

This would help for issue #373 
Basically check for the locale independently
Check we have `py3` available when reporting errors

Better handling of init errors especially locale issues

---

doc/README.md
py3status/py3.py

Reviewing @fmorgner's PR made me realise that `Py3.safe_format()` could be improved by not using our own parser.

Improve parsing in safe_format()

---

py3status/i3status.py

This fixes the issue re i3status unicode and python2 #369

allow passing unicode to i3status

---

py3status/events.py

When events fail currently we do not receive a full traceback in the logs etc - this commit adds this it should help fix any event related problems.  A user notification is also triggered by this change when an event error occurs.
It is also possible that a 'corrupt' config can cause events to be triggered when they should not.  Basically if a container is defined but not actually added via order etc and it contains a module that is used elsewhere then an event for the non-setup container module is triggered.  This is an unlikely thing to happen but this just stops it if it does.

Events: Better errors and fix for non-displayed modules

---

py3status/core.py
py3status/events.py
py3status/i3status.py

This PR does the following
* Moves refreshing i3status into i3status.py as `I3status.refresh_i3status()`. Rather than being implemented in both in events.py and core.py.
* `Py3statusWrapper.refresh_modules()` can refresh all or named modules.  With named modules either an exact name or starting_with can be used.  `refresh_all` events now happen without needing to send a USR1 signal to py3status.  Events code changed to use this rather than re-implementing.
* `Events.dispatch_event()` Now handles the dispatching of events rather being done in `Events.run()` This allows events to come from other sources as well as i3bar.
The reasons for this PR are.
1. Cleans up some of the code and reduces repetition.
2. Allows for some cool future functionality I've been playing with to be introduced more …

Refactor events and module refresh

---

py3status/modules/README.md
py3status/modules/rainbow.py

This fixes the `<` being escaped to `&lt;` in the modules README.
Also proof of concept for pushing to your repo

fix issue with &gt; in modules docs

---

py3status/parse_config.py

Force modules.items() to a list so that we are not iterating it when it might change.
This was not needed for python 3.4/2.7 but was a problem in 3.5

Bug fix: parse_config for python 3.5

---

py3status/i3status.py

There was an issue after the sleeping dogs branch was merged that affected the output from a group.  A time module in the group would not be updated regularly.
This was because i3status time modules do not always create a fresh response and therefore they corrupted the module updated checks in module.py (the time would be updated and this would end up updating the last_output - so it looked like the output hadn't changed)

Bug Fix: ensure that last_output remains correct

---

py3status/module.py

In PR #354 mpris module the output wants to be colored but currently there is no easy way to do this.
This PR allows composites to provide a color
```
{
'cached_until': ...,
'color': <color>,
'composite': [
{.....},
{.....},
]
}
```
The color will be added to any of the parts of the composite that do not supply color themselves.
It needs documenting but since #393 adds composite documentation. I'll add it in either this PR or that one depending which gets merged first.

Pass color to composite parts

---

py3status/parse_config.py

#387 includes a report of an issue with an empty config.  This prevents that error and notifies the user that no modules are present.  I'm not sure if the notification is the best.  really we are sayingthat there are none defined in `order +=...`

warn user on empty config

---

py3status/core.py

Module import errors were not very informative.
This PR adds better logging of exceptions.
It also adds `level` parameter to `report_exception()` to allow error level to be passed.

Improved reporting of module import errors

---

py3status/constants.py
py3status/parse_config.py

If we have the following i3status.conf.  
```
order += "static_string"
order += "group"
static_string {
format = 'one'
}
group {
static_string {
format = 'two'
}
static_string {
format = 'three'
}
}
```
Then currently, only one static_string module is created even though three have been defined.  This PR instead treats this as three independent modules.  It does this by creating a unique name for modules defined inside a container.  This allow them to be distinguished between and so be initialised with the correct values.

Anon modules: less module clashes in containers

---

py3status/modules/group.py

Due to how modules were started the group module had to be sure that all modules were initialised before it could produce the correct output.  Since PR #276 all modules are now initialised before any are run so we no longer need this behaviour.

Group module minor update

---

doc/README.md

Make module examples use `py3.format_safe()`
Also add initial documentation on composite responses

Documentation update example modules improvements and composites

---

doc/README.md
py3status/core.py
py3status/py3.py

Both `py3.notify_user()` and `py3.log()` suffered issues when being sent a unicode string under python2.
This PR fixes the issue so that they are both much more forgiving about the strings they will accept.

Bug Fix: py3 python2 unicode fixes for notify_user() and log()

---

doc/README.md
py3status/core.py
py3status/module.py

* Add `init()` support for modules.
* Fixes containers so that `self.items` is always available.  This makes things easier for initialising containers as we do not need to check if self.items is defined for the module it will just be an empty list.
* Adds documentation on module methods/responses (think of this as a bribe)
Due to how py3status modules are loaded their `__init__()` is called before any configuration parameters have been set.  It is often useful to run code just once when the module has been configured.
To achieve this I have often written code like this 
```
def __init__(self):
self._initialized = False
def _init(self):
... run initialization code here ...
self._initialized = True
def module_method(self):
if not self._initialized:
self._init()
... run module code here ... …
```

Module init() method

---

doc/README.md
py3status/module_test.py
py3status/modules/check_tcp.py
py3status/py3.py

* `safe_format()` now can get placeholders straight from the py3status module (ignores any methods)
* `\?` special escape char added for the future
* Works with module stand alone test
* docs updated to reflect changes

safe_format() get attributes from module

---

py3status/parse_config.py

Fixed the unknown encoding "binary" exception that occurred, if the config-file happened to be a symbolic link on linux.

Fixed exception if config-file is a symlink

---

py3status/modules/exchange_rate.py

When a single currency is used in the format string, this module failed on line
68 since Yahooapis does not return single currency as a one element list, but
the element (dictionary) itself.
Solution: check if the expected element is a list or not.

Fix exchange_rate module when single currency is used

---

py3status/modules/glpi.py

This module used `i3s_config['colors']` to decide if colors should be enabled (undocumented).
This removes that logic.  As in #410 if we want this as a feature we should add it universally.

Color updates: glpi

---

py3status/modules/kdeconnector.py

Color update
This module was using `i3s_config['interval']` for its timeout.
This adds `cache_timeout` param like other modules

Color update: kdeconnector

---

py3status/formatter.py
py3status/py3.py

So `_safe_format()` had a few issues where it didn't behave as i would have liked.
eg `'{empty}|nothing here'` would return `''` rather than `'nothing here'`
Additionally the code was starting to become quite hard to read, possibly buggy, and prevented expansion of new ideas eg block commands things like `[\?max_length=10 {file-name}]` `[\?if=param Hello]`
Anyhow I have written a formatter it uses a simple parser similar to the config parser.  It also makes py3.py much shorter and easier to read.
Plus it has tests `python formatter.py`
I think seeing as we are going to shift modules to safe_format() that having a solid implementation is an improvement.

Improved formatter

---

doc/README.md
py3status/core.py
py3status/modules/frame.py
py3status/modules/group.py
py3status/py3.py

The frame module.  This allow modules to be grouped.  This is useful if you wish to add more than one module to a 'slot' in a group.
```
group {
frame {
volume_status {}
battery_level {}
}
time {}
}
```

Add module frame

---

doc/README.md
py3status/parse_config.py
py3status/private.py

From #415 this adds universal base64 encoding via
```
module {
value:base64 = '<encoded>'
}
```
@ultrabug if you are happy with this concept I'll update this PR with some documentation

Allow password encodings in config

---

py3status/modules/frame.py

This PR removes the additional separator that were added at the end of frames. This is only if "separator" is set. If this was an expected behaviour, I'll add an option to remove it.

Remove additional separator at the end of frames

---

py3status/modules/weather_yahoo.py

I get errors like this periodically with weather_yahoo module
```
2016-08-29 02:00:22 WARNING Instance `weather_yahoo _anon_module_2`, user method `weather_yahoo` failed (TypeError) weather_yahoo.py line 93.
2016-08-29 02:00:22 INFO Traceback
TypeError: 'NoneType' object has no attribute '__getitem__'
File "/home/toby/dev/py3status/py3status/module.py", line 419, in run
File "/home/toby/dev/py3status/py3status/modules/weather_yahoo.py", line 153, in weather_yahoo
today, forecasts = self._get_forecast()
File "/home/toby/dev/py3status/py3status/modules/weather_yahoo.py", line 93, in _get_forecast
today = r['query']['results']['channel']['item']['condition']
```
This just catches that and behaves as if there was a connection or other error

Bugfix: weather_yahoo TypeError

---

py3status/formatter.py

fixes #448 where zero was not displayed.  Now a value of zero is treated as being a valid value. False, '', None are treated as non-valid.  This make more sense.  Extra tests added around this.

Formatter bug fix for zero

---

py3status/core.py
py3status/docstrings.py

When using `py3status docstring check` allow modules to be specified eg  `py3status docstring check xrandr`

py3status docstrings: Allow checking docstring for specific modules

---

py3status/modules/kdeconnector.py

If notifications are disabled via  `kcmshell5 kcm_kdeconnect` then we get the following error.
```
TypeError: 'NoneType' object is not subscriptable
File "/home/toby/dev/py3status/py3status/module.py", line 419, in run
File "/home/toby/dev/py3status/py3status/modules/kdeconnector.py", line 221, in kdeconnector
(text, color) = self._get_text()
File "/home/toby/dev/py3status/py3status/modules/kdeconnector.py", line 208, in _get_text
(notif_size, notif_status) = self._get_notifications_status(notif)
File "/home/toby/dev/py3status/py3status/modules/kdeconnector.py", line 187, in _get_notifications_status
size = len(notifications['activeNotifications'])
```
This is a simple fix for that

kdeconnector: fix for notifications not available

---

py3status/formatter.py

This is for a bug in the formatter.  When we had a format like `'{composite}  [{placeholder}]'` the placeholder would end up being converted into a `{'full_text':...}` item too early in the processing, it should only be converted to this form in the final block (the one with no parent).
I've added a test for this case.

Bugfix formatter composites error

---

py3status/modules/kdeconnector.py

When connecting to a reachable but unpaired device d-bus device['isPaired'] is actually a method so should be called as the function definition is treated as a truth.  This is quite hard to hit.
@ritze can you confirm this is good for your setup, I've done quite a bit of playing and this seems robust.

kdeconnect device is paired error

---

py3status/core.py

reported on IRC
@Lujeni was affected also and found the problem and this patch.
I'm doing the PR since he's busy and I'd like 3.1 out.

fix log exception when message contains special characters, by @Lujeni

---

py3status/i3status.py

On rare occasions I've had this error.  I'm not sure quite what causes it but this patch will stop the error.
```
IndexError: list index out of range
File "/home/toby/dev/py3status/py3status/i3status.py", line 349, in spawn_i3status
self.set_responses(json_list)
File "/home/toby/dev/py3status/py3status/i3status.py", line 227, in set_responses
if self.i3modules[conf_name].update_from_item(item):
File "/home/toby/dev/py3status/py3status/i3status.py", line 105, in update_from_item
self.set_time_zone()
File "/home/toby/dev/py3status/py3status/i3status.py", line 143, in set_time_zone
i3s_time_tz = parts[2]
```

Fix for occassional timezone bug

---

py3status/core.py
py3status/module.py
py3status/modules/group.py

Because the `post_config_hook()` was run when a module started, it was possible for content of groups to be updated and trigger an update of the group before the group had its `post_config_hook()` run.
This PR ensures that all modules have their `post_config_hook()` run before any modules are started.
This also updates group module to use post_config_hook()

Run all post config hooks before starting any modules

---

py3status/modules/bluetooth.py

'hcitool con' displays master/slave connections as separate entitites.
This results in the same bluetooth connection being reported twice.

Fix issue where duplicate bluetooth connections are shown

---

py3status/modules/kdeconnector.py

`isPaired` is deprecated and module doesn't work anymore with the new kdeconnector version.

kdeconnector: API fix

---

py3status/modules/xrandr_rotate.py
py3status/modules/yandexdisk_status.py

`self.format` is a string that needs to be passed into `safe_format()`, not `self.format.format`, which is a function.

Fix safe format refactoring regressions

---

py3status/modules/README.md
py3status/modules/process_status.py

allow for --full search of a procress. Original users will see no difference, but you can now pgrep for things like "ssh 10.*"

Process status

---

doc/README.md
py3status/core.py
py3status/module.py
py3status/modules/group.py
py3status/py3.py

This implements #469
`Py3.register_content_function()` has now been replaced with a more general `Py3.register_function()` and it is now documented.

Groups switch to urgent items

---

py3status/modules/backlight.py
py3status/modules/process_status.py
py3status/modules/scratchpad_async.py
tests/test_module_doc.py

This PR adds testing of docstrings.
We check that 
* docstring contains all the config options the module provides.
* correct default values are given
* config parameters listed in alphabetical order
Some modules have odd defaults eg `save_path` in `screenshot` module these are excluded from the tests.
Some modules cannot be imported due to missing dependencies eg `aws_bill` these are currently excluded but if we agree the proposal in #482 then we could also test these modules.
As well as ensuring more accurate docstrings this PR will help ensure new modules are correctly documented.
Also included are some fixes for existing modules to pass the tests

Tests: module docstrings

---

py3status/module_test.py

running `python2 modules/volume_status.py` would crash 
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u266a' in position 0: ordinal not in range(128)
```
This fixes the issue by using repr not str to test if attribute is a method.

Bugfix: module_test unicode issue

---

py3status/core.py
py3status/modules/battery_level.py

Module battery_level.py lines 343 and 350 raise an AttributeError when the Py3status class is instantiated and the battery is below either threshold. 
The self.last_known_status variable isn't declared yet so the threshold conditionals fail. Otherwise if the battery starts above the threshold and drops below it, the error is avoided.
Declaring last_known_status = '' at the top of Py3status fixes the problem.
A subprocess.call() to notify-send on lines 159 and 364 of battery_level.py raises a FileNotFoundError (python3.5) when libnotify is not installed. Neither libnotify nor dunst is listed in the module requirements.
The module should probably use the py3status notify_user() method so people can utilize the -b flag.

battery_level.py recommended changes

---

py3status/modules/fedora_updates.py

Commit adds option `check_security` to be able to ignore info about
security fixes. It's useful info, but
* not everyone is interesting in it (e.g. when running update everytime
he/she sees a number > 0 :))
* `dnf updateinfo` reads from external sources, which can be
time and CPU consuming
The option is enabled by default because of backwards compatibility.

fedora_updates: Add option for checking security updates

---

py3status/modules/github.py

If you are monitoring all notifications, but there are none, a click on
the module took you to the repo page (which would probably be
unconfigured). Now it will take you to the GitHub homepage (since the
empty notification page would be kind of useless).

Don't go to repo when notifications == 'all'

---

py3status/modules/volume_status.py

Adds a new variable `backend` which can be either "alsa" or "pulseaudio". Adding other backend is only a matter of creating a wrapper class which extends the abstract `AudioBackend` class. If the backend specified doesn't exist, an exception is raised in the `post_config_hook`. This stops py3status.
In addition, I added a new variable to optionally color the `format_muted` string depending on the volume. I use it to know if it's safe to unmute.

Add pulseaudio support to volume_status

---

py3status/modules/battery_level.py

Instead of checking `self.charging`, the code was checking `self.time_remaining`. Since `self.time_remaining` is always a non-empty String (even in case of error, where you would get a `?` instead of None or something else), this check always evaluated to true and `self.format_notify_charging` was never used.
Fix issue #509

on_click() logic fix

---

py3status/modules/glpi.py

Setting default cache_timeout to 5 minutes.
Resolves: #497

GLPI: Add cache_timeout

---

py3status/modules/ns_checker.py

Adding format and cache_timeout to the `ns_checker` module.
@tobes: I have a few of these coming, should I put multiple modules in the same PR?  or would you rather have a PR for each module? (I'm not sure of the entire code review process here)
I ask, because I did some major refactoring, along with adding `format`, in another module (`rate_counter`) and felt that that one should be separate.
Working towards #98

ns_checker: Add format and cache_timeout

---

py3status/formatter.py
tests/test_formatter.py

Testing the battery_level changes led to an error in the formatter.
`0.0` was not displayed as it is treated as False.  This PR treats `0.0` as a valid value to display.  The test looks odd due to how python treats False as a number.  A test has also been added for this behaviour.

Formatter bugfix display 0.0

---

doc/README.md
py3status/py3.py

Running commands and getting output of commands is a common task in modules.  This PR adds some helper functions to Py3 to make this easier and use common methodology.
`command_run()` is similar to `subprocess.call()`
`command_output()` is similar to `subprocess.check_output()`
* commands can either be called as a string eg `'acpi -i -b'` or as a sequence eg `['acpi', '-b', '-i']`
* output from commands is suppressed as needed (command_run).
* output is converted to unicode.
* universal newlines in output
This should make using commands easier for module writers

Py3: add command_run() and command_output() helpers

---

py3status/i3status.py

There were some bugs in the i3status module around handling times.
1) Sometimes the module was not updated when it should have been.  This occurs when py3status is first started and the modules time format is the default.  The module can take several seconds to appear.  We now update as required.
2)  The logic for recreating the Tz timezones once a minute was incorrect and we were regenerating them every second.

i3status time modules fix

---

py3status/modules/README.md
py3status/modules/battery_level.py

Implement measurement of battery information using `/sys/class/power_supply` provided by the kernel itself instead of acpi. More robust, however it may give a wonky time measurement and may not work in all cases, for example this one: https://bbs.archlinux.org/viewtopic.php?id=131025

Battery measurement using sys interface

---

py3status/core.py

I found an issue where i3status modules are in containers and try to update the container module before it has had its post_config_hook() called.
This PR prevents this from happening

Don't call updates on modules before they have been fully initialised

---

doc/README.md
py3status/composite.py
py3status/formatter.py
py3status/module.py
py3status/py3.py
tests/test_composite.py
tests/test_formatter.py

Updates to the formatter.
* Composites in the formatter now return a `Composite` object rather than a list (if a composite is created eg when `\?color=XXX` is used in a format string).  This allows us to add composites via `param_dict`.
* A `Composite` is basically a wrapped list but allows us to know that it is a composite rather than just a list.  It also allows easier appending/creating as it understands strings, lists, dicts and Composites.  It also has some helper functions.
* Seeing as how `safe_format()` can return a `Composite` and add them via `param_dict` there is less need for `build_composite()` so it can be deprecated.
* `safe_format()` can be forced to return a composite.  This is helpful if the module will manipulate the result etc.
* `composite_join()`, …

Formatter and Composite updates

---

doc/README.md
py3status/formatter.py
py3status/modules/volume_status.py
py3status/py3.py
tests/test_module_doc.py

Following my plans set out in issue #451 here is an implementation of thresholds.
* `threshold_check()` function added to Py3.  This both returns the correct threshold color for a value but also sets the color for use in formatting.
* Threshold colors added to module as `color_threshold` accessed as `threshold` or as `color_threshold_<name>` accessed as `<name>` this makes things easy for the user whilst reducing the likelihood of accidentally overwriting variables. 
* single or multiple thresholds can be easily defined.
* thresholds can now have as many steps as the user wishes to define as opposed to just the ones of the module writer.
* Some basic documentation added.
* volume_status module updated as an example.

Thresholds

---

doc/README.md
py3status/core.py
py3status/module.py
py3status/module_test.py
py3status/modules/volume_status.py
py3status/py3.py

This PR adds extra functionality to dealing with colors and demonstrates this in the volume_status module.
In a module a common usecase is
`color = self.py3.COLOR_MUTED or self.py3.COLOR_BAD`
We would expect color to be `color_bad` if `color_muted` is not in the config and this is how things currently are.  However if `color_muted = None` then I think that this should be respected and color should be `None`.
To enable this we have to know if `color_muted` is actually defined in the config or not.  This PR uses class `NoneColor` to help.  We also add `Py3.is_color()` helper function.
Module volume_status is updated:
1) volume_muted not in config (default behavior muted is color_bad)
2) `volume_muted = '#FF00FF'` the specified color is used when muted
3) `volume_muted = None` When muted the …

Allow None colors and use in volume_status color_mute

---

tests/test_module_doc.py

I simplified `RE_PARAM` to
```
RE_PARAM = re.compile(
'^  - `(?P<name>[^`]*)`.*?('
'\*\(default (?P<value>('
'.*'
'))\)\*)?$'
)
```
And it seems to work for all the tests. If it is now too broad (and matches things it shouldn't), I can restrict it a bit, but this allows for nested tuples and everything. And even if it matches things it shouldn't (like unmatched quotes), that should be caught by the eval.

Add tuples support to doc checker

---

doc/README.md
py3status/py3.py
tests/test_py3.py

This adds a helper function to py3
The idea is to create human readable output for modules like sysdata it also means we have one true implementation and so should be less subject to errors etc.  We can force the output if needed say to MiB or we can use something like 'bits/second' and get Mibits/second etc.
The output is a numeric (so users can format in their format strings) and a unit.
I think this would be a useful helper for various modules that need this functionality.
some examples
```
format_units(1024) ->  (1.0, 'KiB')
format_units(1024 * 1024) ->  (1.0, 'MiB')
format_units(1024 * 1024, unit='KiB') ->  (1024, 'KiB')
format_units(1024, unit='b/sec') ->  (1.0, 'Kib/sec')
```
It also adds some tests

Py3: helper function format_units()

---

doc/README.md
py3status/formatter.py
py3status/py3.py
tests/test_formatter.py

Issue #484 really needs mpd_status to be updated to use safe_format().  The issue with this is that the module gets information (placeholders) via a function, rather than providing a dict like most modules.  This could also potentially be useful for other modules.
This PR adds the ability to provide an attr_getter function to safe_format() that values will be got from.  This functionality is also available via build_composite().
If this PR is merged we can then update mpd_status to use safe_format().  We can add a shim to the module so that both `%...%` and `{...}` formats can still be used.

Formatter add attr_getter

---

py3status/formatter.py
tests/test_formatter.py

This PR is  another cleanup/refactor of the formatter code.  The main change is that we now treat everything as a Composite so don't have to worry whether items are Composites or not.  This massively simplifies things.
The behaviour is pretty much the same, as can be seen one, of the tests has changed as we still return a simple string as output to safe_format() if we can, and for that test a string could be returned rather than a Composite.
Due to the tests I'm fairly confident that we won't be breaking stuff.
Now the main reason I've done this is that it made it easier to add a new command `min_length` it pads things to a size. eg `format = 'net0: [\?min_length=9 {total} {unit}]'` so the module outputs don't jump about as the output changes.  This is something I'd discussed with …

formatter cleanup and new min_length command

---

py3status/py3.py

that did throw an 'invalid format' on the bar when using group !

fix py3 call to formatter passing an unexistent 'composites' key

---

py3status/modules/vpn_status.py

because it should depends on OS setting, not to have harcoded usage
of python3 via env.
Uncovered by rpmlint while building package for Fedora.

vpn_status: remove shebang

---

py3status/docstrings.py

Only add `*` around the default value if it's single line (ends with a `)`)

Multi-line default values don't end with ')'

---

py3status/core.py

By moving the sleep from the end of the main loop to the beginning we allow more modules to have provided output when we first display.  This makes the initial display when we Mod+Shift+R etc much smoother.

Move sleep to start of main loop in core.py

---

doc/README.md
py3status/module.py
py3status/modules/battery_level.py
py3status/modules/file_status.py
py3status/modules/spaceapi.py
py3status/modules/volume_status.py
tests/test_module_doc.py

Currently we have modules that have a variety of configuration parameters that follow different standards.  It would be nice to have consistency in module parameter names eg `format_xx` for format strings, thresholds etc.  This PR allows us to change module configuations.
* Existing configuration files will continue to work for the user.
* If users set parameters they will not be overwritten, although they may be corrected (currently only {} being updated).
* Reduce the complication of code modules have dealing with legacy config options, eg battery_level has an obsolete `mode` parameter.
* Allow updated configurations to be applied to modules as though they were the user supplied ones eg colors will be available via `py3.COLOR_XXX`
* Deprecations across all modules are dealt with the …

Universal module config parameter deprecation

---

doc/README.md
py3status/events.py

#502 (copying module output to the clipboard) was an interesting idea.
So I've come up with a way that we can do this.  The idea is to be flexible so users can find their own uses for this.
With this PR I can now copy the output of a module to the clipboard on a left click
```
my module {
on_click 1 = 'exec echo $OUTPUT | xclip -i'
}
```
Where `$OUTPUT` will be replaced by the output of the module.  `$OUTPUT_PART` will give part of the output if the module is a composite.  I'm quite happy to change the names for these substitutions if people can think of better ones.
In the future we could also extend this to get variables out of the module eg the output filename from screenshot module so a little thought around the naming for that might be nice too.

Allow module output to be used in commands

---

tests/test_module_doc.py

Fix small typo in `test/test_module_doc.py`

Fix typo for OBSOLETE_PARAM

---

py3status/modules/sysdata.py
tests/test_module_doc.py

Try to use the new Meta/deprecated function for deprecated config args. Tox doesn't like it.

Use new Meta/deprecate_function in sysdata

---

py3status/modules/vnstat.py

An old patch I found. vnstat module had some unused variables.

vnstat remove unused vars

---

py3status/modules/sysdata.py

As discussed in #553, this uses better defaults for sysdata by separating the colors for cpu and memory.

Better default colors for sysdata

---

py3status/core.py

When looking in py3status logs it can be hard to tell what version of py3status was running.  this PR adds a few extra lines to the logging.  The git lines are only shown if running in a git repo
```
2016-11-06 20:45:06 INFO ========
2016-11-06 20:45:06 INFO Starting py3status version 3.3rc0 python 3.5.2
2016-11-06 20:45:06 INFO git: branch log-extra-info
2016-11-06 20:45:06 INFO git: dcf3661 Merge pull request #556 from ultrabug/modfix-3.1-vnstat
```

Log py3status/python versions and git info

---

doc/README.md
py3status/formatter.py
py3status/modules/sysdata.py
py3status/py3.py
tests/test_formatter.py

So @guiniol has been doing things with sysdata and I was doing some testing of #555 and I was finding it a little frustrating.  If I wanted to do custom formatting of say `{cpu_usage}` then the formatting was done in `format_percent` which I understand from the developer perspective but from the users perspective this is confusing in my mind.  I should be able to do `format = '{cpu_usage:.0f}'` and it should work.  But as `{cpu_usage}` is a string even though it looks like a number this fails.
So anyhow I've made this so it now works.  If we have a value that could be numeric and is having numeric formatting applied it will now work.  It also means we can do `{cpu_usage:.0f}` on a string.  we also can do `{cpu_usage:d}` on a float/string as a quick 'make this an int' shortcut.
These …

Formatter: Allow formatting numeric strings

---

doc/README.md
py3status/module.py

In a module like sysdata we have placeholders eg `{cpu_usage}` this ends up
having a value something like `20.542317173377157` which is strange as the
value to use but gives the user the ability to have as much precision as they
want. A module writer may decide that they want this displayed as `20.54` so
`{cpu_usage:.2f}` would do this. Having a default format containing that
just looks long/silly and the user setting a custom format just wants to do
`format = 'CPU: {cpu_usage}%'` and get expected results ie not the full
precision. If they don't like the default formatting of the number they could
still do format = 'CPU: {cpu_usage:d}%' etc.
So using this allows sensible defaults formatting and allows simple
placeholders for user configurations.
There are also a few minor cosmetic …

Allow updating of placeholder formatting of modules

---

py3status/modules/fedora_updates.py

Minor update.
Fixes issue when some packages are updated but some are still outstanding.  In this situation we now recheck if some updates are security related.

fedora_updates redo security check when number of updates decreases

---

py3status/core.py

This PR makes dicts, lists, sets and tuples more readable in the logfile by formatting them using `pprint.pformat()`.  It does not change the syslog output if that is used.

Use pretty printing in logs for data structures

---

py3status/i3status.py

Fixes bug where unicode format strings killed time/tztime

Fix python2 unicode use in i3status time modules

---

py3status/formatter.py
tests/test_formatter.py

It seems a common usecase to not want to show format placeholders when the value is 0 eg number of notifications.
Currently this is possible but a bit verbose `format = '[\?if=value {value}]'` this PR adds a format command to make this `format = '[\?not_zero {value}]'` that makes things more readable it also will treat strings like `'0'` and `'0.0'` as zero values, which feels like it makes sense as we allow these to be formatted as numbers.

new not_zero format command

---

py3status/modules/battery_level.py

When a value of zero was obtained we could end up with a value of None. This fixes the issue
```
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
File "/home/toby/dev/py3status/py3status/module.py", line 584, in run
File "/home/toby/dev/py3status/py3status/modules/battery_level.py", line 174, in battery_level
self._refresh_battery_info()
File "/home/toby/dev/py3status/py3status/modules/battery_level.py", line 316, in _refresh_battery_info
battery_list = self._extract_battery_information_from_sys()
File "/home/toby/dev/py3status/py3status/modules/battery_level.py", line 294, in _extract_battery_information_from_sys
time_in_secs = (remaining_energy / present_rate * 3600)
```

Battery_level: Prevent logic issues when zero

---

py3status/modules/volume_status.py

the volume_status module's PactlBackend regex was hardcoded for sink #0 , now the regex uses self.device
I ran into the error because my computer has two output devices (HDMI=0, Stereo=1).

volume_status PactlBackend does not read user-specified device

---

py3status/modules/sysdata.py

It doesn't make sense to use "high" as a default color, there is no such color in py3status and without extra configuration it won't be colorized at all. It should have been "bad", which is rendered as red.
Also see line 176 which shows that the default value is "bad" for those who still use the obsolete way of configuring thresholds.

Use color 'bad' instead of 'high' as a default threshold in sysdata

---

py3status/modules/backlight.py
py3status/modules/battery_level.py

Quick fixes for battery and backlight displays (in particular fixes #557):
- Battery module failed when running on a computer without a battery
- Backlight module failed when running on a computer with a monitor that can't have its brightness adjusted.

No device fix

---

.gitignore
py3status/modules/do_not_disturb.py

This module has a very simple idea behind it: to be able to turn on and off all the notifications in the system with a single click.
This is easy to achieve if all potentially distracting apps (like email, chat, etc.) use native system notifications rather than their own implementations. This module assumes such setup :wink: 
All the notifications are enabled:
Need to focus? A single mouse click disables the all system notifications:
Done working? A single mouse click, and you have all your notifications back:
I couldn't figure out a smart way to disable notifications, that would work with all available notification managers. But I saw that many people suggest having a shell script that periodically kills the manager's process... So I took the same approach :smile: a bit ugly, but it …

New module: Do Not Disturb

---

py3status/modules/timer.py

This fixes issue #615
Also an error due to returning a tuple as the cache_timeout.  This was reported by @lasers in #623 but timer module is the cause.
```
2017-01-07 22:59:44 WARNING Runtime error (TypeError) module.py line 152.
2017-01-07 22:59:44 INFO Traceback
TypeError: unsupported operand type(s) for -: 'tuple' and 'float'
File "/home/toby/dev/py3status/py3status/__init__.py", line 44, in main
py3.run()
File "/home/toby/dev/py3status/py3status/core.py", line 778, in run
time.sleep(0.1)
File "/home/toby/dev/py3status/py3status/core.py", line 705, in i3bar_start
self.wake_modules()
File "/home/toby/dev/py3status/py3status/core.py", line 717, in wake_modules
module['module'].wake()
File "/home/toby/dev/py3status/py3status/module.py", line 152, in wake
delay = max(self.cache_time - …
```

timer: fix cache_timeout

---

py3status/modules/scratchpad_counter.py

This adds format: string to print when one or more window (default '{counter} ⌫')
This adds format_none: string to print when no window (default '{counter} ⌫')
This will break `hide_when_none`.
This will break `{}`.
Hold off until 3.4 or what?
EDIT: I don't know how to assign `{}` in the string for backward compatible.

scratchpad_counter: Add format

---

py3status/modules/dpms.py

This adds format: string to display (default '~~{query}~~{dpms}'). Closes https://github.com/ultrabug/py3status/issues/617. 

dpms: Add format

---

py3status/modules/online_status.py

This adds format: string to print (default '{state}')
EDIT: Srsly. What to do here? .__.
```
online_status.py:64:100: E501 line too long (100 > 99 characters)
* response['full_text'] = self.py3.safe_format(self.format, {'state': self.format_online})
online_status.py:67:100: E501 line too long (101 > 99 characters)
* response['full_text'] = self.py3.safe_format(self.format, {'state': self.format_offline})
```
EDIT: 👍

online_status: Add format

---

py3status/modules/scratchpad_async.py

This helps with telling the difference between two scripts in the log.

scratchpad_async: Fix name

---

py3status/modules/clementine.py

This adds format: string to print (default '{current}')
This adds format placeholders:
&nbsp;&nbsp;&nbsp;&nbsp;{current} print current song, artist, title, and/or internet radio
This is still incomplete.
&nbsp;&nbsp;&nbsp;&nbsp;Missing placeholders for song, artist, title, and internet radio.
EDIT: Srsly. What to do here? .__.
```
clementine.py:80:100: E501 line too long (100 > 99 characters)
* response['full_text'] = self.py3.safe_format(self.format, {'current': self._getMetadatas()})
```
EDIT: Are you thinking what I'm thinking? PLS REPLY.

clementine: Add format

---

py3status/modules/window_title_async.py

This helps with telling the difference between two scripts in the log.

window_title_async: Fix name

---

py3status/modules/scratchpad_async.py

This adds format: string to print when one or more window (default '{counter} ⌫')
This adds format_none: string to print when no window (default '{counter} ⌫')
This ~~will~~ should not break `always_show`.
This will break `{}`.
Hold off until 3.4 or what?
EDIT: I don't know how to assign `{}` in the string for backward compatible.

scratchpad_async: Add format

---

py3status/modules/xrandr.py

This adds format: string to display (default '{xrandr}')

xrandr: Add format

---

py3status/module.py

#602 introduced a bug whereby we no longer update the config.  This fixes it and is needed for #555

fix update_placeholder_formats not updating

---

py3status/modules/scratchpad_counter.py
py3status/modules/window_title.py

#620 and #622 revealed some bugs in `window_title` and `scratchpad_counter`
the bugs were the searching functions returning None and i3-py unicode issues.
As i3-py is broken/unmaintained and we only use it to get the tree we can just remove it and use `i3-msg -t get_tree`

remove i3-py dependencies

---

py3status/modules/sysdata.py

@tobes I used the new Meta thing to deprecate precision and padding.
I have one question. Does that mean that if someone uses any of the deprecated parameters, all the new parameters will be ignored and set from the `deprecate_function` in `Meta`?
EDIT: forgot to mention, this is on top of #553

Sysdata: deprecate precision and padding

---

py3status/modules/arch_updates.py

This fixes arch_updates so that we now care about the user config.  Also some minor cleanups setting some constants.
@lasers could you see if this PR works eg `format='AUR {aur}'` should work now.  I don't have an arch setup to test on.
fixes #498 
should remove need for #607

arch_updates fixes

---

py3status/modules/frame.py

I was getting an occasional error.  I think it was some sort of race in that horrible looking line.  Anyhow this seems to fix it and looks nicer.
```
2017-01-16 15:46:38 WARNING Instance `frame time`, user method `frame` failed (AttributeError) frame.py line 105.
2017-01-16 15:46:38 INFO Traceback
AttributeError: 'bool' object has no attribute 'copy'
File "/home/toby/dev/py3status/py3status/module.py", line 584, in run
File "/home/toby/dev/py3status/py3status/modules/frame.py", line 105, in frame
out[-1] = out[-1].copy()['separator'] = True
```

frame: fix possible race

---

py3status/modules/sysdata.py

Found a bug in sysdata whilst testing #679 
```
2017-01-20 13:22:53 WARNING Instance `sysdata`, user method `sysData` failed (UnboundLocalError) sysdata.py line 147.
2017-01-20 13:22:53 INFO Traceback
UnboundLocalError: local variable 'sensors' referenced before assignment
File "/home/toby/dev/py3status/py3status/module.py", line 584, in run
File "/home/toby/dev/py3status/py3status/modules/sysdata.py", line 270, in sysData
cpu_temp = self.data.cpuTemp(self.zone, self.temp_unit)
File "/home/toby/dev/py3status/py3status/modules/sysdata.py", line 147, in cpuTemp
if not sensors:
```

sysdata: cpu temp no zone bugfix

---

py3status/modules/mpris.py

The mpris module catches all player which are started after the py3status instance (see Bug #595)
This fix doesn't work with all players, e.g. bomi!

Detect players starting after py3status

---

py3status/modules/xsel.py

Switching from `xsel` to `xsel -o` make it more bearable. 
`-o, --output:    write the selection to standard output.`
With `xsel` alone, I get this error.
```
2017-01-14 13:23:14 WARNING Instance `xsel`, user method `xsel` failed (Exception) py3.py line 699.
2017-01-14 13:23:14 INFO Traceback
Exception: Command 'xsel' returned non-zero exit status -15
File "/usr/lib/python3.6/site-packages/py3status/module.py", line 584, in run
File "/home/chris/src/py3status/py3status/modules/xsel.py", line 38, in xsel
output = self.py3.command_output(self.command)
File "/usr/lib/python3.6/site-packages/py3status/py3.py", line 699, in command_output
raise Exception(msg.format(cmd=command[0], error=retcode))
2017-01-14 13:23:14 ERROR py3status: Instance `xsel`, user method `xsel` …
```

xsel: Fix xsel

---

py3status/modules/bluetooth.py

I have a module enhancement ready too. Not part of this PR.
It would get rid of two formats at least... similar to nvidia_gpu and adds an on_click
to toggle visibility for `format_bt` only...
Nice if we use BT icon instead of `BT`, but not friendly. People will have to set it themselves if they want to. green ` Microsoft Bluetooth Notebook Mouse 5000` --> green ``
~~Thinking about adding~~ Added option to hide the `format_bt` by default so people don't have to click it everyday as green `BT` is usually more than enough if we are only using one device.
```
-    format: format when there is a connected device (default '{name}')
-    format_no_conn: format when there is no connected device (default 'OFF')
-    format_no_conn_prefix: prefix when there is no …
```

bluetooth: use helpers

---

py3status/modules/net_iplist.py

net_iplist: use helpers

---

py3status/modules/battery_level.py

Uses `self.py3.command_output()`.
Untested.

battery_level: use helpers

---

py3status/modules/diskdata.py

Uses `self.py3.format_contains(self.format, 'avocado')` Hassle-free PR. :avocado: 
Please note the missing `}`. :astonished:

diskdata: use helpers

---

py3status/modules/clock.py

Uses `self.py3.format_contains(self.format, 'cherries')` Hassle-free PR. :cherries:

clock: use helpers

---

py3status/modules/pomodoro.py

Uses `self.py3.format_contains(self.format, 'banana')` Hassle-free PR. :banana:

pomodoro: use helpers

---

py3status/modules/frame.py

Uses `self.py3.format_contains(self.format, 'lemon')` Hassle-free PR. :lemon: ~~Untested.~~

frame: use helpers

---

py3status/modules/mpris.py

Uses `self.py3.format_contains(self.format, 'here')` Easypeasy. :pear:
Untested.

mpris: use helpers

---

py3status/modules/yandexdisk_status.py

Similar to Dropbox...
Adds  `self.py3.command_output()`
Add strings
* string_busy: show when Yandex.Disk is busy (default 'Busy')
* string_off: show when Yandex.Disk isn't running (default 'Not started')
* string_on: show when Yandex.Disk is idling (default 'Idle')
Adds something to take care of exception. Closes issue (should I even make one?)
* string_error: show when Yandex.Disk isn't configured or is outdated.
&nbsp;&nbsp;&nbsp;&nbsp;(default "Yandex.Disk: isn't configured")
* string_unavailable: show when Yandex.Disk isn't installed
&nbsp;&nbsp;&nbsp;&nbsp;(default "Yandex.Disk: isn't installed")
Please note that `else --> BUSY (COLOR_DEGRADED)` section may be wrong because (maybe if not configured), it would display `BUSY` for pretty much anything including this command...
``` …
```

yandexdisk_status: use helpers, remove hardcoded strings, fix exception

---

py3status/py3.py

In #664 an issue was identified where a command would sometimes get terminated by a linux signal (this is what the negative return codes are about).  I think this is something to do with an empty STDIN in that issue.  It may also be a python 3.6 related change.
Anyhow this fixes this which to me feels the correct approach.

Py3.command_output() signal fix

---

py3status/modules/selinux.py

`except OSError:` -> `except:` makes the status work. No more exception... Disabled tho.
It's technically still true because of `show when no SELinux policy is loaded.`
Few strings in there too for full-fledged customization.
Not sure if I should make a minor exception issue on this one.
Untested.

selinux: fix exception, remove hardcoded strings

---

doc/README.md
py3status/core.py
py3status/parse_config.py

This is a proposal to resolve issue #665.
A section named 'custom' has been added as a valid py3status configuration section. If it contains a key named 'nagbar_font', its value will be used as an argument to the i3-nagbar -f option.

Add ability to set i3-nagbar font

---

doc/README.md
py3status/py3.py

`py3.check_commands()` takes a list of commands.  It is easy to pass a string instead.  this PR allows us to pass a string and it will be treated as expected.  It also makes it cleaner to just check for a single command.
`py3.check_commands(['foo'])` ->  `py3.check_commands('foo')`

allow check_commands() to take a string

---

py3status/__init__.py

When running py3status command line stuff eg `py3status modules list` if there is an exception then it is reported via the nagbar etc.  As running these commands only makes sense from the cli it is better to just show the traceback.
This shouldn't affect users but is a major help in development.

nicer exceptions on cli-commands

---

py3status/py3.py

when using `py3.log()` use pretty print to make the logs more readable.
minor import reorder included.

py3 logging nicer formatting

---

py3status/modules/window_title_async.py

It happened when you focused empty workspace and then reloaded i3. (always_show is true)

Do not treat workspace name as window name.

---

py3status/modules/process_status.py

This adds format: string to print (default '{state}')
This adds format_error: string to print when error (default 'no process name given')

process_status: add format, use helpers

---

py3status/core.py
py3status/events.py
py3status/i3status.py
py3status/module.py
py3status/py3.py

This PR just cleans up the `py3_config` this is what I'm calling our parsed config file.  I'm easy on the name.  The aim it to make it part of the py3status config currently it is I3status and we keep having to reach into it.
As well as improving clarity it also means that the i3status stuff running becomes optional rather than being vital We can probably remove the whole mock thread etc.

Cleanup i3status config access

---

py3status/modules/mpris.py

The order of checking `index` was wrong. So mouse clicks weren't recognized if `index` was `None`.

Fix mouse clicks

---

py3status/modules/wifi.py

This module automatically fails on Debian because `iw` is in `/sbin/iw` and not `/usr/bin/iw` like other linux distros.
For regular binaries like dropbox, clementine, hamster, etc, we can keep checks in place.
For sticky situation binaries like `iw`, we can skip and try/except the command instead.
Because of this surprising scenario, I went ahead and check `hcitool` too (for bluetooth module) to see if it was same. It wasn't. `hcitool` can be seen in Debian. We should keep checks in place until `(questionable binary)` can't be viewed somewhere else without sudo.
Closes https://github.com/ultrabug/py3status/issues/572

wifi: remove command_checks(iw)

---

py3status/modules/clock.py

Strftime formats %s and %T include number of seconds, but time_delta is equal to 60, which leads to the seconds counter to be stuck.

Clock plugin: Add %s, %T for time_delta calculation

---

py3status/modules/external_script.py
py3status/py3.py

Uses `self.py3.command_output` 
Uses `os.path.expanduser` (Discussion in https://github.com/ultrabug/py3status/pull/663)

external_script: use helpers

---

py3status/modules/external_script.py

Adds `try/except` to fix an exception I ran into. Closes https://github.com/ultrabug/py3status/issues/756
EDIT: Remove `strip_output` option (line 73-74)... and use formatter instead? [y/n]

external_script: fix exception, remove warning

---

py3status/modules/vnstat.py

Uses `self.py3.command_output()`.
I notice that I can't use `self.py3.command_output()` outside of class Py3status. I put the function inside... since it's the only one thing that's calling that function. If it's possible to use `self.py3.command_output()` outside, please let me know... There are few other modules that are like this. Python2and3 tested OK.
Closes https://github.com/ultrabug/py3status/issues/720.

vnstat: use helpers, add exception, cleanup

---

doc/README.md
py3status/core.py
py3status/module.py
py3status/py3.py

This PR improves support for the py3status section by making it available via `Py3statusWrapper.get_config_attribute()`.  This means that we can easily get at the settings and inherit first from `py3status` and then `general`.  This is really useful for many features eg the popup font could be set at the application or module level.
So it's not about giving modules access but for global features.
```
general {
color_good = '#00FF00'
}
py3status {
color_good = '#00AA00'  # overrides general setting for py3status modules
nagbar_font = 'pango:Ubuntu Mono 12'  # global setting
some_new_setting = 'wow'  # module specific setting
}
my_module {
color_good = '#00CC00'
some_new_setting = None  # overrides
}
```
Edit:  I did a bit more playing with this.  Adding `py3._get_config_setting(name)`. It …

allow improved access to settings from py3status section

---

py3status/modules/wifi.py

For unicode SSID name, iw will output: `SSID: \xe5\xaf\x8c\xe5\xbc\xba\xe5\xba\xb7\xe4\xb9\x90`, it should be properly decoded.

support unicode wifi SSID

---

py3status/core.py
py3status/py3.py

There was a bug in #741 Sorry for letting it through but the functionality is not widely used yet.
This is because colors are handled specially to allow things like 
```
color = self.py3.COLOR_MUTED or self.py3.COLOR_BAD
```
This behavior was broken.  This fixes it.  Colors are special they are the only settings that modules can access directly via the current functionality, and we make sure they are cleaned out of module output.
I have also added a minor addition this just helps when calling `self.py3.unknown()` as we get to see the error.  Really it should be as it's own PR but I thought I'd sneak it in.
```
if not name.startswith('COLOR_'):
-            raise AttributeError
+            raise AttributeError(name)
return self._get_config_setting(name.lower())
```
I think I'm going to …

fix color comparison bug

---

py3status/core.py
py3status/events.py
py3status/module.py
py3status/modules/group.py
py3status/parse_config.py
py3status/py3.py

When a module cannot be imported for example due to a missing python dependency, we notify the user.  A module can also indicate it cannot function by raising an exception in it's `post_config_hook()`.  Again we notify the user.
This can be a pain.  This PR changes the behaviour so that when these happen we put output to the i3bar for the module either `<module_name>` or `<module_name>: <reason>` click 1 will cycle, click 3 will hide.
The reason is `Import Error <error>` or the exception in `post_config_hook()` eg `raise Exception('missing command')`
This should have been added when we added the disable module on `post_config_hook()` exception.
It's pretty basic but we can enhance it as we go along.  I'd like to add something similar for module method call errors at a future time once …

Show import or post_config_hook errors in i3bar

---

py3status/modules/diskdata.py

When the same block device has multiple lines in df output, like btrfs subvolumes, the disk usage is multiplied.
There's probably a better way to do this, but not without rewriting it.

[diskstats module] Fix stats for fs mounted multiple times

---

doc/README.md
py3status/py3.py

This adds a helper to get all the placeholders from a format_string.
It is helpful for a number of potential modules.

Py3.format_placeholders() helper

---

py3status/modules/xsel.py

This adds format: string to print (default '{output}').
Reason for missing `format` in xsel earlier... It was already done in new module `external` which would do the job for both `external_script` and `xsel` (via external_script+ `xsel -o`). The code for both is pretty much almost same. That and severe xsel issues.
Things we wouldn't need anymore due to formatter... `max_size`, `symmetric`, 

xsel: add format

---

py3status/module.py

Fixes the issue reported in #780 
When composites are returned as a list rather than Composite the did not get simplified.  By convrting the list to a Composite we enable the simplification to happen.

fix issue with empty full_text not showing separator

---

py3status/exceptions.py
py3status/modules/exchange_rate.py
py3status/modules/github.py
py3status/modules/spaceapi.py
py3status/modules/weather_yahoo.py
py3status/private.py
py3status/py3.py
py3status/request.py

Seeing as #522 seems to have stalled here is an alternative.
it adds `py3.request()` which returns a simple object that can provide the http status code, text and json.
It allows basic authentication.
request is POST if data is supplied otherwise it will be a GET
query string params can be given in url or as a dict
headers can be supplied.
timeout can be given
I did add proxy support but it ended up getting so complicated (both as code but also testing - https is not supported well) so I removed it all.  For complex things we should just use requests (I'd like to eventually do that via this method so that for example proxies would be usable for all requests)
I've updated all the modules I was able to test.
If it seems good I'll update the documentation

Py3 provide http request functionality

---

py3status/modules/volume_status.py

If the volume is preceded by a '-' pactl will raise the following error:
'pactl: invalid option -- '
We need to pass '--' right after pactl:
$ pactl -- set-sink-volume -5%
Otherwise pactl tries to parse the number as an option, which it isn't. 
reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=686667

add -- after pactl call

---

py3status/modules/backlight.py

This is in response to PR #796 by @Tadly
It does 5 things
1. only calls `_set_backlight_level()` when needed rather than on every event.
2. if we have `xbacklight` installed we use it to get the brightness rather than `/sys/class/backlight`.  THe reason for this is that we can be looking at the wrong device eg `intel_backlight` rather than `acpi_video0` which causes problems.
3. The `brightness_delta` changed from `5` to `8` the reason for this is that some displays only have 15 brightness levels and so misbehave when the delta is 5
4. slightly simplifies the button checks, as there is no need to check for `self.button_up` if it is `None`/`0` then it will not have the value `event['button']`
5. calls `xbacklight -set` with option `-time 0` this causes the update to be immediate and makes …

backlight fixes

---

doc/README.md
py3status/events.py
py3status/i3status.py
py3status/module.py
py3status/py3.py

Following #734 this PR improves error reporting on modules to cover runtime errors.
Errors are shown in a similar manner to in #734 ie in the i3bar with click actions to `1` show more/less detail and `3` to hide the error.
Two types of runtime error are dealt with.
1) unintended errors, the module raises a uncaught exception
2) module triggered errors.  modules can call `py3.error(msg, timeout)` to trigger an error with a user defined message.  the timeout allows the module to be permanently killed or just for a limited time before trying the modules method again.
__Issue:__
Modules are allowed multiple methods.  As far as I'm aware only `netdata` uses this functionality.  I've done my best to fully support this but there is a small edge case around the event, as we cannot tell which …

allow runtime errors to be handled in i3bar

---

py3status/modules/group.py

Fix for #779
when the `group` module shows empty modules it probably should not.  In the default mode you cannot change to the next module.  When an empty group is detected we try the 'next' module.
We make sure we are not endlessly cycling and if there is no module with output we try again every 5 seconds and switch if one has content.
Although this changes the behaviour slightly I think the improvement makes sense.

skip empty modules in group

---

py3status/modules/systemd.py

Simple module to check the status of systemd services via dbus (using pydbus module).
Example showing the status of two VPNs handled by systemd:

Systemd status checker

---

py3status/module.py
py3status/modules/frame.py
py3status/modules/group.py

This is a fix for #750 
There are lots of options but this one feels the simplest and least user invasive.
When a container is closed (so we don't see the urgent module) we just make the 'closed' container urgent.  In practical terms this means that the button will show as urgent.  The user can the decide if they wish to open the container.
This prevents the need for multiple options for what behaviour we want.  This feel a sensible default.
Currently we do not care if the module stops being urgent.  This is quite simple but requires `Module.urgent` to be exposed to modules which it is not currently.  This would trivial but then makes this PR overly complex.

show urgent on closed containers

---

tests/test_module_doc.py

Some configuration parameters have special meaning in the py3status config. This is mainly because they have meaning to i3bar.
`min_width`
`separator`
`separator_block_width`
`align`
This PR adds tests to prevent them being used in modules.
Currently `group` uses `align` and I can't think how to easily remove it so I gave it a free pass

improve docstring tests to prevent reserved config parameters

---

py3status/modules/getjson.py
py3status/request.py

Convert `getjson` module to use `py3.request()`
There was also a bug where we might not get a charset so we now default to utf-8

getjson: use py3.request() + bugfix

---

py3status/modules/frame.py
py3status/modules/group.py

These modules were using the old way of dealing with composites.  Changed them to use the preferred methods.

group/frame: use safe_format() not build_composite

---

tests/test_module_doc.py

When checking module config params we ignore some specific ones.  These are no longer needed.

TRIVIAL remove some un-needed ignored parameters

---

py3status/modules/keyboard_locks.py

The difference between i3py3status's `keyboard_locks` is...
1) Composite / Colors
2) Made for py3status
~~No format though... due to clash with composite.~~ Also, this module is how I discovered the composite bug by emptying out all `icon_*_off` options.

add new keyboard_locks module  

---

py3status/module.py

I think this must have been lost to a `git stash` at some point.
When we dismiss an errored module

bugfix: missing function

---

py3status/modules/taskwarrior.py

This module contain `self.py3.command_output`, but not under `try/except`.
May have to be tweaked again to deal with possible new i3bar `post_config_hook` exception for bits and pieces... such as `isn't installed`.

timewarrior: fix potential exceptions

---

py3status/docstrings.py

`core_module_docstrings()` gets the module documentation from each modules docstring and converts it to MarkDown.
This PR adds a `format` parameter so that we can now ask for the documentation to be converted to RestructuredText.

documentation II (docstring rst functionality)

---

py3status/modules/hamster.py

This module contain `self.py3.command_output`, but not under `try/except`.
May have to be tweaked again to deal with possible new i3bar `post_config_hook` exception for bits and pieces... such as `isn't installed`.

hamster: fix potential exceptions

---

py3status/modules/netdata.py
tests/test_module_doc.py

This adds format: string to print (default '[\?color=stuffs goes here]')
TODO: Add a missing separator. What magic to use? Pls.
TODO: Fix docstring (obv).
TODO: New PR for module enhancements after this...
└──────── Add new threshold options and such.

netdata: add format

---

py3status/autodoc.py

Introducing `autodoc.py` this is used to auto create documentation.
It can be run independently via `python autodoc.py`
In this PR it learns about the modules and creates `doc/modules-info.inc` documenting modules

documentation IV (autodoc modules)

---

py3status/autodoc.py

Ok,
So this one is the worst of this entire series.
What we do is look in Py3 and get all methods, exceptions, and constants and create a documentation include file for each.
We get the methods via looking in Py3, we need to use `inspect` to get the calling parameters
Exceptions we also get via looking in Py3
For constants we need to look at the ast for the file so we can find 'docstrings' for the constants.
A couple of methods log() and notify_user() have constants for defaults so we need `CONSTANT_PARAMS` to allow us to map this.
Hopefully it is broken out enough to be reviewable without too much pain.

documentation VII (autodoc py3)

---

py3status/modules/window_title_async.py

window_title_async: use post_config_hook

---

py3status/modules/github.py

Doing all those little PRs feels like an annoyance, but I guess we want little things at a time.
Easier to test/merge. Sorry about massive emails.
P.S. Replace `?` with `None` to work with... `[{issues}][\?soft=/][{pull_requests}]` or something of that equivalent so we don't have to see `py3status ?/?` sometimes. It just can show up when it's ready with the information.

github: use post_config_hook

---

py3status/modules/xrandr_rotate.py

xrandr_rotate: use post_config_hook

---

py3status/modules/twitch_streaming.py

This changes nothing as `twitch_streaming` is currently broken, but still good to do that.
See https://github.com/ultrabug/py3status/issues/613 for more information.
Gave me chance to peek inside a bit... Things that need to be worked on...
* Code currently broken. We need new API + key stuffs here.
* `format`. Based on other modules, we may want `{format_twitch}` here.
* `format_twitch`. Based on other modules, we would want `state_` or `icon_` for invalid, offline, and any other state.
* Use `py3.requests`. 
* Default `cache_timeout = 60` as not to call Twitch every 10s (imho).

twitch_streaming: use post_config_hook

---

py3status/modules/net_iplist.py

P.S. Do we want to use this...
```
def post_config_hook(self):
self.iface_re = re.compile(r'\d+: (?P<iface>\w+):')
self.ip_re = re.compile(r'\s+inet (?P<ip4>[\d\.]+)/')
self.ip6_re = re.compile(r'\s+inet6 (?P<ip6>[\da-f:]+)/')
```
...or...
```
RE_IFACE = re.compile(r'\d+: (?P<iface>\w+):')
RE_IP = re.compile(r'\s+inet (?P<ip4>[\d\.]+)/')
RE_IP6 = re.compile(r'\s+inet6 (?P<ip6>[\da-f:]+)/')
class Py3status:
"""
"""
```
Same same but different. We want same thing for all modules that needs it.

net_iplist: use post_config_hook

---

py3status/modules/scratchpad_async.py

scratchpad_async: use post_config_hook

---

py3status/modules/coin_balance.py

coin_balance: use post_config_hook

---

py3status/modules/do_not_disturb.py

do_not_disturb: use post_config_hook

---

py3status/modules/bitcoin_price.py

How did we miss this earlier when working on the format? *smh*

bitcoin_price: use post_config_hook

---

py3status/modules/tor_rate.py

tor_rate: use post_config_hook

---

py3status/modules/vpn_status.py

vpn_status: use post_config_hook

---

py3status/module.py

If a module errors and then starts working correctly we still catch some clicks and behave like we are in error eg button 3 hides the module.  This PR fixes this so things behave as expected.

ensure normal click behaviour

---

py3status/module.py

A module is terminated because it failed to load or raised an exception in `post_config_hook()`
However `killall -USR1 py3status` will cause the module to get started when it shouldn't.
This trivial patch fixes the issue.

bugfix prevent terminated modules from being enabled

---

py3status/request.py

#795 is caused by a timeout exception not being properly caught.
this adds an extra chance to catch this and continue as expected.
@lasers this should fix the issue for you

make sure we catch timeout

---

.gitignore
doc/conf.py
doc/configuration.rst
doc/index.rst
doc/intro.rst
doc/modules.rst
doc/py3.rst
doc/writing_modules.rst
py3status/autodoc.py
py3status/modules/graphite.py

This PR brings the documentation together so we can view the content http://py3status.readthedocs.io/en/documentation-part-8
* We call `autodoc.create_auto_documentation()` from `doc/conf.py`
* Fixing some of the links and allowing references to individual modules
* Minor text cleanups and additions
* update `.gitignore` for auto-generated files
* Clean up the `graphite` docstring slightly as it was causing a sphinx indentation warning
Once this is merged then I think we are ready to start using this as the new source of py3status documentation.

documentation VIII (integration)

---

py3status/request.py

So `parse_qsl()` returns a list of tuples not a dict.  Therefore we need to append params as tuples.

bugfix: py3.request() parameters

---

.gitignore
doc/doc-requirements.txt
py3status/autodoc.py
py3status/docstrings.py
py3status/modules/battery_level.py
py3status/screenshots.py

This PR adds screenshots to the new module documentation.  Thanks to @lasers for his idea and support for this feature.
Screenshots are defined in a `SAMPLE OUTPUT` section of the modules docstring.  Multiple samples can be defined.
`autodoc.py` calls the creation of the screenshots and then adds any for a module when documentation is created.
`screenshots.py` does most of the work.  screenshots can be generated by running it directly eg `python screenshots.py`.  We use Pillow to create the images.  The reason for this is that it is available in the readthedocs build system and works well enough.  It has the limitation that it cannot do substitution for glyphs not supported by the chosen font.  As we are using `DejaVuMono` the support is generally good, so far only the 🕝 char.
I wrote …

documentation IX (module screenshots)

---

py3status/modules/xscreensaver.py

Hello there. My best pal @neutronst4r and I aim to... Closes https://github.com/ultrabug/py3status/pull/236 
We took time today to modernize this script the best we can. One part about modernizing this script is to replace commands with `self.py3.command_run`... It works fine... kinda.
The expected behaviour for this module is to leave `xscreensaver` running in the background regardless.
If we start `xscreensaver` and later use `i3-msg start`, the process get killed or something. That was not the case with the current commands. Should we keep the current commands or to use `self.py3.command_run` with some (unknown) parameters?
Please have a look. Many thanks from us. 👨‍👦

add new xscreensaver module

---

py3status/modules/timer.py

This adds format: string to print (default 'Timer {timer}').
This adds format_timer: string to print (default '{H}:{M}:{S}').
One thing I don't know how to solve... Add `color = '#cccccc` # to preserve default color legacy behavior whilst allowing users to use universal `color` option.
I go with easy. Give up default color legacy.... and opt for default statusbar color like any other modules... And if they want default color legacy behavior (or any other color, really), they should set their own color.

timer: add format, use post_config_hook

---

py3status/modules/frame.py

Uses `self.py3.format_contains(self.format, 'lemon')` Hassle-free PR. :lemon: I missed this.

frame: use helpers (no.2)

---

py3status/modules/netdata.py

This removes annoying notification about not finding `nic`.
I don't use netdata but when I'm testing this module, I sometimes run into this annoying notification for many different reasons such as...
* Moving computer/laptop around
* Unplugging cords
* Not running `nm-applet` on startup
* Use `Disconnect` in `nm-applet`
* Whatever the reason may be...
This is quite annoying so I think we should remove the notification part. I'm not sure what stance we would like to take for the _New!_ `nic` placeholder so I included it in the `format` because all other placeholders are in the format too.... with `degraded` color.
Maybe we go with `bad` instead? One thing to point out. The alignment looks slightly off between `\?color=` versus `color threshold`.
`samecolor samecolor` OK.
`samecolor …

netdata: replace notification with placeholder

---

py3status/module.py

With a module error if it was dismissed by a user and then an error occurred again the error would be re-shown.  With this PR the error will not show.
However if the module starts sending 'good' output and then an error happens the error will be shown.  This feels the right approach and is wanted (and tested) in #722

better module error handeling prevent reappearance when dismissed

---

py3status/modules/bluetooth.py

**FORMAT**
```
OLD                    |  NEW
-----------------------|-----------------------
format                 |  format 
format_prefix          |  format_device
format_no_conn         | 
format_no_conn_prefix  |
```
Fixes oops in color options.
~~Deprecates `device_separator` in favor of `string_separator`. Ya I know. Discussion first.~~
* Add _NEW! device_ <-- FUUUUU! (device_separator in bluetooth) to that list too.
**MODULE ENHANCEMENT**
I used `Microsoft Bluetooth Notebook Mouse 5000` F----- long! I fix this now...
button_toggle: mouse button to toggle visibility
* `BT: Microsoft Bluetooth Notebook Mouse 5000` --> `BT` (toggleable, icon_collapse)
always_collapse
* `BT: Microsoft Bluetooth Notebook Mouse 5000` --> `BT` (toggleable, icon_collapse)
~~**DEFAULT**~~
~~Bluetooth …

bluetooth: fix format

---

py3status/modules/uptime.py

Hello there. My best pal @Horgix and I aim to... Closes https://github.com/ultrabug/py3status/pull/205
We took time today to modernize this. The reason we made this PR is because this module really kick asses. Maybe it's not perfect right now, but it should do really well.
* Support `decades` and `weeks` too.
* New default format to be in consistent with output from `$ uptime --pretty`.
Also, we want people to be able to use `uptime` in their py3status sooner than later.
Please have a look. Many thanks from us. 👨‍👦 
EDIT: Before merging, we could revert ABCs (back to time length) on the parameters.

add new uptime module

---

py3status/modules/air_quality.py
py3status/modules/aqicn.py

Courtesy of @beetleman. https://github.com/ultrabug/py3status/pull/746
This covers all remarks.
Style in compliance with other modules.
* ~~TODO: Replace `oldthing` w/ `py3.request` L130~~
* ~~TODO: Decide on using `{icon}` or `{category}`~~
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~~and~~
* ~~TODO: Decide on using `icon_*` or `category_*`~~
I decided on `{category}` and `category_*`. Fight me irl.
To make this more well around, we would have to add things that allows users to override things for i8ln... or they could do that in their own copy of  customized `air_quality` module.
* `aqi_policies = ''` -- Override custom policies
* `aqi_categories = ''` -- Override custom categories
* `aqi_colors = ''` -- Override custom colors
* `aqi_url = ''` -- Override URL
Please take a look. …

fix new air quality module

---

doc/conf.py
doc/configuration.rst
py3status/autodoc.py

config examples are boring and hard to read eg http://py3status.readthedocs.io/en/latest/configuration.html#id3
This PR adds a simple pygments lexer so that they are colorized

documentation X (py3status lexer)

---

py3status/modules/github.py

In #826 @lasers highlighted github doing more updates than needed.
This prevents the updates unless the `button_refresh` is clicked by default this is `2`

github: prevent unneeded updates on clicks

---

py3status/events.py
py3status/module.py

With the updates around showing module errors.  We now always call `Module.click_event()` so that it can handle displayed errors etc.  Because of this the module would be refreshed even if there was no need.
This PR prevents refresh if module's `on_click()` or the error click handling is not done.
Thanks to @lasers for finding this bug in #826

prevent modules being updated when no on_click()

---

py3status/parse_config.py

for #861 
tokens must start with `a-z` or `_` following chars can be `a-z` `0-9` `_` and `-`

allow - in config token

---

py3status/modules/deadbeef.py

As of now, Python2 and Python3 prints out differently in `master` version.
`deadbeef` does not always work correctly for some time now probably because of `u'delimiter'` change back in October and other unknown forces.
To explain more about printing out differently, we sometimes get odd `deadbeef: errors` probably because of `u'delimiter'` and other unknown forces.
Okay, enough. What other unknown forces?  This `deadbeef --nowplaying-tf _FMT` forces.
Running that command can pollute terminal with `starting deadbeef 0.7.2`.
Running that command can pollute terminal with fifty~ lines.
Running that command can pollute terminal with error codes.
Running that command can return `True` for `pgrep deadbeef` at right times.
This PR should make `deadbeef` fully usable with Python2 and Python3. 
I …

deadbeef: back from the dead

---

py3status/modules/keyboard_locks.py

We add `SAMPLE OUTPUT`. I can't generate screenshots anymore as it's not working for me now or I forget how to. Thanks. P.S. How to fix the docs? I found a simple typo. We want `freenode`.

keyboard_locks: add sample output

---

py3status/modules/xrandr.py

The idea is very simple: this module is useful to switch outputs, however when there is only one output available (my case: I'm on laptop with external screen disconnected), there is no sense to consume space on my status panel by showing this module.

[xrandr] Add option to hide output if only one combination is available

---

py3status/modules/getjson.py
py3status/modules/whatismyip.py

A better way to approach #817.
Adjustments to the `whatismyip` module:
- Support any format placeholder that is available in JSON response of `url_geo`, not only hardcoded ones.
- Use a better default value for `url_geo`, which doesn't have DNS issues.
- Remove `url` and always use `url_geo` to simplify the code.
- Ensure the COLOR_GOOD is always used when online.
@tobes please have a look and let me know what you think, I'll test more later today and fix lint issues if they occur.

[whatismyip] Support any format placeholder, always use `url_geo` with a better default

---

py3status/modules/whatismyip.py

I was running this locally for quite a while, and I must say it is very useful feature.
With it I don't have to visually compare all the time if my IP / country changed or not, I can use py3status to do this for me and colors to quickly bring the mismatch to my attention.
Unless, this somehow can be done with magical `format`? 😉

[whatismyip] Add 'expected' param

---

py3status/modules/wifi.py

This adds format: string to print `(default 'W: {status}')`
This uses existing string to print`(format_down = 'down')`
This uses existing string to print `(format_up = '{bitrate} {signal_percent} {ssid}')`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;OR
One format for everything `(default 'W: [{bitrate} {signal_percent} {ssid}|\?show down]')`
You pick.
I may have some more cleanups/changes for this module on different branch.
Will wait for 3.6. Hassle-free `format-only` PR. 100% Untested. 🐗 

wifi: add format, merge formats 

---

py3status/modules/sysdata.py

This reverts commit 4d90fd69d75b83c5e15244f5bf1a043b3b0f83fb, and thus, re-adds load support to sysdata. (There'll be another one for swap).
This adds three new placeholders `load1`, `load5` and `load15` and one new threshold `load` compared to the value of `load1`.

Add load support to sysdata

---

py3status/modules/wifi.py

Quick bugfix for my netbook. Confirmed working okay.
```
2017-04-11 05:49:45 INFO ========
2017-04-11 05:49:45 INFO Starting py3status version 3.6rc1 python 2.7.13
2017-04-11 05:49:45 INFO i3status spawned using config file /tmp/py3status_qHIvRD
2017-04-11 05:49:45 INFO loading module "wifi" from /home/chris/src/py3status/py3status/modules/wifi.py
2017-04-11 05:49:45 INFO starting module wifi
2017-04-11 05:49:45 WARNING Instance `wifi`, user method `wifi` failed (AttributeError) wifi.py line 173.
2017-04-11 05:49:45 INFO Traceback
AttributeError: Py3status instance has no attribute '_ssid'
File "/usr/lib/python2.7/site-packages/py3status-3.6rc1-py2.7.egg/py3status/module.py", line 709, in run
File "/home/chris/src/py3status/py3status/modules/wifi.py", line 173, in wifi …
```

wifi: fix AttributeError bug

---

py3status/exceptions.py
py3status/py3.py
py3status/request.py

if we do `py3.request(url).json()` and there is invalid JSON we get a nasty exception.
This PR make it so we now raise  `RequestInvalidJSON` so now such exceptions are easy to catch.  This is useful for example in PR #877

raise exception on invalid JSON in request

---

py3status/composite.py
py3status/formatter.py
py3status/py3.py
tests/test_formatter.py

So it's been a while since the formatter got a rewrite :)
In 3.5 the formatter processes the format_string and substitutes the placeholders in a single pass.  This has two effects.  Firstly we do the work of processing the format_string every time we use it.  Secondly doing the substitutions at processing time makes it overly complicated and hard to add new features.
This PR corrects this approach.  We now process the format_string once and cache it.
The code is imho much easier to follow especially around the min_max length processing
The tests now show errors in a more readable manner using `pprint.pformat()` and can be run in a way to allow easier benchmarking etc.  All the original tests pass and some new ones have been added.
Adding additional features is easier eg `[\?soft -]` …

formatter rewrite to improve fuctionality

---

py3status/modules/getjson.py
py3status/py3.py
tests/test_py3.py

`getjson` module has a dict flattening method.
```
{
'fish_facts': {
'shark': 'Most will drown if they stop moving',
'skates': 'More than 200 species',
}
'fruits': ['apple', 'peach', 'watermelon'],
'number': 52
}
{
'fish_facts-sharks': 'Most will drown if they stop moving',
'fish_facts-skates': 'More than 200 species',
'fruits-0': 'apple',
'fruits-1': 'peach',
'fruits-2': 'watermelon',
'number': 52
}
```
make this available to other modules

new py3 helper flatten_dict()

---

py3status/modules/wifi.py

**POST_CONFIG_HOOK**
We avoid `sudo` and/or `iw dev` to avoid potential issues, password, privilege permission, error codes, missing binaries, etc. Idk. Eww, tacky. We use `/sys/class/net` instead.... looking for first available ifaces starting with `w`.
I don't believe the `wifi` in master branch detects ifaces correctly. It either skip them entirely... or just use the assigned `wlan0` right away due to stupid default `self.device = "wlan0"` setting so I'm guessing that works for years... until people switched to `wlp3s0` or something. We now assign it `None`.
I'm not even sure if it went through `if-else` in `post_config_hook` because it was hard to test things without working color comparison (for terminal) and without working `post_config_hook` (for terminal too). I had `wlp3s0`. …

wifi: fix sudoers entry

---

py3status/modules/battery_level.py

This is how I fixed https://github.com/ultrabug/py3status/issues/548 on my Dell notebook where the battery level can go above 100% . Simply limits the icon character index to the string length, so the rightmost character will be also be shown for levels > 100%.

Battery level icons now work with capacity over 100%.

---

py3status/modules/net_iplist.py

This fixes `net_iplist` by using the new `composite_join`. Previously, it would do a `str.join` but that doesn't work with composites.
Additionally, the regexp has been improved so that it can display ip addresses of peered interfaces (such as VPNs) too.
EDIT: this is similar to #901 I think.

Fix net_iplist to work with master

---

py3status/exceptions.py
py3status/modules/external_script.py
py3status/py3.py

When there is an error it is hard to know what went wrong.  Also some commands use error codes to indicate things other than something actually was bad.  Anyhow we now raise a `CommandError` exception that allows access to the returncode, error, and output of a command.
I'm sort of thinking with `py3.command_run()` we should just simplify it and get it to return `True`/`False` depending on if it runs ok,  So if command has a retcode of `0` we return `True` else `False`.  I think that would make more sense for quick easy usage.

py3 commands raise CommandError

---

py3status/modules/clock.py

@lasers found a bug that came to light with the formatter changes.
This is due to a composite being returned rather than a string.  This is a bug in clock that the formatter changes triggered.

fix for clock module due to returned composite

---

py3status/modules/xrandr_rotate.py

Uses `self.py3.command_output(cmd, shell=True)` Hassle-free PR. 🖥 
Thoughts on adding `.strip()` inside `py3.command_output`?
```
./gpmdp.py:41:            return self.py3.command_output(['gpmdp-remote', cmd]).strip()
./hamster.py:34:        activity = self.py3.command_output('hamster current').strip()
./insync.py:70:            status = self.py3.command_output(["insync", "get_status"]).strip()
./backlight.py:94:            level = self.py3.command_output(['xbacklight', '-get']).strip()
./xrandr_rotate.py:60:        return self.py3.command_output(cmd, shell=True).strip().split()
./xrandr_rotate.py:65:        output = self.py3.command_output(cmd, shell=True).strip()
./xrandr.py:139:        current = self.py3.command_output('xrandr').strip()
```

xrandr_rotate: use helpers

---

py3status/modules/xrandr.py

Uses `out = self.py3.command_output(cmd)`
Uses `self.py3.command_run(cmd)`
I filed bugs for both `xrandr` and `xrandr_rotate` so I can't be too sure about the consistence between this PR and `master` version. I keep PR simple enough to know things works fine out of the box with the new helpers, but still unsure about behavior due to existing bugs. Thanks. 
Hopefully, a hassle-free PR. 🎃

xrandr: use helpers

---

doc/contributing.rst
doc/index.rst
doc/intro.rst
doc/py3-cmd.rst
py3status/command.py
py3status/core.py
setup.py

As requested in #588 and #745 and also required for #481 (though requires further code)
Command line fun for all the family
```
py3status-command refresh_all
py3status-command refresh wifi
py3status-command refresh "wifi eth0"
py3status-command refresh wifi whatismyip
py3status-command click whatismyip
py3status-command click 5 backlight
```
Calling commands from i3
```
bindsym $mod+x exec py3status-command click whatismyip
bindsym XF86AudioRaiseVolume  exec "amixer -q sset Master 5%+ unmute; py3status-command refresh volume_status"
bindsym XF86AudioLowerVolume  exec "amixer -q sset Master 5%- unmute; py3status-command refresh volume_status"
bindsym XF86AudioMute         exec "amixer -q sset Master toggle; py3status-command refresh volume_status"
```

py3status-command: control py3status from cli/i3

---

py3status/modules/dpms.py

This adds safeformat for all statuses (on/off). Now we can customize this. 📺
I looked at the history commits for this `dpms`. It was pretty awful. I was noob and made several commits before I learned about using `--amend`... Sorry for all the noises, all the emails, etc... Thanks to my friend @tobes for putting up with that and always helping out with things.
Hi. About this module... I believe it turns out that we should stick with `format_on`, `format_off` in first place and pass everything in `safe_format`...
Several months earlier, we didn't do that. We turned this into `{icon}` and `icon_*` because we don't want `format_*` for non-format strings and we didn't bother to `safeformat` things. That would have been easier in first place. I think it is best that we format all the things. …

dpms: add safeformat for all statuses

---

py3status/modules/whatismyip.py

As of now status mode in whatismyip only shows either color_good or color_bad and as such ignores user "expected" dictionary, showing color_good even when there is an IP/country mismatch. This following commit fixes this and adds color_degraded support for status mode.

color_degraded support in status mode for whatismyip module

---

py3status/modules/external_script.py

Read a color code from the second line of output.
If the external script has only one line of output the behavior
is unchanged.

external_script module: add support for colors

---

py3status/modules/i3block.py
tests/test_module_doc.py

i3blocks https://github.com/vivien/i3blocks is a popular alternative to py3status.
In the spirit of _keep your friends close but your enemies closer_ I've written a module to allow i3blocks blocklets (and compatible scripts) to be run directly in py3status.
Support i3blocks blocklets in py3status.
[i3blocks](https://github.com/vivien/i3blocks) is a project to allow simple
scripts to provide output to the i3bar.  This module allows these blocklets to
run under py3status.  The configuration of the blocklets is similar to how they
are configured in i3blocks.
Some blocklets may return pango markup eg `<span ...` if so set
`markup = pango` in the config for that module.
```
[time]
command=date '+%D %T'
interval=5
[wifi]
instance=wls1
label='wifi:'
command=~/i3blocks/wifi.sh
interval=5
order += …
```

i3blocks support

---

doc/configuration.rst
py3status/module.py

As discussed in #761. This PR enable a universal `allow_urgent` config parameter.
```
py3status {
allow_urgent = True
}
module {
allow_urgent = False
}
```
It is enforced by module.py (i3status modules would not be affected - do they use urgent? - could be added)
it is possible for modules to set a legacy default but this only makes sense for existing modules (github, scratchpad_async, pomodoro)

Universal allow_urgent

---

py3status/modules/volume_status.py

Device is not always `0`. It can be `1`. Dunno about `[2-9]`. Fixes https://github.com/ultrabug/py3status/issues/921.

volume_status: (pactl) get device number instead of assuming device 0

---

py3status/modules/spaceapi.py

The 'lastchange' field in the 'state' object is optional according to the SpaceAPI specification. If it is not present, the lastchanged variable was never set, causing a 'used before assignment' error during formatting.

spaceapi: prevent 'used before assignment' error

---

py3status/modules/mpris.py

When you ran the _mpris_ module in test mode you couldn't abort it with ^C. The exception was 
caught in the module and wasn't raise up to _module_test_.

mpris: raise keyboard interrupt

---

py3status/modules/backlight.py

```
❯  xbacklight -get
100.000000
❯  xbacklight -get
94.947121
```
In these cases the module was outputting `100%` and `94%`. I want to see `95%` in the latter case 🙂

Round brightness values (so that 94.96% is rendered as 95% and not as 94%)

---

py3status/modules/volume_status.py

In order to get volume/mute state this module uses regexp containing hardcoded english words Mute, Sink, Volume. This fails on systems with language set to some other language than English, because this regular expression does not match any line which results in exception.
This commit forces english pactl output by setting LC_ALL environment variable to 'C' in spawned subprocess

volume_status: fix PactlBackend on non english system

---

py3status/modules/spotify.py
tests/test_module_doc.py

A lot of spotify album/track titles have this rubbish Remastered or Stereo suffix (eg. "Ziggy Stardust - Remastered 2012 Version"), which is an absolute waste of space on the screen, looks very unaesthetic and also is very useless.
This PR introduces new config options
sanitize_titles: true/false 
sanitize_words: list of words that indicate meta data

spotify: sanitize album/track title

---

py3status/modules/battery_level.py

Quickfix for #732. Catches ZeroDivisionError which could happen if either the active or inactive battery is reporting 0% capacity.

Catch ZeroDivisionError for #732

---

py3status/modules/mpris.py

There is a bug with the dbus signals. We get callbacks for all running players if only one player change the playback state.
To catch the false signals I check the playback state with the dbus method additionally. Let me know if you've an better idea.

mpris: dbus signal fix

---

py3status/modules/arch_updates.py

There is no `-b` flag, using it leads to zero results.

Fix usage of cower in arch_updates module

---

py3status/modules/whatismyip.py

In #826 @lasers highlighted modules doing more updates than needed.
This prevents the updates unless the button_refresh is clicked by default this is 2

whatismyip: prevent mouse updates

---

py3status/modules/github.py
py3status/py3.py
py3status/request.py

Allows modules to access headers from `py3.request()`.
Updates `github` module to use them.
Cleaned up the import of `urlparse`
Fixed logical bug where we would always check for links  `''.split(', ') == ['']`
Fixed typo in `Py3.request()` comment

Make headers available via py3.request() and update github module

---

.travis.yml

Travis is now using `trusty` rather than `precise` for builds which broke pypy.
This sets a pypy version.  Which fixes things.  We should look into what pypy versions we want to/cn support via travis

set pypy version - fix build tests

---

py3status/__init__.py
py3status/command.py
setup.py

py3-cmd is slow #918 
current performance for `time py3-cmd click 2 volume_status` (median of 3 runs)
```
python 3
real    0m0.347s
user    0m0.319s
sys     0m0.023s
python 2
real    0m0.270s
user    0m0.223s
sys     0m0.045s
```
with this branch
```
Python 3
real    0m0.091s
user    0m0.074s
sys     0m0.016s
Python 2
real    0m0.056s
user    0m0.043s
sys     0m0.011s
```
We get this improvement by
* only importing `py3status.core` in `__init__.py` this means we can import from py3status much more cheaply.
* only import `platform` module if we need it
* hack `setuptools` so that we can run our command without all the overheads of importing `pkg_resources`
when installed from a wheel we do not have these issues as the command runs without the overhead.

Faster py3-cmd

---

py3status/formatter.py
tests/test_formatter.py

@maximbaz found an issue around values that get rounded to zero not being treated as zero in some situations. eg #964
Moving the zero check till after the value has been formatted fixes the issue.
Tests added to prevent regressions

formatter not zero fix for displayed values

---

py3status/formatter.py
tests/test_formatter.py

This PR enables `not_zero` and `show` formatter commands to be inherited.  Previously `color` ended up propagating.
This means we can now write a format like `\?not_zero Output:[ X {x}][ Y {y}]` rather than `Output:[\?not_zero  X {x}][\?not_zero  Y {y}]` which should help us simplify formats a bit
eg uptime `'up [\?if=weeks {weeks} weeks ][\?if=days {days} days ][\?if=hours {hours} hours ][\?if=minutes {minutes} minutes ]'`  == `'\?not_zero up [ {weeks} weeks][ {days} days][ {hours} hours][ {minutes} minutes] '`
Due to the inheritance changes, color now uses the same code rather than it's old method.
Some tests added for luck

formatter allow some commands to be inherited

---

py3status/modules/cmus.py
tests/test_module_doc.py

I looked at `cmus` from `i3py3status`. Made one for py3status.
`cmus-remote` offers ton of buttons to click so I tossed them all in.
The `--volume` and `--seek` options are quite nice for scrolling wheel.
We get metadata directly from `cmus` so there are quite lot of placeholders and I likely didn't get them all... due to missing metadata in songs, Internet radio stations and such.
This makes it a fun module to use. Please let me know if you have any questions. Thx.

add new module: cmus

---

py3status/modules/moc.py
tests/test_module_doc.py

**`moc`** is a console audio player designed to be powerful and easy to use.
This is similar to `cmus`. Two things I'm pondering about...
~~**No. 1**~~
~~I have `cache_timeout` and `cache_timeout_off`. The second one is for sleeping so it
does not run every 2s when the software is not running.~~
~~If we do this style, I wonder if it's a good idea to merge this instead of two separate
options.~~
~~* `cache_timeout = 5, 20` ---> (refresh `5`, sleep `20`)~~
~~* `cache_timeout = 5` ---> (refresh `5`, sleep `5`)  <--- How most modules usually
operate.~~
**No. 2**
Same thing for buttons. The number of buttons available for `cmus` and `moc` easily outnumber the number of buttons on most comfort mouses. We stick with this or same scenario with `No .1` above using a dictionary? One button config …

add new module: moc

---

doc/intro.rst

When we renamed `py3-cmd` we missed this reference in the documentation.

Fix py3-cmd link in docs

---

doc/conf.py
py3status/autodoc.py
py3status/screenshots.py

To allow screenshots to be embedded in the documentation, this PR adds a `screenshot` directive to sphinx.  This will be useful for documenting formatting.
```
.. screenshot::
{'color': '#00FF00', 'full_text': 'Example output'}
```
The changes to `screenshots.py` are to allow single images to be created, but don't really change how things are done.  There is a bit of nastiness around caching `font` and `glyph_data` as that helps performance.

Docs: add new screenshot directive

---

py3status/modules/cmus.py
py3status/modules/moc.py
py3status/screenshots.py

New `cmu` and `moc` modules had errors in their screenshot data.  This also broke the documentation build.
* fix modules screenshot data
* improve screenshot building so that if this happens again the build will not die
**edit**
fixed additional docstring errors causing build warnings/formatting issues

cmus, moc: fix screenshots

---

py3status/module.py

If a runtime error is more than one line it displays incorrectly in i3bar.  This fixes the issue by only showing the first line.

Only show first line of error in i3bar

---

py3status/modules/window_title_async.py

Hi. This module could use a bit of rewritten... to get rid of `max_width` in favor of the formatter and maybe some other minor things to clear up the confusion. For now, we closes https://github.com/ultrabug/py3status/issues/747

window_title_async: fix workspace glitch

---

py3status/core.py
py3status/module.py
py3status/module_test.py
py3status/py3.py

#806 called attention to problems with `module_test` not using the same code paths as when `py3status` is running. This is due to changes regarding getting config settings and the formatter updates. This causes issues
master (color missing and Composite causing confusion)
```
$ python modules/dpms.py
{'color': None, 'full_text': <Composite [{'full_text': u'DPMS'}]>, 'cached_until': 1500839733.0}
```
this branch (output as we send to i3bar - excluding cached_until which is added for user debugging)
```
$ python modules/dpms.py
{'color': '#00FF00', 'full_text': u'DPMS', 'cached_until': 1500839670.0}
```
Although it looks large there are few changes to how the code works.
__core.py__
We create a new class `Common` which holds common code `report_exception()` and `get_config_attribute()` so …

share code so module_test improved

---

py3status/modules/clock.py

#988 found an error in the clock module strftime formatting.  This PR fixes the issue by ensuring we have none unicode strings in python2.
The fix is big due to restructuring the code.  It might be worth moving the code into Py3 at some point if other modules need this functionality.

clock module fix unicode time formatting

---

py3status/py3.py
py3status/util.py

This is something that i3pystatus had that I though was a nice feature.
Instead of using sharp color changes on thresholds ie either good/degraded/bad we allow gradients between the colors.
Gradients are disabled by default to enable add `gradients = True` to `py3status` section or to individual module in config.
Any modules that use thresholds will then work.
The code creating the gradients is a little as we need to use hue, saturation, value colorspace rather than rgb so that we can have really good gradients. but it is self-contained.
There may be issues if modules have very small threshold ranges eg `[(0, 'good'), (0.5, 'bad')]` but I don't think modules currently do this and we can always fix if we have some.

universal gradients

---

py3status/parse_config.py

the following config broke py3status see #987
```
order += static_string
static_string 
format = 'py3status test'
}
```

better error catching for missing {

---

py3status/modules/static_string.py

* For terminals, we can put `hello, world!` in the `format` instead of using `test` config.
* This module can be used to test something... or to have a work-in-progress module being sandwiched by two of this modules... to make sure we added the module correctly and that it's printing things correctly.... and checking padding issues... and et cetera...
* When one sometimes want to try something using `static_string` and run it from terminal, one would get `test` config every time instead of the expected result. This simply removes a minor annoyance.
* If that's not a good enough, well... We, and the users, could just add `static_string {}` and see the result right away... without having to put something in the `format`.
* If that's still not good enough... Man, you're tough... I don't …

static_string: hello, world!

---

py3status/modules/cmus.py
py3status/modules/moc.py

I had this branch ready already. I removed `moc` duplicate placeholders
```
{totalsec} total time in seconds, eg 4322
{totaltime} total time in seconds, eg 72:02
```
The rest is just fixing up formatting and phrasing things better (imho).

cmus, moc: quality assurance

---

tests/test_module_doc.py

Hey all!
While working on #930, I ran into the linter pretty consistently. The most annoying issue to deal with was alphabetical ordering for parameters, as the error message in the linter would not indicate clearly which items were out of place. This becomes a bigger issue the more options you have!
I decided to take a crack at improving it! Below are my changes. I added a simple `diff` method to signal differences between two lists of items. This improves the linter output significantly:
_Module source_:
```python
...
cache_timeout = 10
fallback = True
force_on_start = None
fixed_width = True
format = '{output}'
icon_clone = '=' 
icon_extend = '+' 
hide_if_single_combination = False
output_combinations = None
...
```
_Before_:
```
Attributes not in alphabetical order, should be …
```

Better module doctest failures

---

py3status/core.py
py3status/events.py
py3status/i3status.py
py3status/module.py

Currently killing py3status is slow.  This is mainly due to the i3status thread that can wait up to 5 seconds to die.
by 'reversing' the lock we can wait() on it and die much quicker
making the event thread a daemon also cuts off approx 500ms
minor cleanup of `I3status.__init__()` to bribe you (I can put as separate PR) plus we lose a line of code :D
```
time timeout 5 py3status > /dev/null
real	0m5.073s
user	0m0.349s
sys	0m0.064s
real	0m10.073s
user	0m0.341s
sys	0m0.065s
```

reverse lock so we can wait for it

---

py3status/core.py
py3status/i3status.py

use `wait()` with a timeout rather than `sleep()`
this reduce the amount of overhead and also makes us more responsive as we do the updates exactly when they are needed.
i3status is special so it needs to tell us when it wants to update the times which we still do in the main loop.
i3status stuff can be much improved but we get a nice benefit here and keep the PR easy to review.  later we can do that cleanup.
the test is rather crude we just run py3status for 10 mins but it shows we save cycles
```
time timeout 600 py3status > /dev/null
real	10m5.061s
user	0m0.800s
sys	0m0.125s
real	10m5.056s
user	0m1.151s
sys	0m0.232s
```

use wait() instead of sleep() in main loop

---

py3status/composite.py

Skip adding separator for empty strings, responses, and Composites.

composite: skip adding separator for empty items

---

py3status/core.py
py3status/events.py
py3status/i3status.py
py3status/module.py

This PR reduces the amount of time we spend in threading module by ~50%,  we do increase the work done in core by ~40% but this is a small increase compared to the saved time.
Overall it is about a ~15% saving
on my 10 minute test based on pprofile line profiling.
**master**
py3status module updates: 1595
total cpu time: 1,285,655
threading: 411,426
core time: 86,658
**branch**
py3status module updates: 1622
total cpu time: 1,109,407
threading: 208,338
core time: 123,383
* `Py3StatusWrapper.queue` renamed to `Py3StatusWrapper.update_queue` for readability
* `Module` no longer a `Thread`
* remove the `Timers` in `module.py`
* replace `Py3StatusWrapper.lock` with `Py3StatusWrapper.running` where possible to reduce overhead.
* We now run modules using a simple `Runner` thread when updates …

remove Timers and spend less time in threading

---

py3status/docstrings.py
py3status/modules/xrandr.py

Update xrandr docstring.
To both improve the display and for upcoming documentation work.  Fixes glitches in readthdocs output
To enable `<OUTPUT>_workspaces` etc to be recognized the re used for documentation creation now allows parameter names starting with `<`

xrandr: clean docstring

---

py3status/modules/i3block.py

By adding `cache_timeout` to the parameters, helps with cleaner testing and helps generally for documentation purposes.

i3blocks: fix parameters so all documented

---

py3status/core.py
py3status/i3status.py
py3status/module.py

Some minor cleanups to `i3status.py`
* setup things like `I3StatusModules` in advance rather than in the loop checking `i3status` output.
* only check timezone info on first run and then on the half hour rather than every minute.  This also improves checking after sleep/suspend (timezone checking is costly due to `strptime()`)

Cleanups to i3status including reducing workload

---

py3status/modules/xrandr.py

We kill off `_refresh_py3status` and use `py3.update` here.

xrandr: use py3.update

---

py3status/modules/xrandr.py

xrandr: use post_config_hook

---

py3status/modules/fedora_updates.py

Replacing `__init__` with `post_config_hook` for `fedora_updates`.

fedora_updates: use post_config_hook

---

py3status/modules/player_control.py

Replacing `__init__` with `post_config_hook` for `player_control`.

player_control: use post_config_hook

---

py3status/modules/pingdom.py

Bugfix.
```
2017-09-02 10:05:37 WARNING Instance `pingdom _anon_module_47`, user method `pingdom_checks` failed (KeyError) module.py line 774.
2017-09-02 10:05:37 INFO Traceback
KeyError: 'missing "full_text" key in response'
File "/home/chris/src/py3status/py3status/module.py", line 774, in run
raise KeyError(err)
```

pingdom: fix keyerror exception

---

py3status/modules/icinga2.py

```
'Py3status' object has no attribute 'color' (AttributeError) module.py line 747.
Traceback
AttributeError: 'Py3status' object has no attribute 'color'
File "/home/chris/src/py3status/py3status/module.py", line 747, in run
File "icinga2.py", line 48, in get_status
'color': self.color,
```
I'm guessing 2555bd62ba054a39ced272d7d1d65e3dfa12ff9d broke this module last year right on this month. Removed the orphaned `self.color`.
Now we get the annoying `stuffs are not working without the configurations`. I added `not configured` in the `post_config_hook`. See how it could be broken for some time, I go ahead and clean up everything.

icinga2: fix attributeerror exception, use post_config_hook

---

py3status/modules/apt_updates.py

We make `post_config_hook` for `apt`. Performance tweak.
We prevent this module from complaining too much. `[Errno 2] No such file or directory: 'apt'`.

apt: use post_config_hook

---

py3status/modules/backlight.py

Hi. Here's a bugfix. Just because the users can install `xbacklight`... does not mean `xbacklight` ought to be enabled internally in the module. For that, we need more than checking a command.
We need a better xbacklight detection.
When Linux distros and/or DE detects that the users are using a laptop, it can install `xbacklight` too... likely a part of laptop/other metapackage.
Having it installed does not necessarily mean that `xbacklight` are guaranteed to work out of the box... as some laptops can have native backlight support using Fn key. Some laptops can not have this feature too so the users would be left with a bad/broken module.
If you looked in the module, you can see that because you have `xbacklight` installed, it will try and get you a value from `xbacklight -get` instead of …

backlight: better xbacklight detection

---

py3status/modules/vnstat.py

We move one thing to `post_config_hook`. Performance tweak.

vnstat: use post_config_hook

---

py3status/modules/clementine.py

We make `post_config_hook` for `clementine`. Performance tweak.

clementine: use post_config_hook

---

py3status/modules/insync.py

We make `post_config_hook` for `insync`. Performance tweak.

insync: use post_config_hook

---

py3status/modules/diskdata.py
py3status/modules/github.py
py3status/py3.py

We can stuff many things in a sack of `py3.contains_format` along with `any`/`all` option.

py3: add multiple format_contains

---

py3status/modules/netdata.py

Removing `__init__`. Moving things to `post_config_hook` for `netdata`.

netdata: use post_config_hook

---

py3status/modules/battery_level.py

Removing `__init__`. Moving a thing to `post_config_hook` for `battery_level`.

battery_level: use post_config_hook

---

py3status/modules/diskdata.py

Currently only free, used, and used_percent are exposed. Even though you could infer the total disk space using these values, it's a bit cleaner to just expose the total disk space as well to allow for format strings such as `Disk Usage: {used}/{total_space}GB`

Expose total disk space in diskdata module

---

py3status/py3.py

The module is totally broken now. Because since `cmd` is a string, and because we rely on shell (like pipe and grep), py3.command_output() will `shlex.split` it, and the command becomes invalid.
https://github.com/ultrabug/py3status/blob/c63d7fccfd0789d590a0f20c5bca3341423b0cdb/py3status/py3.py#L861-L865
Until the module is rewritten without relying on the shell, I'm wrapping it in an array so `shlex.split` is not being applied on the command.
I haven't been using this module for a while, so it could have been broken for a long time already 🙂

Fix xrandr_rotate module

---

py3status/modules/vnstat.py

`vnstat` deprecated `--dumpdb` many years ago in favor of `--exportdb`. Being nice and all, `vnstat` continues to support the old command. Debian stable does not have `--dumpdb` in their man page either. I think we should use the updated command.

vnstat: use updated command

---

py3status/modules/xrandr_rotate.py

Hi. I studied the code. This fixes https://github.com/ultrabug/py3status/issues/837. Please merge https://github.com/ultrabug/py3status/pull/1103 first. 👍 
**ORIENTATION** 
I shared this in the bug report.
```
I expected green `H` for using landscape monitor.
I received green `V` instead.
```
We received green `V` instead because of this biased statement...
```
is_horizontal = (orientation.startswith('(') or
orientation in ['normal', 'inverted'])
return self.horizontal_icon if is_horizontal else self.vertical_icon
```
We get `self.vertical_icon` when it does not match `normal` or `inverted`. This also returns `V` on the empty lines and even on `(normal` too. I likely got empty lines based on the initial report.
```
xrandr: Output DP-3 is not disconnected but has no modes
xrandr: Output …
```

 xrandr_rotate:  fix orientation

---

py3status/py3.py

Some commands provide valid output via STDERR this PR allows this to be piped to STDOUT.
This is an issue for `apt` and `dnf`

command_output allow piping of STDERR to STDOUT

---

py3status/modules/external_script.py

external_script has it's own 'error handling' make it use `py3.error()` for consistency.

show external_script error using error()

---

py3status/modules/kdeconnector.py

Define `self._dev` in `post_config_hook()` rather than in the class body

kdeconnector: clean up _dev

---

tests/test_formatter.py

Currently when a formatter test fails we get a backtrace of the testing functionality which is both noisy and unhelpful.  If an actual exception occurs during a test then we do see that traceback as it is important for fixing the issue.
This PR uses pytest functionality to make fails cleaner, we also print out the failing format to make the error easier to understand.
example
failing test in current master
```
_________________________________ test_inherit_show_1 __________________________________
def test_inherit_show_1():
run_formatter({
'format': '\?show [[[hello]]]',
>           'expected': 'hello x'
})
tests/test_formatter.py:1169: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_dict = {'expected': 'hello x', 'format': '\\?show …
```

tests: cleaner more helpful output on test failure

---

py3status/core.py

`helpers.print_line()` adds extra overheads by 
* being called
* doing lookups eg `sys.__stdout__.write`
* adding a `\n` that we can do
this just inlines it.  maybe we should remove it from helpers as there are no users of the function left

explicit new lines for output plus inline code

---

py3status/module_test.py

Fixes standalone module testing including #1018 so that we can do `python module.py`

update standalone testing

---

py3status/py3.py

fix for #1028
make `py3.log()` more like `log()`
now we just do the `pformat` on tuple, list, dict, set

improve logging for modules

---

py3status/request.py

Revisiting the issue of #1052 
Rather than just fixing `exchange_rate` module to not fail, I dug further and found the root cause.
When we do `Py3.request()` we have 3 outcomes.
1. Everything is good we get our `HttpResponse` with all the `.json()` etc
2. We get a timeout or similar and a `RequestException` of some type is raised
3. We have a http error and return a `HttpResponse` with the `status_code` set
In the 3rd option the returned `HttpResponse` fails if attributes `text`, `headers` are queried or the `.json()` method.  This PR allows these to now function as expected.

fix HttpResponse for when an http error ocurrs

---

py3status/i3status.py

I'm an idiot and forgot to multiply.
This corrects the timezone checking so that it is actually every 30 mins as it should be

set the correct timezone check time

---

py3status/core.py

This is an improvement on #1029 
Instead of using a lock etc we just do all the work manipulating the timeout queuing stuff inside the main thread.
Modules now add to `timeout_add_queue` which is atomic.  If needed they cause the timeout queue processing.  If an update is due before the module update then we do not need to trigger the processing as it will be done in time for the module to be updated correctly.
Overall this is more efficient and hopefully less complex because we don't have the locking issues.

adding module timeout move to core thread
