py3status/modules/spaceapi.py
This module is providing your hackerspace status provided by a json file standarized by SpaceAPI (spaceapi.net, v0.13)
=> add spaceapi module

py3status/modules/battery_level.py
=> fixed battery_level.py compatibility with Python3

py3status/modules/bluetooth.py
I wrote a new module which shows the status of the bluetooth connection ("BT: OFF" vs. "BT: \<DEVICE_NAME\>").
=> New bluetooth module

py3status/modules/pomodoro.py
Add sounds for three events. Pygame is imported tentatively in order not to introduce any hard dependency.
=> Pomodoro module: add sound support

py3status/modules/pomodoro.py
In the Pomodoro module, you now can end breaks earlier and pause an ongoing Pomodoro. Those actions are also documented so that one has not to guess how to use the module :)
=> More capabilities and documentation for Pomodoro module

py3status/__init__.py
Add module listing including a short description of each module.
Add CLI command parser for future expansion.
=> Add module listing, minor refactoring

py3status/modules/dpms.py
External processes might change DPMS so the module should check in the main loop
=> External processes might change DPMS

py3status/modules/counter.py, py3status/modules/screenshot.py
I have added two modules, counter.py and screenshot.py, read their descriptions to figure out what they do.
Basically:
* Counter count the time and calculate the service price according to taxes and price per hour configured.
* Screenshot takes screenshot (depends on gnome-screenshot, can be modified at will). It is also able to upload the screenshot to a remote server via ssh.
=> Amaury Brisou : Counter and Screenshot Modules

py3status/modules/README.md, py3status/modules/external_script.py, py3status/modules/static_string.py
Adding external_script and static_string modules and mentioning them in readme.
=> Adding external_script and static_string modules

py3status/modules/volume_status.py
I implemented a more customizable sound volume module. volume_status expands on the standard i3status volume module by adding custom colors and percentage thresholds. It also uses the normalized format style.
=> volume_status.py module

py3status/modules/keyboard_layout.py
=> Fix typos in keyboard_layout module

py3status/__init__.py
...and old school modules responses wrt issue #117
=> Fix cli available modules detection

py3status/modules/xsel.py
As discussed in #py3status on freenode here is my PR for xsel.py
=> added module xsel to display xsel buffers in py3status

py3status/modules/sysdata.py
Removing annoying spaces in `cpu_temp`
=> trim spaces in `cpu_temp`

py3status/__init__.py
Fixes bug where click events are never executes.
=> Fix poll() calls to convert from seconds

py3status/modules/keyboard_layout.py
I have made a few enhancements for the keyboard_layout module. I used xset to get the currently active layout. It doesn't work correctly if more than two layouts are configured, but since it doesn't happen in most cases, It almost resolves #33 and doesn't always require installing xkblayout-state.
I also added a better way of customizing colors, and made a few code optimizations.
=> Enhanced version of keyboard_layout module.

py3status/modules/window_title_async.py
We already have the window_title.py module, but this version provides async update for the title and uses well maintained i3 IPC library.
=> Add window_title_async.py module

py3status/modules/spotify.py
This PR adds colors to the spotify status line based on the playback status of the song.
By default, `color_good` is used when the song is playing, `color_degraded` when the song is plaused/stopped and `color_bad` when spotify is not running.
=> Add support for colors to the spotify output based on the playback status

py3status/modules/pomodoro.py
It is easer to install pyglet(pip) than pygame(sources or packages).
=> replace pygame with pyglet

py3status/modules/battery_level.py
With this simple change it is now possible to receive notifications when battery level becomes low (<30%) or critically low (<10%).
To achieve that, the following configuration parameter must be set in `.i3status.conf`:
```
battery_level {
...
notify_low_level = true
}
```
Notifications have different urgency levels, which can be used by notifications daemon to choose colors, timeouts, etc. For example, my notification daemon is configured to display "urgent" notifications in red, and they will not hide automatically, comparing to "normal" notifications.
=> Notify when battery is running low

.gitignore, .travis.yml, py3status/__init__.py, py3status/modules/battery_level.py, py3status/modules/mpd_status.py, py3status/modules/rate_counter.py, py3status/modules/screenshot.py, py3status/modules/sysdata.py, py3status/modules/window_title.py, py3status/modules/window_title_async.py, py3status/modules/wwan_status.py, tox.ini
This PR adds support for flake8 travis tests (needs to be enabled on travis-ci.org). I also addressed existing flake8 complains to make it happier.
=> Run flake8 checks on travis

py3status/modules/deadbeef.py
Show current track playing in deadbeef, available parameters are:
{artist} : artist
{title} : title
{elapsed} : elapsed time
{length} : total length
{year} : year
{tracknum} : track number
=> deadbeef module

py3status/modules/dpms.py
* added color support for output
created new PR as #186 is completly meesed up and the description of this one matches better.
=> dpms: added color support

py3status/modules/keyboard_layout.py
As mentioned on IRC the module to report current keyboard layout wasn't working properly with my specific setup. The static LED mask values were not meeting any of my layouts and while it's not taking much to edit these I'm trying to automate the process but I'm not sure if it would work for everybody.
In my specific case it works fine but I would like your input.
=> keyboard_layout module and static LED mask

py3status/i3status.py, py3status/modules/group.py
@ultrabug fix for the click issue.
basically if the items weren't initialized we crashed :(
=> Bugfix group widths when items not ready.

py3status/core.py, py3status/i3status.py, py3status/module.py, py3status/modules/group.py
=> fix group time issue #222

py3status/core.py, py3status/i3status.py
This fixes #221 
* We now force a format onto i3status so that it can easily be parsed for time offset and timezone.
* User can use any format without affecting the above
* We only update if we need to so only once a min if no %S for example
=> Time fix for #221

py3status/modules/README.md, py3status/modules/wifi.py
This makes 4 changes to the wifi module.
* add `{ip}` format option
* add `{icon}` format option, similar to battery level, showing signal strength
* tries to guess wifi device (has preference for `wlan0` which was old fixed default)
* add `{device}` format option
=> Wifi updates

py3status/docstrings.py, py3status/modules/README.md
These are the `modules/README.md` updates following the recent merges.
I found and resolved an issue with the docstring/README parsing.
Additionally fixed a bad typo.
=> Module readme update

py3status/modules/README.md, py3status/modules/group.py
I've decided the default group format is stupid and this would be an improvement
=> nicer group default format

py3status/modules/pomodoro.py
Here is the pomodoro update.  We now continue alert the user when the time is up even if the status bar is hidden.
As far as I can tell the module works identically to how it used to.  I have not tested the sound as I've not got pygame etc installed but I've not touched that part of the code.
=> pomodoro update

doc/README.md
I did a start on some documentation, feedback welcome.
=> Documentation:  Example Modules

py3status/events.py
This patch stops containers from using `on_click X` config events re #293 
I think this does what we want.
=> limit on_click config option for containers

py3status/core.py, py3status/modules/group.py, py3status/py3.py
I updated the module -> module_info
=> py3 improvements

README.rst, doc/README.md
I've added some more stuff to the docs (mainly stuff from the wiki).
Also updated the fedora `yum` to `dnf` as that is the default package manager now.
=> doc updates

py3status/modules/README.md, py3status/modules/timer.py, py3status/py3.py
The timer module was written as a composite demo, this PR:
* Plays a sound when the countdown completes if configured by user.
* Adds `time` config parameter
* Uses a Timer so i3bar can be hidden without affecting the operation. 
* Adds time module to the README
* Sound playback is via Py3 so available to other modules (uses `paplay` or `play` if available)
=> Updates to timer module allowing sound playback via py3

py3status/modules/README.md, py3status/modules/yandexdisk_status.py
This is a module for supporting [Yandex.Disk](https://disk.yandex.com/) - a cloud storage created by [Yandex](https://en.wikipedia.org/wiki/Yandex).
=> Yandex.Disk module implemented to support Yandex.Disk cloud storage

modules/twitch_streaming
Checks if twitch streamer is online or offline.
=> Proposing new module Twitch streaming

README.rst, doc/README.md
=> contributing guidelines

py3status/modules/README.md, py3status/modules/twitch_streaming.py
Updates:
* move to correct location and rename (something odd happened here)
* remove `grossie_gore` default as channel is banned
* add error if `stream_name` missing
* docstring cleanups
* minor code cleanups
=> Twitch updates

py3status/modules/README.md, py3status/modules/yandexdisk_status.py
docstring plus removed unneeded `str` cast
=> yandex updates

doc/README.md
=> fix cached_until

doc/README.md, py3status/py3.py
=> Py3 to /docs/README.md

py3status/modules/sysdata.py
The output of the `free` command varies across different
versions/implementations. So parse the contents of
/proc/meminfo instead.
Signed-off-by: Peter Mamonov <pmamonov@gmail.com>
=> modules: sysdata: get memory usage from /proc/meminfo

py3status/modules/README.md, py3status/modules/weather_yahoo.py
I noticed that the doc for this was outdated following your changes.  I also added an example config
=> Weather_yahoo docs update

py3status/modules/weather_yahoo.py
Weather_yahoo fails when connection is not available.  eg when my laptop wakes.
This PR just hides the output and tries again in 30 seconds.
=> Weather_yahoo: Prevent connectionError when network down

py3status/modules/README.md, py3status/modules/github.py
=> Github: open repo if no notifications and use button 3 for action

doc/README.md, py3status/py3.py
=> Docs: py3.prevent_refresh()

README.rst
Just to make navigation a bit easier
=> Docs: add some links to main readme

py3status/core.py, py3status/py3.py
This seemed to be the simplest way to do this without adding an extra param.  I've renamed the param to show it's new usage better.
=> notify_user: suppress restart message if module

setup.py, tox.ini
We can still use flake8 on setup.py
=> re-add setup.py to flake checks

py3status/modules/exchange_rate.py
Now that the exchange rate of my country is in free fall.
I thought an exchange rate module might be a fun way to watch the car crash.
=> Exchange rate module

py3status/modules/online_status.py
Now you can check the online status via ping.
=> Add hostname/dns support for the module online_status

doc/README.md
Add new sections to documentation.
=> Docs: module docstring and testing.

py3status/modules/sysdata.py
=> Sysdata: only care about shown info for threshold

py3status/modules/process_status.py
Just show you if a process is currently run or not.
=> Add new module process_status

py3status/modules/file_status.py
A simple module which shows you if a file or dir in your filesystem is available or not.
=> Add new module file_status

py3status/modules/kdeconnector.py
Shows information of [kdeconnector](https://community.kde.org/KDEConnect): battery status, new notifications etc.
=> Add new module kdeconnector

py3status/modules/arch_updates.py
* Re-order config params.
* Use new testing
* Docstring minor changes
I'd really like to change the `include_aur` to be boolean (default False) It would still work for people who use 0 etc as I'd change the test from `if include_aur == 0:` to `if not include_aur:`
=> cleanup arch_updates

py3status/events.py
=> find correct click events for config defined events

py3status/modules/exchange_rate.py, py3status/modules/github.py, py3status/modules/weather_yahoo.py
I've been getting notified of some occasional timeouts this PR seems to fix the issue
=> Catch timeouts

py3status/modules/rainbow.py
This is the most pointless yet most exciting module you can imagine.
Basically it allows color cycling of modules.  Imagine the joy of having the current time change through the colours of the rainbow.
If you were completely insane you could also use it to implement  the i3bar equivalent of the `<blink>` tag and cause yourself endless headaches and the desire to vomit.
=> Add module rainbow

doc/README.md, py3status/modules/group.py, py3status/py3.py
git hub made a new branch?
from #384
=> Parse format

py3status/module.py
from @pydsigner comment in #399
=> better comments for post_config_hook

py3status/modules/bitcoin_price.py, py3status/modules/imap.py, py3status/modules/spaceapi.py
This updates
* bitcoin_price:
Uses `color_index` parameter - should be fine but will want fixing
* imap:
* spaceapi
Both have colors defined as `xxx_color` in config
Anyhow these will want updating in 3.2 I have added FIXME comments to them for 3.1 they will be half done.
=> Color updates: misc

py3status/modules/battery_level.py
This is it's own PR just because it is a large change to a single module.
=> Color updates: battery_level

py3status/modules/README.md, py3status/modules/twitch_streaming.py
Couple of missing : caused rendering issues in README
=> Module twitch_streaming documentation fix

py3status/py3.py
=> Py3 formatting bugfix

py3status/modules/frame.py
python2 list has no copy() use [:] instead
Also copy the item that we are going to change.
=> Frame module has a python2 issue

py3status/modules/wwan_status.py
=> wwan_status remove print

py3status/docstrings.py
using `pys3tatus docstring update` characters `<` `>` and `&` were not being escaped very well.
This PR improves this.
Example module docstring fragment:
```
param_<something>: .... <moo> ... `<moo>`  ... 5 < 6 ... you & me
```
(github rendering affects this slightly but you get the idea)
old output to README.md
- `param_&lt;something&gt;` .... &lt;moo&gt; ... `&lt;moo&gt;`  ... 5 < 6 ... you & me
new output
- `param_<something>` .... &lt;moo&gt; ... `<moo>`  ... 5 &lt; 6 ... you &amp; me
=> py3status docstrings: Better dealing with < > & in docstrings

doc/README.md, py3status/module.py, py3status/py3.py
this is the py3.time_in() magic
=> Imporvements to py3.time_in()

py3status/modules/coin_balance.py
The 'coin_balance' module fetches the users balances of different
crypto-currencies from a user-defined server. The currently supported
coins are: Bitcoin, Dogecoin, and Litecoin. 'coin_balance' requires a
server that is compatible with the Bitcoin RPC protocol and is easily
extendable to new crypto-currencies by extending the 'COIN_PORTS'
dictionary.
=> New module: coin_balance

py3status/modules/coin_balance.py
color provided by core functionality so remove from this module
Also fixes doc to use `Format placeholders:`
=> Coin_balance: remove color param

py3status/i3status.py
=> Allow i3status modules to have custom colors

doc/README.md
=> Documentation minor updates for cached_until

py3status/modules/README.md, py3status/modules/gpmdp.py
Rendering issue
https://github.com/ultrabug/py3status/blob/master/py3status/modules/README.md#gpmdp
This fixes it and removes surplus text
=> Docstring fix for gpmdp

py3status/formatter.py
if we have the format `[\?if=condition Hello|Goodbye]`
If condition is True then we get `'Hello'`
Currently if condition is False we get `''` with this patch we get `'Goodbye'` this feels the correct behaviour and it also makes it easier to write format strings.
=> Allow else in a \?if=.. block

CHANGELOG, py3status/modules/README.md, py3status/version.py
=> version 3.1

py3status/module_test.py
There were some bugs in `module_test.py` for standalone running of modules.
* `@staticmethod` etc were not excluded from module methods to test.
* `post_config_hook()` was not excluded from module methods to test.
* `post_config_hook()` was not executed before module was tested.
* `self.items` was not set for containers.
This PR fixes these issues as well as adding some comments for clarity 
`method_name` -> `attribute_name` as that it more descriptive.
=> Fix module_test for post_config_hook staticmethods etc

tests/test_module_doc.py
The error was not very helpful, this is a bit better I think
=> improve error report on missing default value

py3status/parse_config.py
@inclementweather noted in #492 there were issues with the config parser and unicode escape sequences eg `\u0349` being used in i3status.conf.
This fix allows unicode to now be specified in the config in any of the following ways `Δ` `\N{GREEK CAPITAL LETTER DELTA}` `\U00000394`  `\u0349`
=> fix unicode escape sequences in config parsing

py3status/modules/exchange_rate.py
* Module will now cache exchange rates as sometimes we receive no data or only partial data for our query. 
* Use post_config_hook() for initialisation
=> Module: exchange_rates updates

py3status/modules/spaceapi.py
I started enjoying onclick events more and more, so I thought going to a hackerspace's website (which is in the data provided via spaceapi) might be nice.
=> Go to a space's website onclick

py3status/modules/aws_bill.py, py3status/modules/battery_level.py, py3status/modules/bluetooth.py, py3status/modules/coin_balance.py, py3status/modules/deadbeef.py, py3status/modules/fedora_updates.py, py3status/modules/frame.py, py3status/modules/glpi.py, py3status/modules/imap.py, py3status/modules/kdeconnector.py, py3status/modules/mpd_status.py, py3status/modules/mpris.py, py3status/modules/ns_checker.py, py3status/modules/nvidia_temp.py, py3status/modules/rt.py, py3status/modules/scratchpad_counter.py, py3status/modules/twitch_streaming.py, py3status/modules/whatismyip.py, py3status/modules/window_title.py, py3status/modules/wwan_status.py, tests/test_module_doc.py
The docstring tests are improved.
We now use ast to examine the module.  This allows us to test modules with unfulfilled dependencies.  It also allows the checking of the defined parameters in a module for alphabeticalness.  It also now catches unicode python2 issues.
Docstring/attribute order/unicode fixes for various modules are here to
=> Docstring test improvements and docstring updates

doc/README.md, py3status/py3.py
=> Documentation: fix typo

py3status/core.py
I happened upon some code that is never used, also no user used the default parameter so cleaned that up too.
=> cleanup get_config_attribute() remove unused code

py3status/modules/graphite.py
Master breaks due to new more precise documentation testing.
This fixes things
=> fix graphite for tests in master

py3status/modules/net_iplist.py
This PR adds a module to display the list of IP of the computer. IPs can be blacklisted by prefix. By default the loopback is blacklisted.
=> Net iplist

py3status/modules/glpi.py
There may be more useful data to pull from the database (opened/closed per time period, number closed by a user, etc.), but I'm not familiar with GLPI, so I'm just keeping the format as-is.
Working towards #98
=> GLPI: Add format

py3status/modules/rate_counter.py
Added full text format and money format.
Cost was majorly refactored.  It was previously calculated with way too much work, and would fail if timer ran over a month (it would ignore months and essentially reset to 0).
Working towards #98
=> rate_counter: Add format and majorly refactor code

py3status/modules/mpris.py
=> Fix AttributeError when click on mpris without a running player

py3status/modules/volume_status.py
I've added a new 'backend' for volume_status to use `pactl`
My main reason for this is pulseaudio allows a volume greater than 100% useful for quiet youtube videos etc.
I've added a `max_volume` parameter to control this.  @guiniol how does pamixer deal with setting volumes above 100%?  maybe you could add max_volume support for it.
=> volume_status: add pactl support

py3status/modules/backlight.py
and setting initial brightness on start !
I was frustrated that the backlight module didn't provide the functionality so I figured that it was about time I got to code again :D
=> backlight module: allow chaging brightness with mouse scroll

py3status/py3.py
`log(0)` is not something we want to do, so check that value != 0 before doing any such thing.
=> Check that value != 0 before taking the log

py3status/modules/dpms.py, py3status/modules/static_string.py
get these modules to use `safe_format()`
=> Use safe_format dpms, static_string

py3status/modules/sysdata.py, tests/test_module_doc.py
This PR adds support for the new colors/thresholds utilities.
(I removed the swap and load support from this PR and open new PRs once this one is in)
=> Sysdata: add support for colors/thresholds

py3status/modules/sysdata.py
Sysdata module cpu_usage was not working
* python2 broken due to unicode issues.  Fix this by using `Py3.command_output()`
* When a zone was given the output broke.  Fix by running output through the regex.  If the zone is bad we just use the default.  We can change this behaviour but it seems good to me maybe we should return '?'
* When we cannot get a temp we return '?' and allow this to propagate.
@guiniol it would be good if you could review this
=> sysdata: bugfix for python2 cpu_usage

doc/README.md, py3status/core.py, py3status/formatter.py, py3status/i3status.py, py3status/modules/aws_bill.py, py3status/modules/battery_level.py, py3status/modules/diskdata.py, py3status/modules/mpris.py, py3status/modules/net_rate.py, py3status/modules/player_control.py, py3status/modules/spaceapi.py, py3status/modules/vnstat.py, py3status/modules/weather_yahoo.py, py3status/modules/window_title.py, py3status/parse_config.py, py3status/py3.py, tests/test_formatter.py, tox.ini
This switches testing from flake8 to pytest-flake8 (It seems to be more thorough in its testing)
There are a bunch of whitespace fixes so that the tests pass.
sysdata still need fixes but I was going to wait till the pending changes are merged so currently ignore the current errors.
=> Flake8 fixes and testing improvements

py3status/core.py, py3status/py3.py
Currently exceptions in Py3 may not always get reported for example an error in a format.
This PR adds the ability for Py3 methods to log exceptions (where they are catching them) eg a bad format may now produce log extract like
```
2016-11-06 21:00:26 WARNING Invalid format `[[{output}]~{button}~` (Exception) frame.py line 126.
2016-11-06 21:00:26 INFO Traceback
Exception: Block not closed
File "/home/toby/dev/py3status/py3status/modules/frame.py", line 126, in frame
output = self.py3.build_composite(self.format, composites=composites)
File "/home/toby/dev/py3status/py3status/py3.py", line 564, in build_composite
attr_getter=attr_getter,
File "/home/toby/dev/py3status/py3status/formatter.py", line 318, in format
raise Exception('Block not closed')
```
We have to do a bit of magic to make …
=> Py3: _report_exception() internal helper

py3status/module.py
Some modules eg volume_status raise exceptions in post_config_hook() when things are bad.  Currently we do not handle this very well.  This PR causes such exceptions to disable the module.
=> Disable modules if post-config_hook() raises Exception

py3status/modules/xrandr.py
This change adds rotation support to the `xrandr` plugin.
=> Support Rotation

doc/example_module.py, py3status/modules/backlight.py, py3status/modules/bitcoin_price.py, py3status/modules/bluetooth.py, py3status/modules/clementine.py, py3status/modules/coin_balance.py, py3status/modules/deadbeef.py, py3status/modules/diskdata.py, py3status/modules/dpms.py, py3status/modules/exchange_rate.py, py3status/modules/file_status.py, py3status/modules/insync.py, py3status/modules/kdeconnector.py, py3status/modules/mpris.py, py3status/modules/net_rate.py, py3status/modules/netdata.py, py3status/modules/nvidia_temp.py, py3status/modules/online_status.py, py3status/modules/pingdom.py, py3status/modules/pomodoro.py, py3status/modules/process_status.py, py3status/modules/scratchpad_counter.py, py3status/modules/sysdata.py, py3status/modules/twitch_streaming.py, py3status/modules/vnstat.py, py3status/modules/vpn_status.py, py3status/modules/weather_yahoo.py, py3status/modules/whoami.py, py3status/modules/window_title.py
Fix the failing tests due to pytest-flake8 update
=> flake8 fixes for tests

py3status/modules/sysdata.py
Report memory usage in MB if total memory is less than 1GB, otherwise it is reported in GB.
Fixed bug where percent used was being rounded, which reported as "XX.00%".
Resolves #401
=> sysdata: Add dynamic memory unit

py3status/modules/imap.py
=> imap module: added starttls option

py3status/modules/selinux.py
=> selinux: fix python2 import issue

py3status/modules/rss_aggregator.py
I know, the previous version was just merged. I initially couldn't tell that I would implement ttrss so early. But I had a lot of time, so I did it. Hope you guys aren't too mad at me.
=> RSS : added Tiny Tiny RSS as available aggregator

py3status/modules/battery_level.py
On my computer the key values are named differently.
=> Support a different type of battery

py3status/formatter.py
The formatter spends approximately 20% of its time tokenizing the format string.  Seeing as we keep using the same format strings we can cache this and so reduce our overall workload.
=> cache format string tokens to reduce work done

py3status/module.py
Fixes a bug where we were updating the formats before they had been set. see #555
=> fix bug for update_placeholder_format

py3status/modules/README.md, py3status/modules/arch_updates.py, py3status/modules/imap.py
=> arch_updates: Add hide_if_zero

py3status/modules/whoami.py
This adds format: string to print (default '{username}').
=> whoami: Add format

py3status/modules/player_control.py
This adds format: string to print (default "{icon}"). 
=> player_control: Add format

py3status/modules/whatismyip.py
This documents the format placeholders.
~~Ongoing efforts to `FORMAT ALL THE THINGS!` (meme). https://github.com/ultrabug/py3status/issues/98~~  Sorry!
=> whatismyip: Add format placeholder

py3status/modules/whoami.py
This documents the format placeholders.
=> whoami: Add format placeholder

py3status/modules/taskwarrior.py
This adds format: string to print (default '{task}')
=> taskwarrior: Add format

py3status/modules/window_title.py
This adds format: string to print (default "{title}")
=> window_title: Add format

py3status/modules/online_status.py
Putting a cherry on this cake... See https://github.com/ultrabug/py3status/pull/647#issuecomment-272155209 and below. 🍰 
Sorry. I didn't know about deprecation stuffs earlier. Tested OK. 🍰 
Thanks for helping me with everything. Have another cake. 🍰 
Ongoing efforts to `PUT A CHERRY ON ALL  THE CAKES!` (meme). 🍰
=> online_status: add deprecation stuffs

py3status/modules/mpd_status.py
This fixes max_width. Thanks @tobes. Closes #636.
=> mpd_status: Fix max_width

py3status/modules/whoami.py
Putting a cherry on this cake... See https://github.com/ultrabug/py3status/pull/647#issuecomment-272158113 :cake:
Sorry. I didn't know about deprecation stuffs earlier. Tested OK. 🍰
Thanks for helping me with everything. Have another cake. 🍰
Ongoing efforts to `PUT A CHERRY ON ALL THE CAKES!` (meme). 🍰
=> whoami: add deprecation stuffs

py3status/modules/xrandr.py
=> xrandr: add deprecation stuffs

py3status/modules/uname.py
Putting a cherry on this cake... Similar purpose as `whoami`. :cake:
Sorry. I didn't know about deprecation stuffs earlier. Tested OK. 🍰
Thanks for helping me with everything. Have another cake. 🍰
Ongoing efforts to `PUT A CHERRY ON ALL THE CAKES!` (meme). 🍰
=> uname: add deprecation stuffs

py3status/modules/whatismyip.py
Added a new format option {country}, that, if present, will show ones outside location. Useful when using VPN.
Removed  the previous empty lines in the comment section, that were supposedly breaking the Readme.
=> Added geolocation support for whatsmyip.py using "ip-api.com"

py3status/modules/window_title.py, py3status/modules/window_title_async.py
=> Window without name will not crash py3status

py3status/modules/netdata.py
Closes https://github.com/ultrabug/py3status/issues/457
=> netdata: use next available nic

py3status/modules/sysdata.py
Showing memory usage is not enough.
=> Add swap support for sysdata module

py3status/modules/rainbow.py
#618 suggested a great new feature.
So now if you do 
```
rainbow {
multi_color = True
...
}
```
We have even more color.  This is such a great option I'd almost suggest defaulting it to True
=> rainbow: add multi_color option

py3status/modules/README.md, py3status/modules/sysdata.py
Ram support should be mentioned in description
=> Update sysdata documentation.

py3status/modules/keyboard_layout.py
=> keyboard_layout: use helpers

py3status/modules/hamster.py
=> hamster: use helpers

py3status/modules/taskwarrior.py
=> taskwarrior: use helpers

py3status/modules/gpmdp.py
Uses `self.py3.format_contains()`
=> gpmdp: use helpers

py3status/modules/wifi.py
Fix exception when `iw` binary is not installed.
Fix exception when `iw` can't get network interface for wireless hardware.
Python2and3 tested OK.
Partially tested... on wired hardware.
EDIT: Now uses `self.py3.format_contains()` too.
=> wifi: use helpers, fix exception

py3status/modules/github.py
This module here is somebody's baby. Tread lightly.
* Uses `self.py3.command_run()`.
* Sorted the placeholders.
* Updates the requests w/ name and description.
* Grouping things together. Omitting lines.
Let me know what to undo if any. Thanks.
**EDIT:** Github's `format`/`format_notifications` need a boob job cause it ain't perfect.
~~F~~ format should be... `'{repo} {issues}/{pull_requests}`.
~~NF~~ format_notifications should be... `'{repo} {issues}/{pull_requests}{notifications}`.
Idk if we need `{notifications_count}`. I'm asking you this.
Example: I cannot do this `py3status 32/45` --> `Github: 3`
Also, an `use_urgent` option to turn off `urgent`.
Unrelated: Maybe IMAP should get urgent and `use_urgent` option too.
**EDIT:**
* Now uses `self.py3.format_contains(self.format, …
=>   github: use helpers

py3status/modules/insync.py
Uses `self.py3.command_output()`.
Untested.
=> insync: use helpers

py3status/modules/check_tcp.py
Removes hard-coded `UP` and `DOWN`
=> check_tcp: remove hardcoded strings

py3status/modules/mpd_status.py, py3status/modules/scratchpad_counter.py, py3status/modules/vnstat.py, py3status/modules/window_title.py
closes #671 
removes code :)
I also made window_title easier to read
=> cleanup: remove transformed from module responses

py3status/modules/tor_rate.py
The tor_rate module shows the incoming and outgoing data rates of a Tor
daemon instance.
=> New module: tor_rate

py3status/formatter.py
Fix a strange unicode issue with the formatter under python2.
=> formatter fixup

py3status/modules/insync.py
Adds exception to handle something unexpected.
```
Exception: Command 'insync' had error Traceback (most recent call last):
File "__main__insync__.py", line 129, in ipc_insync
File "socket.py", line 224, in meth
error: [Errno 111] Connection refused
File "/home/chris/src/py3status/py3status/module.py", line 584, in run
File "/home/chris/src/py3status/py3status/modules/insync.py", line 51, in insync
queued = self.py3.command_output(["insync", "get_sync_progress"]).splitlines()
File "/home/chris/src/py3status/py3status/py3.py", line 710, in command_output
raise Exception(msg.format(cmd=command[0], error=error))
```
I don't know if insync daemon was running as I don't use insync myself. I apparently had insync module still running and we didn't have "isn't running" string …
=> insync: fix exception

py3status/modules/dpms.py
This adds missing `cache_timeout` 
>I quite like having button_toggle in the config
This adds `button_toggle` too.
~~EDIT: Wanted to know if I should replace `system` w/ `self.py3.command_run`.~~ Did that.
EDIT: Wanted to know if we should replace that one `system`.
=> dpms: add button_off, button_toggle, cache_timeout

py3status/modules/clementine.py
The code will need to be worked on... to take care of exceptions when clementine isn't running. Also confirmed on `master`. I can fix it later. Just for this PR, I introduces helpers.
EDIT: Closes https://github.com/ultrabug/py3status/issues/713.
=> clementine: use helpers, fix exception

py3status/modules/dropboxd_status.py
Adds `self.py3.command_output()`
Deprecates `{}`
Adds placeholder `{status}`
Add strings
* string_busy: show when Dropbox busy (default None)
* string_off: show when Dropbox unavailable (default None)
* string_on: show when Dropbox up-to-date (default None)
Adds something to take care of exception. Closes https://github.com/ultrabug/py3status/issues/717
* string_unavailable: show when Dropbox isn't installed (default 'Dropbox isn't installed!')
=> dropboxd_status: use helpers, deprecate stuffs, fix exception, add strings, bugfix. 

py3status/modules/diskdata.py
Uses `post_config_hook`. Is this okay? See `*args, **kwargs`
Uses ~~`self.py3.check_commands`~~ `self.py3.command_output`
Adds `self.py3.clarify`, closes https://github.com/ultrabug/py3status/pull/743.
~~I feel there may be a bug. I receive err string,  `all:   err% (  4.0 KiB/s)`, with `df` output:~~
_── CODE OMITTED ──_
_── CODE OMITTED ──_
Wrong `self.py3` command.
=> diskdata: add clarification, use more helpers

py3status/modules/keyboard_layout.py
> \_\_init_\_() use should be discouraged
Discouraged...
Python2and3 OK.
=> keyboard_layout: streamline

py3status/modules/nvidia_temp.py
EDIT: Closes https://github.com/ultrabug/py3status/issues/699. 
EDIT: Closes https://github.com/ultrabug/py3status/issues/754.
This adds format: string to print (default 'GPU: {format_temp}')
This adds format_temp: string to print (default '{temp}°C')
This adds ~~format~~ string_unavailable: string to print if unavailable (default 'N/A')
I didn't test Unavailable (How?)
I didn't test format_separator (Extra GPU required).
Will break. Hold this for v3.4 or what?
=> nvidia_temp: add format, use helpers

py3status/modules/imap.py
Comcast outage or service down again? Typical.
~~With `hide_if_unavailable`, this hides `N/A` not leaving you pondering what module `N/A` was for.~~
=> imap: add depreciation stuffs 

py3status/modules/wifi.py
=> wifi: fix device autodetection magic

py3status/events.py
this should fix #774 
I'm not sure if there is also another issue related to clicks but I need to test more first.
=> Prevent an attribute error

py3status/modules/imap.py
=> imap: allow_urgent on unread messages

py3status/modules/nvidia_temp.py
Adds try/except to fix an exception I ran into. Closes https://github.com/ultrabug/py3status/issues/764
=> nvidia_temp: fix exception

py3status/modules/netdata.py
=> netdata: optimization no.2

py3status/module.py
fix for #632 at least for non-composite modules
=> fix issue with blank module causing extra separator to show

py3status/modules/pingdom.py
This adds format: string to print (default '{output}').
UNTESTED.
=> pingdom: add format

py3status/modules/bluetooth.py
hcitool is deprecated (bluez-5.44) so it is better to use the dbus library directly
=> [bluetooth module] hcitool is deprecated (bluez-5.44) so it is better to use the dbus library directly

py3status/modules/rainbow.py
This adds format: string to print (default '{rainbow}')
Pretty ugly, but w/e. 
=> rainbow: add format

py3status/docstrings.py
Going for a series of small PRs
Cleanup code and improve the reg_ex.  The old reg_ex would view `-1` as the start of a bullet point which is incorrect.
=> documentation I (cleanup)

py3status/exceptions.py, py3status/py3.py
Update docstring in Py3 to use .rst so we can auto document them
We also document constants and exceptions
=> documentation III (update docstrings)

py3status/modules/spaceapi.py
This adds format: string to print (default '{spaceapi}')
Hmm. I forget. Too many branches. 😆 🤣 
=> spaceapi: add format

py3status/modules/bitcoin_price.py
I added format ~~Due to json or code, I made this more customizable than before... by replacing hardcoded strings w/ options.~~ correctly.
Default: `btce: 911.30$, btcde: 871.71€`
~~Can customize/omit colon, comma, unavailable, unreachable~~
* ~~format: display format for this module (default '{bitcoin}')~~
* ~~string_separator1: first separator (default ': ')~~
* ~~string_separator2: second separator (default ', ')~~
* ~~string_unavailable: no price (default 'N/A ')~~
* ~~string_unreachable: no connection (default 'Bitcoincharts unreachable')~~
* format: display format for this module (default '{format_price}')
* format_price: display format for prices (default '{market}: {price}{symbol}')
This adds Format placeholders:
* {format_price} format for bitcoin prices
This adds format_price …
=> bitcoin_price: add format

doc/configuration.rst, doc/contributing.rst, doc/intro.rst, doc/writing_modules.rst
The main hand written documentation.
Most of this is just the current pages converted to .rst
`intro.rst` is probably the only one to really care about as it is 'new' stuff.
I think we can improve the docs from this base.
as with the documentation I-V this is independent of the other PRs
=> documentation VI (general pages)

py3status/modules/keyboard_locks.py
=> keyboard_locks: fix typo error

py3status/modules/getjson.py
=> [getjson] Fixing typo

py3status/modules/window_title.py
We don't need `post_config_hook` for this one.
=> window_title: remove __init__

py3status/modules/arch_updates.py, py3status/modules/battery_level.py, py3status/modules/clock.py, py3status/modules/coin_balance.py, py3status/modules/github.py, py3status/modules/group.py, py3status/modules/kdeconnector.py, py3status/modules/mpd_status.py, py3status/modules/pomodoro.py, py3status/modules/twitch_streaming.py, py3status/modules/volume_status.py, py3status/modules/vpn_status.py, py3status/modules/xrandr_rotate.py
Make modules slightly more same-same. Little fix that I want to merge.
https://gfycat.com/DelayedConsciousGilamonster
=> Same same but different  

py3status/formatter.py, tests/test_formatter.py
@valdur55 found a bug in the formatter around NoneColors this fixes it and adds a new test to the formatter
=> prevent NoneColor breaking formatter

py3status/modules/group.py
Uses `self.py3.format_contains(self.format, 'kiwi_fruit')` Hassle-free PR. 🥝
=> group: use helpers

py3status/modules/online_status.py
Reviving an issue that was closed, abandoned, left for dead, and almost forgotten: https://github.com/ultrabug/py3status/pull/696.
=> online_status: use helpers

py3status/modules/mpris.py
Reoganised mpris module code and str(item.get('color')) is needed to overcome this issue:
> 'NoneColor' object does not support indexing
Fix #707
=> Mpris module is now working. Fix #707

py3status/modules/mpris.py
=> Do not ask application name/full_name when we know  this player already.

doc/contributing.rst, doc/doc-requirements.txt
how to build documentation etc
=> documentation XII (development updates)

README.rst
Start using the new documentation.
=> documentation XIII (README.rst use readthedocs)

py3status/modules/deadbeef.py
I deprecate `delimiter`. Fucking stupid. Go for easy life.
We use `record separator` and `group separator` now.
We keep `{placeholders}` for easy access.
I rewrite placeholder descriptions for easy readability.
I omit `{isplaying}` and add `{album}`.
DEADBEEF IS FINALLY BACK FROM DEAD! 💀 🍗
=> deadbeef: support 25+ external placeholders

doc/intro.rst
Looking forward to use the new docs (as I'm still using old ones from visited history). 👍
=> doc/intro: fix typo error

py3status/modules/uptime.py
fixes docstring indentation.
For 3.6 I'm going to update the docstring processing to simplify things and will add tests for compliant rst generation from them.
=> uptime: fix docstring indentation

py3status/modules/whatismyip.py
This is what @lasers asked in #819.
=> [whatismyip] Define `icon_*` params instead of `format_*`

py3status/modules/aws_bill.py, py3status/modules/bitcoin_price.py, py3status/modules/clock.py, py3status/modules/group.py, py3status/modules/kdeconnector.py, py3status/modules/mpris.py, py3status/modules/online_status.py, py3status/modules/player_control.py, py3status/modules/pomodoro.py, py3status/modules/rate_counter.py, py3status/modules/spotify.py, py3status/modules/twitch_streaming.py, py3status/modules/vnstat.py, py3status/modules/volume_status.py, py3status/modules/weather_yahoo.py, py3status/modules/whatismyip.py, py3status/modules/xrandr.py, py3status/modules/xscreensaver.py
I'm looking at improving our module docstring parsing.
As part of this these trivial cleanups have been identified.
=> module docstring trivial updates

py3status/modules/keyboard_locks.py, py3status/modules/netdata.py, py3status/modules/rainbow.py, py3status/modules/xscreensaver.py
some updates to module screenshots
plus missing color options for xscreensaver
=> updates to some module screenshots

py3status/modules/getjson.py
We like the format. Uses `self.py3.safe_format(self.format)`. Hassle-free PR. 🍉
=> getjson: add safe_format for None

py3status/modules/clock.py, py3status/modules/weather_yahoo.py
=> bugfix yahoo_weather and clock

py3status/module.py
#848 Spam the logs less when we cannot import a module
=> reduce the noise when we cannot import a module that does not exist

py3status/modules/bitcoin_price.py
Same deal with `bluetooth: add safeformat for the separator` PR.
This adds safeformat for the seperator. `format_separator = '[\?color=#f00&show \| ]'`
Couple of lines realigned to fit under 80 column.
=> bitcoin_prices: add safeformat for the separator

py3status/modules/bluetooth.py
This adds safeformat for the seperator. `format_separator = '[\?color=#f00&show  \| ]'`
Couple of lines realigned to fit under 80 column.
=> bluetooth: add safeformat for the separator

py3status/modules/selinux.py
* Remove command checking -- Fix #957 
* Use `color_degraded` in permissive mode -- Feature
* Style nitpicking for consistency with other modules.
=> SELinux: Remove command checking; Use color_degraded in permissive mode; Style nitpicking

py3status/i3status.py
from issue #948 this now reports a better error to the user when i3status is missing.
It is very simplistic we could do a `which i3status` to confirm but that feels overkill for now
Better logging of i3status spawning (when it has)
removed some unneeded bits from mocking
=> i3status missing better reporting

py3status/command.py
realised the button numbers were incorrect
=> fix button names

py3status/formatter.py, py3status/modules/net_rate.py, py3status/py3.py
From #935 make `hide_if_zero` work.
A new py3 helper is added to allow us to get the needed info.
=> make hide_if_zero work for net_rate

py3status/modules/apt_updates.py
This adds a module for monitoring updates available as listed by apt. It is based on the updates module for pacman / aur for arch linux.
=> Added apt updates module

py3status/py3.py
This one could use a better report on the output of the command if available
+ some minor QA
=> py3.command_output normalized and enhanced error reporting

py3status/modules/volume_status.py
thanks to yabbes for reporting
=> volume_status allow device as a int

py3status/core.py
Whilst looking at #987 I found that `report_exception()` is not available as early as it is needed.  this PR allows us to use it much earlier in the process. To be honest I think this predates the Common code changes.
We also output the traceback to `stderr` if logging options are not set so that we can see the traceback in the cli
=> allow report exception to be available early

py3status/module.py, py3status/modules/group.py
#859 should be fixed by this.
I can't reproduce the issue but looking at the code this makes sense as to why we get the traceback @lasers reported there.
=> fix group width issue when no output

py3status/modules/graphite.py
Remove extra default from docstring
=> graphite: docstring fix [TRIVIAL]

py3status/modules/group.py
Exception... Due to `current = []`.
```
IndexError: list index out of range
File "/home/chris/src/py3status/py3status/module.py", line 747, in run
File "/home/chris/src/py3status/py3status/modules/group.py", line 218, in group
current_output = self._get_output()
File "/home/chris/src/py3status/py3status/modules/group.py", line 180, in _get_output
current[0]['full_text']
```
Indentation... Just a lucky gotcha.
=> group: fix an exception, an indentation

py3status/modules/dropboxd_status.py
We make `post_config_hook` for `dropbox`. Performance tweak.
=> dropbox: use post_config_hook

py3status/modules/nvidia_temp.py
We make `post_config_hook` for `nvidia_temp`. Performance tweak.
=> nvidia_temp: use post_config_hook

py3status/modules/process_status.py
We move one thing to `post_config_hook`. Performance tweak.
EDIT: On second thought, let's not make everything same.
EDIT: Nah. Forget it... They're pretty much same.
=> process_status: use post_config_hook

py3status/modules/yandexdisk_status.py
We make `post_config_hook` for `yandexdisk_status`. Performance tweak.
=> yandexdisk_status: use post_config_hook, use py3.error

py3status/modules/volume_status.py
=> volume_status: None defaults for the buttons

py3status/modules/battery_level.py
The time feels right to make this pull request. ⏲
=> battery_level: use time_in

py3status/modules/weather_yahoo.py
We make `post_config_hook` for `weather_yahoo`. EDIT: Performance tweak.
=> weather_yahoo: use post_config_hook

py3status/modules/rate_counter.py
Cleans up the module configuration which is nice for testing/documenting.
=> rate_counter: better directory handling

py3status/modules/screenshot.py
Cleans up the module configuration which is nice for testing/documenting.
=> screenshot: better directory handling

py3status/core.py
We can make things slightly more efficient in processing the module's output
=> process_module_output() improvements

py3status/modules/fedora_updates.py
~~Consistency is good.~~ Consistency can be good.
=> fedora_updates: remove old docstring

py3status/modules/volume_status.py
We add  a new config parameter for amixer card. This fixes https://github.com/ultrabug/py3status/issues/927.
@zhenyangze If it's not too much, let us know if this works out great. Thanks. :-)
=> volume_status: add card param for amixer

py3status/modules/mpd_status.py
=> fix #1090 (mpd_status creates a new socket connection every second)

py3status/modules/getjson.py
We make nice and unnecessary `post_config_hook` for `getjson`.
=> getjson: use post_config_hook

py3status/modules/README.md, py3status/modules/air_quality.py, py3status/modules/apt_updates.py, py3status/modules/arch_updates.py, py3status/modules/bitcoin_price.py, py3status/modules/bluetooth.py, py3status/modules/coin_balance.py, py3status/modules/coin_market.py, py3status/modules/deadbeef.py, py3status/modules/exchange_rate.py, py3status/modules/fedora_updates.py, py3status/modules/frame.py, py3status/modules/github.py, py3status/modules/graphite.py, py3status/modules/group.py, py3status/modules/i3block.py, py3status/modules/insync.py, py3status/modules/net_iplist.py, py3status/modules/rainbow.py, py3status/modules/tor_rate.py, py3status/modules/twitch_streaming.py, py3status/modules/vpn_status.py, py3status/modules/weather_yahoo.py, py3status/modules/wwan_status.py
Make modules slightly more consistent. Little fix that I want to merge before the `3.6` release.
Ekk! 46+ lines... Quality over quantity? 😕
=> modules: make docstrings consistent

py3status/modules/uptime.py
We use `loop` and `dict` instead of `multiple if-statements` to annihilate the lines. 😮
=> uptime: annihilate the lines

py3status/modules/volume_status.py
@lasers ho hum
fixes things that got broken by changes made for the sake of making changes
and no testing done I think
=> fix volume_status

py3status/modules/volume_status.py
I broke some. I fix some. :-)
```
... /py3status/modules] master(+2/-0)+ ± python3 volume_status.py
{'full_text': '♪: 10%', 'color': '#FF0000', 'cached_until': 1509281140.0}}
{'full_text': '♪: 5%', 'color': '#FF0000', 'cached_until': 1509281142.0}
{'full_text': '♪: 4%', 'color': '#FF0000', 'cached_until': 1509281353.0}
{'full_text': '♪: 3%', 'color': '#FF0000', 'cached_until': 1509281355.0}
{'full_text': '♪: 2%', 'color': '#FF0000', 'cached_until': 1509281356.0}
{'full_text': '♪: 1%', 'color': '#FF0000', 'cached_until': 1509281357.0}
Command '['pamixer', '--sink', '0', '--get-volume']' returned non-zero exit status 1. (CalledProcessError) module.py line 729.
Traceback
CalledProcessError: Command '['pamixer', '--sink', '0', '--get-volume']' returned non-zero exit status 1.
File …
```
=> volume_status: (pamixer) throws error on zero percent

py3status/i3status.py
` update_times()` was dead code so removed
we need to also need to know the update interval to know if we are late or not.
=> fix summertime bug (hopefully) and some related time module cleanups

py3status/py3.py
https://github.com/ultrabug/py3status/pull/1089 leaves the `command` string untouched if `shell` is `True`. When a `retcode` error occurs, it prints the first char (of the string) instead of the first element (of the list) in the log. Minor bugfix.
```
self.py3.command_output('mocp --info', shell=True)
CommandError: Command `m` returned non-zero exit status -6 (State: PLAY )
```
=> py3: print full command in the error logs

py3status/request.py
=> Make POST requests work

py3status/parse_config.py
Duplicate code in two places of parse_config can be simplified into one helper function!
=> Small refactor for parse_config.py

py3status/modules/volume_status.py
=> volume_status: add boost for pamixer

py3status/modules/cmus.py, py3status/modules/google_calendar.py, py3status/modules/insync.py, py3status/modules/keyboard_locks.py, py3status/modules/tor_rate.py, py3status/modules/weather_owm.py
For `3.7.1` or `3.8` or `whatever`. I fixed column for `google_calendar` too.
=> quick consistency/cleanup fixes

py3status/modules/bitcoin_price.py
We use the nice method `self.py3.request` here.
=> bitcoin_price: use helpers

py3status/modules/timer.py
=> timer: add urgent

py3status/modules/xrandr_rotate.py
Salut. Comment allez-vous? Quand je rendais ce module plus sympa ... j'ai remarqué quelque chose ... L'icône ne se met pas à jour. Après l'avoir regardé, le correctif est simple ... Dès que `self.displayed` obtient quelque chose, nous cessons de laisser l'icône se mettre à jour.
Cela maintenant le fixe. L'icône se mettra à jour en conséquence ... et sur les clics aussi.
@maximbaz This updates the icon and will respond to refresh `on_click` too. Test it? :relaxed:
=> xrandr_rotate: refresh properly

py3status/modules/keyboard_layout.py
#1179 seemed a great idea and also something that I would use
Here is a quick implementation
=> allow selection of keyboard layout

py3status/__init__.py, py3status/cli.py, py3status/core.py
This is the start of some general cleanups.  As can be seen there are some FIXMEs but I want to keep this PR as simple as possible with the minimum of code change.
=> move arg parsing to own file to help decouple stuff

py3status/modules/wifi.py
We do the `use_sudo` thing once in `post_config_hook` for all commands. Minor performance tweak. And we update the docs with missing `sudoers` entry for `ip addr show` which is used only for `{ip}` placeholder.
=> wifi: use sudo in post_config_hook

doc/contributing.rst
Closes https://github.com/ultrabug/py3status/issues/1038.
=> docs: add profiling section

doc/writing_modules.rst
I happened to have my spelling checker turned on and found these
=> typo fixes

py3status/modules/exchange_rate.py, py3status/py3.py
New feed as Yahoo api no longer available see #1174
Also makes `update_placeholder_formats()` available to modules
precission has been lowered due to the data being old and so less accurate so this seems appropriate
=> exchange_rates: use new feed

py3status/modules/netdata.py
We remove `class GetData` and some things to annihilate the lines. Same output.
(Q) What do you think about fixing this up with loop?
The users can have more than 1 interface, eg laptop with wifi and ethernet. Seeing an interface slower than the another interface could be useful in knowing which interface they are using when watching Netflix and/or other data-heavy activities.
For most users, this should not be a problem as they're going to have only 1 interface.
If we do this, I wonder if we should harvest `nics` on every loop since users could play with ethernet any time... and wifi connection can be disconnected / connected from time to time too. Anyhow, you're the one with the laptop... I asked because `psc` code stops on first `nic` card with `000000` gateway. Let me know. Thx.
=> netdata: annihilate the lines

py3status/modules/wifi.py
Closes https://github.com/ultrabug/py3status/issues/1231. Thanks for the report! @maximbaz
=> wifi: set after, not before

py3status/modules/external_script.py
We make nice `post_config_hook` for `external_script`.
=> external_script: use post_config_hook

py3status/modules/external_script.py
Incinerates https://github.com/ultrabug/py3status/pull/1083.
=> external_script: fix indexerror exception

py3status/modules/net_rate.py
Removing `__init__`. Moving things to `post_config_hook` for net_rate.
=> net_rate: use post_config_hook

py3status/modules/sysdata.py
Simplifying sysdata one pull request at a time. First thing first, I remove `class GetData`.
=> sysdata: remove class getdata

py3status/modules/sysdata.py
Zip this one too. :zipper_mouth_face:
=> sysdata: zip up the mem stuffs

py3status/modules/deadbeef.py
=> fix deadbeaf error

py3status/modules/sysdata.py
I address cpu stuffs.
* Rename `_get_cpu` to `_get_stat`. This gets kernel/system statistics.
* Replace 17 lines with a link.
* Make new `calc_cpuinfo` to make it more readability.
* * Currently a basic function.... Could be expanded later like `mem` and eventually `swap`.
* Return a dict because it is possible somebody want to add per-cpu percents too one day.
Small PRs gets things done! :-)
=> sysdata: clean up stat, make new cpuinfo

py3status/modules/group.py
Cleans up the group code for #1246 as the group can then run before modules.  This allows the group module to wait an amount of time for module output before using other content.
The default is 5 seconds and I think not having it user set is fine
=> group: allow waiting for active module

py3status/modules/spotify.py, py3status/modules/xrandr.py
Add click events to Spotify module to support : 
- PlayPause
- Next song
- Previous Song
Those are configured in the i3status.conf file
=> Spotify click event

py3status/modules/pomodoro.py
Make the status bar strings for the pomodoro module more customizable
=> Customiziable pomodoro strings

py3status/modules/sysdata.py
I test everything once in the `post_config_hook` and I remove noisy comments.
=> sysdata: post_config_hook initializations

py3status/modules/taskwarrior.py
=> taskwarrior: post-merge QA, use post_config_hook

py3status/modules/README.md, py3status/modules/xscreensaver.py
E-mail address does not exist anymore.
Please and thank you
=> Please remove my email from the project

py3status/modules/keyboard_locks.py
Merging all `icon_*` config parameters into the `format` config parameter.
=> keyboard_locks: merge formats

py3status/modules/imap.py
sorry, I seem to have missed that.
=> fix travis whitespace error

CHANGELOG
`CHANGELOG 3.8`. I removed typos commits, screenshot pain commits, little correction commits, extraneous commits, feedback commits, etc. This is what I'm left with right now.. Currently at 99 lines.
=> add changelog 3.8

py3status/modules/backlight.py
Because #1077 [is not in master and not in 3.8](https://github.com/ultrabug/py3status/pull/1077#issuecomment-377995471) 😞 
/cc @ultrabug
=> Reintroduce PR #1077

doc/configuration.rst
as requested by @ultrabug some documentation for the new `shell(...)` expressions. See also #1331 
let me know if this is ok or needs work
=> documentation for shell(...)

py3status/modules/bitcoin_price.py
Updated the request url to use HTTPS as opposed to just HTTP, since the api supports HTTPS requests.
=> bitcoin_price: Changed request url from http to https

py3status/modules/keyboard_layout.py
This is for @inigoserna's #1332.
=> keyboard_layout: add variants

py3status/core.py, py3status/module.py
Reverts ultrabug/py3status#1353
This breaks click events
=> Revert "Module simplify"

py3status/core.py, py3status/py3.py
Hi,
I find this missing and need it.
Will use it for my modules next.
=> notify_user: add dbus title and icon modification

py3status/modules/sysdata.py
Make use of the `py3.format_units` helper function for sysdata/mem units.
=> sysdata/mem: use py3.format_units

py3status/py3.py
=> py3: fix hardcoded soft=True argument

py3status/modules/sql.py, tests/test_module_doc.py
Hi. This is a new module made by **@Cereal2nd** in #1303. I added support for multiple rows.
=> sql: add new module, add support for multiple rows

py3status/modules/sysdata.py
This is lot of codes just to rename one placeholder. This will help with simplifying `thresholds` next.
=> sysdata: rename cpu_usage to cpu_used_percent

py3status/modules/gitlab.py
Hi guys,
I hope the family is fine!
A little addon to gitlab module.
A quick PR to add global pipeline status for a Gitlab project.
(congrats @lasers 🎊 !)
=> [gitlab] add pipelines status placeholder

py3status/py3.py
Addresses #1281 **Feature 2**: A solution for internal thresholds.
I'm being formal by tagging stars on many things that happens outside of modules.
Often, there are no review. Should I go ahead and merge them or wait for a review first?
=> py3: threshold_get_colors to allow name with different values

py3status/modules/lm_sensors.py
=> lm_sensors: fix the docs

MANIFEST.in, fastentrypoints.py, setup.py
Addresses https://github.com/ultrabug/py3status/issues/1195
=> setup: add fast-entry_points

py3status/modules/wwan.py
Hi @cyrinux, I updated `wwan` with new py3 method. Need you to double check this. :blush:
=> wwan: use py3.get_color_names_list helper

py3status/module.py
=> module: fix universal module options for python2

py3status/parse_config.py
Addresses https://github.com/ultrabug/py3status/issues/1323.
Because I ran into this too, I was able to come up with a diff.
Ideal? I dunno. Good enough? Yes.
=> parse_config: fix lookuperror exception

py3status/module.py
Trust, but verify... I slice this off #1436 so you can have easier time looking through the changes.
=> module: verify whether min_width is an integer

py3status/module.py
Nesting `align` if statement inside `min_width` if statement to reduce unnecessary work.
I slice this off #1436 so you can have easier time looking through the changes.
=> module: nest align if statement inside min_width if statement

doc/configuration.rst, doc/py3-cmd.rst
Addresses https://github.com/ultrabug/py3status/issues/1245 with this PR and new `py3-cmd` docs.
=> docs: write down the button numbers

py3status/modules/air_quality.py, py3status/modules/aws_bill.py, py3status/modules/bitcoin_price.py, py3status/modules/bluetooth.py, py3status/modules/clementine.py, py3status/modules/deadbeef.py, py3status/modules/getjson.py, py3status/modules/glpi.py, py3status/modules/gpmdp.py, py3status/modules/online_status.py, py3status/modules/rt.py, py3status/modules/spaceapi.py, py3status/modules/taskwarrior.py, py3status/modules/twitch.py, py3status/modules/weather_owm.py, py3status/modules/weather_yahoo.py
=> modules: replace http with secure https

py3status/modules/timer.py
Removing unnecessary func in favor of `format()`.
=> timer: replace make_2_digit with format

py3status/modules/air_quality.py, py3status/modules/arch_updates.py, py3status/modules/cmus.py, py3status/modules/github.py, py3status/modules/google_calendar.py, py3status/modules/group.py, py3status/modules/moc.py, py3status/modules/netdata.py, py3status/modules/nvidia_smi.py, py3status/modules/spotify.py, py3status/modules/weather_owm.py, tests/test_module_doc.py
Starting over with a clean state for several modules.
=> test_module_doc: fix modules to remove all ignore items 

doc/configuration.rst, py3status/storage.py
Addresses https://github.com/ultrabug/py3status/issues/1361
=> storage: use $XDG_CACHE_HOME or ~/.cache (+many more)

py3status/formatter.py, tests/test_formatter.py
So this is an improvement on #1333 that actually cares about the format rather than randomly guessing what might be important.
I've added code to allow the `update_placeholders()` functionality to also update used params as that makes sense but is most of the code.
I added some testing for these functions too but they are fairly basic but good to have
=> allow us to get params from formats and also update them

py3status/modules/nvidia_smi.py
=> nvidia_smi: add missing degree celsius

py3status/formatter.py
clean version of #1440 
We can do the same nicer
=> formatter: catch both lonely braces

py3status/modules/fedora_updates.py
fix broken module plus also more responsive startup
=> fedora-updates: fix issue caused by lack of testing

py3status/modules/timewarrior.py
> no time like the present, there's
=> timew: fix future bug caused by copy and paste

py3status/formatter.py, tests/test_formatter.py
#1468 found an issue 
@lasers so yeah I found it and fixed it
usbguard code made me want to throw up though - it needs a full rewrite imho or at least comments explaining what the fuck it is up to
=> fix empty seeming composite block issue

py3status/py3.py
commit ea1a126e cause a BOM (byte order mark) to be added to `py3.py` which broke the documentation build.  This fixes it.
I've checked the other python files in master and all seem ok but we should do some cleanups and test around this issue as we have a bit of a mess
__before__
```]$ /usr/bin/printf "\ufeff...\n" | file - ../py3status/*.py
/dev/stdin:                              UTF-8 Unicode (with BOM) text
../py3status/autodoc.py:        Python script, ASCII text executable
../py3status/cli.py:            Python script, ASCII text executable
../py3status/command.py:        Python script, ASCII text executable
../py3status/composite.py:      Python script, ASCII text executable
../py3status/config_updates.py: Python script, ASCII text executable
../py3status/constants.py:      ASCII …
```
=> Urgent: fix BOM related documentation breakage

py3status/parse_config.py
fix broken py3status.  return value instead of `None`. EDIT: untested pr #1484
=> parse_config: fix issue caused by lack of testing

doc/configuration.rst
Make unrelated changes/correction to the docs.
=> docs: make unrelated changes/corrections

py3status/modules/sysdata.py
This introduces a new option `mem_htop` to print `htop`-like values for `{mem*` placeholders.
* I'd like your opinions on replacing this without a config.
* I'd like your opinions on defaulting this new option.
Addresses #666.
=> sysdata: add htop-like memory usage

py3status/modules/sysdata.py
This fixes IndexError exception with `swap` placeholders. We forget to try swap too.
```python3
list index out of range (IndexError) module.py line 766.
Traceback
IndexError: list index out of range
File "py3status/py3status/module.py", line 766, in run
File "sysdata.py", line 294, in sysdata
self.init['mem'], self.init['swap']
File "sysdata.py", line 233, in _get_mem
"SwapTotal:", "SwapFree:"]
File "sysdata.py", line 207, in _calc_mem_info
cached_mem_kib = memi[keys[3]] + memi[keys[5]] - memi[keys[4]]
```
=> sysdata: fix swap indexerror exception

py3status/modules/timewarrior.py
Reverts ultrabug/py3status#1517
we are in a code freeze!
=> Revert "timewarrior: pass action/id index"

.travis.yml, setup.py
This adds Python 3.7 trove classifier.
=> setup.py, travis.yml: add python 3.7 support

py3status/docstrings.py, py3status/screenshots.py
This is a cleanup of `screenshots.py` and also a minor fix for `docstrings.py`
* comment/docstring typo fixes and clarifications
* fix `# noqa` issues
* `module` -> `is_module` parameter rename for clarity
* improvements to code with broken screenshot data handling
Maybe this should be as multiple PRs but as this is a single feature module and overall the changes are small I've done like this.
I can refactor if requested
=> clean and improve screenshots generation

py3status/py3.py
Addresses #1281 **Feature 1**: Support strings.
=> py3: add threshold string support

py3status/docstrings.py
=> Print module information to sdtout instead of stderr

py3status/modules/battery_level.py
=> battery_level: Default to using sys instead of acpi

py3status/modules/imap.py
Essentially, whenever I booted into i3, for a short time (until the network was available), 'mail: None' was displayed. This fixes both the fact that it should be 'mail: N/A' and also delays displaying it when using IDLE (so the behaviour is the same compared to polling mode)
=> [BUGFIX] module imap: fix output formatting issue

py3status/modules/arch_updates.py
Use [yay](https://github.com/Jguer/yay) as an alternative to query the number of AUR updates.
=> arch_updates: alternatively use yay for AUR check

py3status/modules/deadbeef.py
Improving Deadbeef breaks our module. :-) This should addresses #1580.
=> deadbeef: return deadbeef data without error codes

py3status/modules/wifi.py
This exports wifi frequency in Mhz and Ghz.
=> Export wifi frequency

py3status/modules/vnstat.py
Replace deprecated `--exportdb` with `--oneline b` (bytes). This addresses #1568.
EDIT: ..........................
`--exportdb` got deprecated. We need to fix this.
```
$ vnstat --exportdb | grep -i 'd;0'   # 'd;0' for first day, 'm;0' for first month
d;0;1541417662;334;19;58;963;1
```
I went with `--oneline` because it looks like a good fix. `--json` would give us more.
```
$ vnstat --oneline
1;eno1;11/05/2018;334.06 MiB;19.94 MiB;354.00 MiB;69.77 kbit/s;Nov '18;334.06 MiB;19.94 MiB;354.00 MiB;7.25 kbit/s;334.06 MiB;19.94 MiB;354.00 MiB                               
```
```
--oneline
Show  traffic  summary  for  selected  interface  using one line with a
parseable format. The output contains 15 fields with ;  used  as  field
delimiter. The 1st field contains the version information of …
```
=> vnstat: replace deprecated --exportdb with --oneline

py3status/modules/mail.py
Iterating to resolve a KeyError exception.
=> mail: validate mailboxes, names to avoid collisions

py3status/modules/mail.py
>@L0ric0 This allows the mail module to check for new mail in IMAP-subfolders and not only in INBOX. Useful when automatically sorting mail.
This replaces https://github.com/ultrabug/py3status/pull/1541.
=> mail: add imap subscriptions to filter mailbox folders

py3status/modules/velib_metropole.py, py3status/py3.py
Hi guys,
A new module for shared velib bike in Paris.
Working version.
PR following https://github.com/ultrabug/py3status/issues/1512
Waiting for comment.
ps: When pybikes will be python3 compliant (https://github.com/eskerda/pybikes/pull/284) I will do generic shared bikes modules.
😗
=> New module: Velib metropole

py3status/modules/do_not_disturb.py
We can merge #1371 first then I rebase on top of it... To preserve authorship history and whatnot.
=> do_not_disturb: new module from scratch

py3status/constants.py, py3status/parse_config.py
=> notify users of obsolete module and their alternatives

doc/intro.rst
py3status is in the official repos, so should use `pacman`
=> Update Arch installation instructions

py3status/modules/do_not_disturb.py
=> do_not_disturb module: fix pause logic hiding startup notifications

doc/contributing.rst
Talked to @ultrabug and proposed to try this workflow.
Approve if you agree, comment if you have concerns 😉 
/cc @ultrabug, @tobes, @lasers.
=> Update contribution guidelines

py3status/modules/apt_updates.py, py3status/modules/arch_updates.py, py3status/modules/async_script.py, py3status/modules/bitcoin_price.py, py3status/modules/diskdata.py, py3status/modules/dropboxd_status.py, py3status/modules/fedora_updates.py, py3status/modules/glpi.py, py3status/modules/i3block.py, py3status/modules/icinga2.py, py3status/modules/imap.py, py3status/modules/mega_sync.py, py3status/modules/mpd_status.py, py3status/modules/net_iplist.py, py3status/modules/pingdom.py, py3status/modules/rate_counter.py, py3status/modules/rss_aggregator.py, py3status/modules/rt.py, py3status/modules/taskwarrior.py, py3status/modules/twitch.py, py3status/modules/volume_status.py, py3status/modules/vpn_status.py, py3status/modules/yandexdisk_status.py, tests/test_method_mismatch.py
Consistency is so hard to maintain...
=> modules: normalize main methods

tests/test_method_mismatch.py, tox.ini
also fix related test misformat
found this while checking out last PR...
=> fix black check mode which should fail the CI if reformatting is needed

py3status/modules/pingdom.py
Please confirm your work history.
=> pingdom: add author ultrabug

py3status/modules/do_not_disturb.py
Extracting from https://github.com/ultrabug/py3status/pull/1638#discussion_r247782220
=> dnd: simplify dunst logic

py3status/modules/exchange_rate.py
Make it rain. $$$$. :dollar: :heavy_dollar_sign: :moneybag: :money_with_wings: :money_mouth_face: 
Addresses #1569.
=> exchange_rate: change feed to exchangeratesapi.io

doc/configuration.rst, py3status/modules/systemd.py
Hi guys,
here a quick improvement for systemd module + black linting
=> systemd: add possibility to check user/session systemd unit

py3status/cli.py, py3status/core.py
=> remove obsolete cli interval argument

py3status/modules/conky.py
Hi. I made a new module `conky`. This module is too good to pass up sharing with py3status.
>Conky has more than 250 built  in  objects,  including  support  for  a plethora  of OS stats (uname, uptime, CPU usage, mem usage, disk usage, "top" like process stats, and network monitoring, just to name a  few), built in IMAP and POP3 support, built in support for many popular music players (MPD, XMMS2, BMPx, Audacious), and much much more.
_display ip address_
_display load averages_
_exec commands at different intervals, eg 5s, 60s, and 3600s_
_display diskio read, write_
_display total number of processes and running processes_
_display top 3 cpu (+mem_res) processes_
_display top 3 memory processes_
_display memory, memperc, membar + thresholds_
_display swap, swapperc, swapbar + …
=> add new module: conky

py3status/modules/xrandr.py
This enables primary.
Addresses #1663
=> xrandr: add dynamic primary configuration

py3status/cli.py, py3status/core.py
When I added + fixed `i3status`, there were things that can be simplified. I refactor them now.
* By moving more CLI stuff from core to cli, we can keep hidden options up front. Also, we can use `options` to determine if we need this or not instead of doing them all in core.
* More reusing the variables such as `home_path`, `xdg_home_path`, etc.
* To keep it simple, I remove `get_config` function in favor of `vars(options)`.
* Minor fix there and there to make things line up more.
I clear this out. Maybe I try and document hidden commands next... or should I stop? Wait for No.1 Collaborator? What's the plan for py3status 3.17 too... Thanks.
=> cli, core: refactor cli stuff from core to cli

py3status/modules/sysdata.py
This reduces getting thresholds from `N+1` times to `N+0` times on every interval. `N` might as well be `2`. 
* Skip `max_cpu_mem` threshold on every interval.  (Very likely)
* If users have placeholders, but no colors, we will skip those too on every interval. (Very likely)
* More threshold options (from 6 to 17) to use such as `load{1,5,15}` and others. (Niche)
* Legacy thresholds still supported for user-defined `format` configs. (Very likely)
* New placeholders added in future should have working thresholds out of the box too. (Yay)
* Simplify code by removing `threshold_get_color` function everywhere. (Yay)
~~EDIT: Hold.~~
=> sysdata: optimize thresholds

py3status/modules/thunderbird_todos.py
If `thresholds` is specified...
1) This reduces getting thresholds from `3` times to `0` or more times on every interval.
2) This reduces getting thresholds up to `4` times to `0` or more times on every interval.
This exposes more color thresholds for users to use too. (Niche).
=> thunderbird_todos: optimize thresholds

py3status/modules/sysdata.py
If `cpu_freq_avg` or `cpu_freq_max` is specified in the format... 
1) This reduces getting format_units from `2` times to `1` or `2` on every interval.
2) Toss `names` and `placeholders` into a list of tuples for better readability. (post_config_hook)
3) Avoid unnecessary `if`, `sum`, `max`, `divide`, `multiply`, `len`, `dict`, etc for every interval. (See 1).
4) Kill lines too. (See 2).
=> sysdata: optimize cpu_freqs

py3status/modules/vnstat.py
This replaces coloring with thresholds.
This reduces getting ~~coloring~~ thresholds from `1` time to `0 or more` times on every interval.
* More threshold options (from 1 to 3) to use such as `down`, `up`. (Niche)
* Legacy `coloring` still supported for user-defined `coloring` config. (Not likely)
* New placeholders exposed in future should have working thresholds out of the box too. (Yay)
* Add an example illustrating how we can colorize with thresholds. (Very cool)
=> vnstat: replace coloring with optimized thresholds

py3status/modules/wifi.py
Plz merge `wifi: add optimized thresholds` first.
* Normalize`Exception(STRING_NOT_INSTALLED)`.
* Run three functions once in `post_config_hooks` instead of every interval.
* Fix floating issue with `percent_to_dbm`... `perc / 2` to `perc / 2.0`. 
* Python3 (-85.5, -75.5) vs Python2 (-86, -76)
* Use `self.py3.error` (real error) instead of response return (static error).
* Initialize vars to eliminate `else` statements. Make `dict` in the future.
=> wifi: initial cleanup

py3status/module_test.py, py3status/modules/aws_bill.py, py3status/modules/clock.py, py3status/modules/coin_market.py, py3status/modules/diskdata.py, py3status/modules/google_calendar.py, py3status/modules/graphite.py, py3status/modules/group.py, py3status/modules/hamster.py, py3status/modules/kdeconnector.py, py3status/modules/keyboard_layout.py, py3status/modules/lm_sensors.py, py3status/modules/loadavg.py, py3status/modules/mpris.py, py3status/modules/net_rate.py, py3status/modules/ns_checker.py, py3status/modules/sql.py, py3status/modules/sysdata.py, py3status/modules/timewarrior.py, py3status/modules/tor_rate.py, py3status/modules/velib_metropole.py, py3status/modules/volume_status.py, py3status/modules/vpn_status.py, py3status/modules/window_title_async.py, py3status/modules/wwan_status.py
This is early spring cleaning.
* Don't mention `i3status.conf`. Use `config` instead.
* Change `i3status.conf example:` to `Examples`.
* Fix typos, code no longer relevant, minor fixes, etc. 
* And other actions to kill empty docstrings, lines, deprecated config, etc.
Not to mention there are tests in other PR.
EDIT: If you found typos or such, feel free to share.
EDIT: Plz merge `add consistency tests for the modules` first.. then I revise this.
=> module cleanups and tweaks

py3status/modules/graphite.py
=> graphite: use func mapping instead of eval('func')

py3status/modules/wifi.py
I want to clean up `device auto detection` first before tackling `sudo auto detection`. (Unrelated)
EDIT: I wonder if lack of try/except is a problem on Debian. It works fine for me on Ubuntu.
=> wifi: clean up wifi device auto detection

py3status/modules/mail.py
* Simplify filters by putting it all in a string and run it once of looping. Kill linez too.
* Add `log` option and turn it off for imap accounts because I'm sick of seeing folders in my log.
* Raise error on invalid filters instead of silently failing. Not a bug, but is a good bugfix. Avoid this:
Invalid `filters` was `['*Example*']` instead of `['.*Example.*']`. 
```bash
2019-02-10 00:08:59 WARNING Instance `mail`,
user method `mail` failed (error) mail.py line 251.
2019-02-10 00:08:59 INFO Traceback
error: nothing to repeat at position 0
File "py3status/py3status/module.py", line 911, in run
File "py3status/py3status/modules/mail.py", line 251, in mail
if re.search(_filter, name):
File "/usr/lib/python3.7/re.py", line 183, in search
return _compile(pattern, …
```
=> mail: raise invalid filters, add log to print folders

py3status/modules/sysdata.py
We add used units to our placeholders instead of discarding. This makes `swap` more readable.
```python
sysdata {
format = "Swap [\?color=lightcoral {swap_used:.1f}[\?max_length=1 {swap_used_unit}]"
format += "/{swap_total:.1f}[\?max_length=1 {swap_total_unit}]]"
}
```
(before) `Swap 0.7G/7.7G` vs (after) `Swap 791.3M/7.7G` with `dynamic` (ought to be default).
=> sysdata: add used units

py3status/modules/arch_updates.py
`cower` has been deprecated for a year and a day. The source repo is gone too. We should remove `cower` from `arch_updates`. It's always possible that some users are still using `cower` today. Time to kick them off if that's actually true, I guess. 
Addresses the issues in #1716.
1) >`cower` has been deprecated and is no longer in the AUR available for install.
2) >`auracle` is not mentionned in the doc then x)
Adding `pikaur` or other helpers should be done separately.
=> arch_updates: remove obsolete cower from docs

py3status/modules/arch_updates.py
This simplifies the code by using `py3.command_output` helper everywhere. I delete comments too.
=> arch_updates: use py3.command_output helper

py3status/module.py
This converts composites to pango markup.
Addresses #1719.
=> module: add pango markup conversion

doc/intro.rst, doc/modules.rst, py3status/argparsers.py, py3status/command.py, py3status/docstrings.py, py3status/module.py
Addresses https://github.com/ultrabug/py3status/issues/1692... for Python2. Plz test and merge.
=> URGENT: move list and docstring from py3status to py3-cmd

py3status/modules/wifi.py
We decide `sudo -n` ourselves instead of asking users to see if they need to use `use_sudo`.
Users will still need to do `sudo visudo` and add lines. The nice thing about this is we give `sudo` to the commands that needs it instead of blindly adding it to both. One less config for users to deal with.
Users would now see `wifi: sudo: a password is required` error message instead of `wifi: command failed: Operation not permitted (-1)` or other message if users don't do their `sudo visudo` thing.
=> wifi: remove use_sudo in favor of auto

py3status/modules/weather_owm.py
This flips coordinates from `(lon, lat)` to `(lat, lon)`. 
Addresses #1728.
=> weather_owm: flip coordinates to (lat, lon)

py3status/modules/battery_level.py
`battery_level` module may return an error "list index out of range" in the following situation:
- A system without battery (desktop)
- Connect a device that includes a battery and reports it status back
to Linux (a PS4 controller)
In this case, `/sys/class/power_supply/` exists, so the old check in `battery_level()` pass. However `_extract_battery_information_from_sys()` returns an empty list (since PS4 controller is not a battery),
making the rest of the code fail.
This commit changes the logic in `battery_level()` to check for an empty list instead, and moves the `/sys/class/power_supply/` test inside `_extract_battery_information_from_sys()`.
It also allows `_extract_battery_information_from_acpi()` to run even when `/sys/class/power_supply/` does not exists, however this seems to be …
=> battery_level: Fix case when an invalid battery is detected

py3status/modules/i3pystatus.py
Splitting up commits so the original PR looks more clean. Already approved.
=> i3pystatus: check python first before telling python2 users to install

py3status/modules/i3pystatus.py
When `safeformat` was added to support universal/py3status options, it comes with a new bug (interval). It can create `composite` keys which can lead to unequal contents and frequent updates. I get the first (and only) dict from the composite to make it more comparable.
Even with this fix, I notice that unequal contents and frequent updates were still occurring sometimes so I looked into this. The reason for this is because of various changes... including initial `None`, and that we don't always get `name` and `instance` from the output and/or the composite. In some instances, `module_name + index number` can appear in the dict too. Also, `{"full_text": ""}` is not same as the empty full_text dict with name + instance.
I had two options: To fill the dicts with missing keys or to remove …
=> i3pystatus: remove composites and keys to make dicts more comparable

py3status/core.py, py3status/modules/mpris.py, py3status/py3.py
This fixes #1271 in a not so perfect way... but still works for me
=>  mpris module: add dummy gevent support which breaking GObject.MainLoop

py3status/modules/diskdata.py
This requires #1773 to fetch different list of placeholders for different functions.
```python
names_and_matches = [
("df", ["free", "used", "used_percent", "total_space"]), # placeholders for "df -k"
("diskstats", ["read", "write", "total"]), # placeholders for "cat /proc/diskstats"
]
```
This simplifies/optimize by looping through a list of placeholders to get what we need ~~for each value~~ at each function instead of doing everything at every interval.
* Skips unnecessary `self._format_rate()` function calls.
* `self.py3.format_units()` values + units.
* `self.py3.safe_format()` composites.
* Skips unnecessary `self.py3.safe_format()` composites.
* Uses `post_config_hook` to define things like `disk or all` once.
First commit optimizes things. Second commit sorts methods. This should …
=> diskdata: optimize formatting composites, units, etc 

py3status/modules/nvidia_smi.py
This adds units for memory placeholders. If there are any other placeholders that uses MiB, then we probably could add them to the list too.
@clarfon Can you try this? If you don't use `memory_unit = 'GiB'`, then your `{memory.used_unit}` would be `B` on zero, `MiB` on 1 or above until 1000~ MiB... before it would become `GiB`.. so you could do something like this...
* `{memory.used} {memory.used_unit}/{memory.total} {memory.total_unit}` ... or
* `{memory.used}/{memory.total} {memory.total_unit}` ... with `memory_unit = 'GiB'`.
Addresses #1788.
=> nvidia_smi: add memory units

py3status/modules/wifi.py
This removes `%`, `dBm`, and adds a new placeholder for `MBit/s`. Users ought to be able to customize  thresholds, precision, spacing, `\?if=signal_percent`, etc. @clarfon Can you test this? 
Addresses #1789.
=> wifi: split up unit placeholders, remove round_bitrate

py3status/modules/backlight.py
=> backlight module: rounding float output (for use with the light package)

py3status/modules/volume_status.py
* Replace short args with long args for better readability.
* Remove unused + unneeded variables.
* Eliminates an extra call by using both args at same time. <-- Real reason for this PR. 
* Do nothing with invalid user-defined devices, cards, etc instead of throwing error.
=> volume_status: pamixer cleanups/improvs

py3status/modules/uptime.py
(Alt. PR) This implements `since` strftime formatting in `uptime` instead of new module `uptime_adv`. 
Replaces https://github.com/ultrabug/py3status/pull/1807.
=> uptime: specify strftime characters to display system up since

py3status/modules/volume_status.py
This adds the blocks feature from other modules to volume_status. The last character gets used for values over 100 as per the implementation in battery_level.
=> volume_status: add blocks

py3status/modules/xkb_layouts.py
This introduces a xkb switcher module using classes instead of setxkbmap [+xset] [+xkblayout-state].
Tested OK. Pls read the comments before proceeding with the review. Thx you.
Addresses #1816.
=> new module: xkb_layouts

py3status/modules/weather_owm.py
timezoneapi.io has closed its free API, switch to our own.
as we do not have tz offset any more, drop the offset_gmt parameter
=> weather_owm module: switch from timezoneapi to our own api (Fix #1818)

py3status/core.py
=> Fix typo in docstring

py3status/modules/bitcoin_price.py
Slightly adjust error message to be smaller
=> Change bitcoin_price module api request to http

py3status/modules/nvidia_temp.py
This fixes ``format_temp_separator = '\?color=green , '`` to print green commas instead of literal `\?color=green , ` strings. Note: I changed `|` to ` `.
=> nvidia_temp module: add safeformat for separator, rename separator

py3status/modules/volume_status.py
A series of commits to simplify code.
>Protagonist kills backends, methods, lines, and statements.
>― Quentin Tarantino
=> volume_status module: simplify code

py3status/modules/ns_checker.py
Moving things to `post_config_hook` for `ns_checker`.
=> ns_checker module: use post_config_hook

py3status/modules/imap.py
builds failing rn. pls fix this.
=> imap module: fix black code formatting to pass tests

doc/py3status.html, py3status/core.py, py3status/formatter.py, py3status/i3status.py, py3status/modules/aws_bill.py, py3status/modules/coin_balance.py, py3status/modules/file_status.py, py3status/modules/google_calendar.py, py3status/modules/i3block.py, py3status/modules/i3pystatus.py, py3status/modules/mpris.py, py3status/modules/rate_counter.py, py3status/modules/spotify.py, py3status/modules/wwan_status.py, py3status/modules/xrandr.py, py3status/storage.py, tests/test_formatter.py
=> treewide: fix typos and throw in some grammar improvements 

py3status/modules/suspend_inhibitor.py, py3status/modules/systemd_suspend_inhibitor.py
Hi guys,
I hope the whole family is fine.
I come back with a simple module to be able to quickly inhibit temporary suspend managed with systemd logind.
Hope you will find this usefull.
Regards
=> [module] systemd suspend inhibitor

py3status/modules/backlight.py
since v243 logind provides a dbus method to set the brightness.
This neither needs X nor root privilege.
Use logind as a fallback when xbacklight is not found
I considered having systemd as a third tool next to light and xbacklight, but I think 
having it as a fallback works better since it's not a dedicated tool but something everybody has.
I considered doing a direct dbus call instead of calling busctl, but there is no common way to 
deal with dbus currently, so I went for the easy way.
For reference
https://github.com/systemd/systemd/commit/b3be8c46af32b1135b0e118415eb2060bd69ae1a
https://github.com/systemd/systemd/pull/12413
https://github.com/systemd/systemd/pull/12424
Also note https://github.com/systemd/systemd/issues/14288 that might be a reason to delay this PR
(but still worth …
=> brightness : use logind as a fallback

py3status/modules/imap.py
Hi,
I've added OAuth support to the IMAP module.
Starting in June, Google is [apparently going to stop](https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html) general apps from using password authentication on G Suite accounts. They'd like people to use OAuth instead.
This patch is quite similar to the Google Calendar module (and the same client secret should be able to be used) but it uses google-auth and google-auth-oauthlib instead of oauth2client because apparently [oauth2client is deprecated](https://oauth2client.readthedocs.io/en/latest/).
Let me know if you need any changes made.
=> IMAP: add OAuth2 support

py3status/modules/mpd_status.py
=> Fix mpd color

py3status/modules/mpd_status.py
fixes https://github.com/ultrabug/py3status/issues/1894
=> mpd_status: properly terminate idling thread

py3status/modules/frame.py
Hello,
It's a simple proposition to expose the submodules output that can then be used in conditional formats (see docstring for one example of such use case).
=> frame module: expose output of submodules

py3status/modules/imap.py
=> RFC: implement degraded_on_stale

py3status/modules/do_not_disturb.py
Hi guys,
Here a tiny add, mako support for do do_not_disturb.
@maximbaz can you try ?
Regards,
=> Add Mako support to do_not_disturb, usefull for wayland environment.

py3status/modules/volume_status.py
=> volume_status module: change amixer flag ordering fix #1914

py3status/modules/sysdata.py
Add the following placeholders in `sysdata` module:
- `mem_free`
- `mem_free_unit`
- `mem_free_percent`
- `swap_free`
- `swap_free_unit`
- `swap_free_percent`
=> Add {mem,swap}_free, {mem,swap}_free_unit, {mem,swap}_free_percent

py3status/modules/battery_level.py
Add {power} placeholder. Shows current power consumption or charging
power in Watts. Works only with measurement_mode = 'sys'
Usage: format="{power:4.2f}"
=> battery_level module: add power consumption

py3status/modules/google_calendar.py
Resolving No module named 'apiclient.discovery' error
Tks!
=> py3 - update for google_calendar.py

py3status/modules/prometheus.py
Sorry, I moved this version into a new branch and it looks like silly github's tiny brain doesn't comprehend that and wants a new pull request for it. :-(
So this is a replacement for  Prometheus query module. #1938
=> Prometheus query module.

py3status/modules/battery_level.py
fix #1950 by really checking the dir in /sys contains the needed file (uevent).
=> battery_level: fix filter in /sys

py3status/modules/mpris.py
The artist fields are already joined later in line 558 / 555 .
=> Don't join the artist fields in BrokenDBusMpris

doc/user-contributed-conf-examples.rst
Here are some example configurations.  Feel free to make any cosmetic changes.
=> CorruptCommit 's configuration examples

py3status/modules/coin_market.py
This is a simplified "new module from scratch" in order to use the new url. 
Closes https://github.com/ultrabug/py3status/issues/1913.
=> coin_market: new module from scratch

.github/workflows/ci.yml, README.rst, tox.ini
Since the `master` still does not use this, the results won't be immediately visible in this PR, so you may have to test it in an extra branch on the main repo and only when it works (or needs bugfixing), you can merge it into `master`.
=> Add GitHub Actions CI

py3status/modules/google_calendar.py, py3status/modules/mpris.py, py3status/modules/spotify.py
Individual bits to improve the usage and readability of appropriate time/timedelta classes.
=> Better usage of timedelta/time modules

doc/intro.rst
=> Fix NixOS instructions

py3status/modules/zypper_updates.py
Similar with fedora_updates but without the extra security checks.
=> Add zypper_updates module

py3status/modules/kdeconnector.py
Adapted kdeconnector module to new interface on version 20.12.3
Battery and notifications methods were moved to a subfolder under device_id folder.
=> Adapted to kdeconnect version 20.12.3

py3status/argparsers.py
=> clarify connection between --debug and --log-file options

py3status/modules/lm_sensors.py
Revisiting this one https://github.com/ultrabug/py3status/pull/1533.
=> lm_sensors: replace raw with json output

py3status/modules/arch_updates.py
adds support for https://github.com/morganamilo/paru
=> arch_updates: add paru support

py3status/modules/vpn_status.py
backward compatible version of #2070 thx to @oceyral
=> vpn_status module: fix changed dbus signal handler signature

py3status/modules/do_not_disturb.py
=> do_not_disturb module: handle mako using makoctl

py3status/modules/net_iplist.py
https://unix.stackexchange.com/questions/358982/network-interface-name-has-with-at-sign-what-is-it
=> net_iplist: support parsing iface name with "@" symbol

docs/user-guide/configuration.md, py3status/__init__.py, py3status/core.py
thanks to @pedro-nonfree
closes #42
=> new option py3status.stop_signal to disable i3bar stop/resume

py3status/modules/weather_owm.py
=> weather_owm module: fix forecast by using new onecall api endpoint

py3status/core.py
=> [core] Drop and log negative new_update_due which causes high cpu load and endless loop (Address #2085)

py3status/modules/external_script.py
This fixes #2100. Please let me know if anything else should be done or if any changes are needed.
=> Allow external_script to preserve number formatting

py3status/core.py
Thx Ultrabug for courage to look deeply into problem.
=> [core] Proper prevention for negative update_due and log it as warning.

py3status/core.py
Reverts ultrabug/py3status#2108
=> Revert "[core] Proper prevention for negative update_due and log it as warning."

docs/dev-guide/the-py3-helper.md, py3status/modules/mpris.py, py3status/py3.py
=> py3.safe_format: implement a generic max_width parameter

py3status/modules/xrandr.py
Found it when I looked config examples for issue #2056
=> [xrandr] fix missing " at the end of line (example section).

py3status/modules/volume_status.py
=> volume_status module: use mapped volume with amixer backend.

py3status/core.py
The reporting of an underlying git source does not work in a range of
instances.  For example, if the repo is part of a submodule, then no git
information will be reported.
Using the python git module gives more consistent information about what
git repo that we are running from.
=> Report git commit information consistently

py3status/modules/volume_status.py
=> volume_status module: add start_delay to address issue #2136

py3status/modules/sysdata.py
Workstations with a ZFS filesystem will report an abnormal memory
usage due to the ZFS ARC cache. For example, on my workstation, the
ARC cache takes up 6GB out of the 16GB core memory. Total memory
usage, as reported by py3status, is close to 87%, quite alarming, but
when we *know* about the ZFS cache, this is no big deal.
Note that tools like `top(1)` also get it wrong, but `htop(1)` and
`btop(1)` don't. I actually took this idea from btop.
I didn't make this customizable because there's one of two things
here, either:
1. the user doesn't have a ZFS setup and this will silently
not change anything, or;
2. the use *has* a ZFS setup and they will almost *certainly* want to
count that out of their memory usage
btop(1) actually makes this configurable, but I think that's
superfluous: who …
=> ignore ZFS ARC cache in memory usage

py3status/formatter.py, py3status/modules/google_calendar.py
=> Escape format

py3status/modules/kdeconnector.py
=> kdeconnector module: show cell network type and strength. (#2162)

py3status/modules/bluetooth.py
Support reporting the battery percentage of bluetooth devices if available.
=> bluetooth: Report battery percentage if available

py3status/modules/arch_updates.py
Just added support to show output from `pikaur`: `pacman` wrapper and AUR helper written in python + one line in docs mentioning it's support
=> add support for pikaur AUR helper

py3status/modules/arch_updates.py
Revisiting. Resolves https://github.com/ultrabug/py3status/issues/1716.
=> arch_updates: remove cower support (gone)

CHANGELOG, README.md, docs/dev-guide/the-py3-helper.md, docs/getting-started.md, docs/user-guide/installation.md, py3status/__init__.py, py3status/argparsers.py, py3status/core.py, py3status/module_test.py, py3status/modules/kdeconnector.py, py3status/modules/mpris.py, py3status/py3.py, setup.py
it's time to move on and drop gevent
=> refactor(core): drop deprecrated gevent support

README.md, contrib/py3status.html, py3status/modules/README.md
Closes https://github.com/ultrabug/py3status/issues/2222.
=> docs: fix broken 404 urls

py3status/modules/volume_status.py
=> volume_status module: pamixer: Fix command if device is 0

py3status/modules/dexcom.py
Hi, I made a new module `dexcom`.
Tested OK in the term. Not tested on the bar.
=> add new module: dexcom

py3status/modules/backlight.py
Hello, I added support to brightnessctl into backlight module. This is necessary because light is no longer maintained and brightnessctl is supported on wayland.
=> add brightnessctl support to backlight module

py3status/modules/conky.py
Skip possibly invalid errors coming from upstream soon https://github.com/brndnmtthws/conky/pull/1841/files#diff-1b23d253ee325539fdcd0f4f4b6f6bb6fc04836b3d9942bcca869d5ed5b2ce2fR82-R90 such as...
```
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: http
conky: FOUND: x11
conky: FOUND: wayland
```
This PR is untested.  First reported by Casper The Friendly Ghost. Thanks ~~Casper~~ Su. :ghost:
=> conky: skip invalid conky errors

py3status/modules/weather_owm.py
=> weather_owm module: switch to 3.0 API endpoint as 2.5 is deprecated

py3status/modules/external_script.py
=> external_script: fix clicking on parts of message thx to @lasers

py3status/modules/wwan.py
Replacing pydbus with dbus-python required specific oldschool hardware usage.
Used Huawei E303 wwan adapter whcih I rescued years ago from second hand shop :).
Commit initiative from #2192
=> wwan: replace pydbus with dbus-python

py3status/modules/kdeconnector.py
Tested it with 
majnaro linux python 3.12.6, kdeconnect-cli 24.08
It worked with _bat, _not, _con path
ubuntu 20.04  python3.8.10, kdeconnector-cli 1.4.0
It worked with old path.
Commit initiative from #2192
=> kdeconnector: replace pydbus with dbus-python

py3status/modules/bluetooth.py, py3status/modules/sway_idle.py, py3status/modules/weather_owm.py, py3status/modules/zypper_updates.py
Closes #2268
Closes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082501
=> modules: fix SyntaxWarning for python 3.12+ thx to @sdelafond

py3status/core.py, py3status/modules/kdeconnector.py, py3status/modules/mail.py, tests/test_user_modules.py
=> core: fix usage of deprecated pkg_resources to the @sdelafond
